In [12]:
pip install requests

Requirement already satisfied: requests in c:\Users\Nagarajan Kanagamani\anaconda3\Lib\site-packages (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\Nagarajan Kanagamani\anaconda3\Lib\site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\Nagarajan Kanagamani\anaconda3\Lib\site-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\Nagarajan Kanagamani\anaconda3\Lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\Nagarajan Kanagamani\anaconda3\Lib\site-packages (from requests) (2026.6.17)
Note: you may need to restart the kernel to use updated packages.

In [13]:
import requests

In [35]:
req = "https://dummyjson.com/products"
res = requests.get(req)

In [ ]:
res.json()

{'products': [{'id': 1,
   'title': 'Essence Mascara Lash Princess',
   'description': 'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
   'category': 'beauty',
   'price': 9.99,
   'discountPercentage': 10.48,
   'rating': 2.56,
   'stock': 99,
   'tags': ['beauty', 'mascara'],
   'brand': 'Essence',
   'sku': 'BEA-ESS-ESS-001',
   'weight': 4,
   'dimensions': {'width': 15.14, 'height': 13.08, 'depth': 22.99},
   'warrantyInformation': '1 week warranty',
   'shippingInformation': 'Ships in 3-5 business days',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 3,
     'comment': 'Would not recommend!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Eleanor Collins',
     'reviewerEmail': 'eleanor.collins@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Very satisfied!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Lucas Gordon',
     'reviewerEmail': 'lucas.gordon@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Highly impressed!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Eleanor Collins',
     'reviewerEmail': 'eleanor.collins@x.dummyjson.com'}],
   'returnPolicy': 'No return policy',
   'minimumOrderQuantity': 48,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '5784719087687',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp'},
  {'id': 2,
   'title': 'Eyeshadow Palette with Mirror',
   'description': "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application.",
   'category': 'beauty',
   'price': 19.99,
   'discountPercentage': 18.19,
   'rating': 2.86,
   'stock': 34,
   'tags': ['beauty', 'eyeshadow'],
   'brand': 'Glamour Beauty',
   'sku': 'BEA-GLA-EYE-002',
   'weight': 9,
   'dimensions': {'width': 9.26, 'height': 22.47, 'depth': 27.67},
   'warrantyInformation': '1 year warranty',
   'shippingInformation': 'Ships in 2 weeks',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 5,
     'comment': 'Great product!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Savannah Gomez',
     'reviewerEmail': 'savannah.gomez@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Awesome product!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Christian Perez',
     'reviewerEmail': 'christian.perez@x.dummyjson.com'},
    {'rating': 1,
     'comment': 'Poor quality!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Nicholas Bailey',
     'reviewerEmail': 'nicholas.bailey@x.dummyjson.com'}],
   'returnPolicy': '7 days return policy',
   'minimumOrderQuantity': 20,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '9170275171413',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp'},
  {'id': 3,
   'title': 'Powder Canister',
   'description': 'The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.',
   'category': 'beauty',
   'price': 14.99,
   'discountPercentage': 9.84,
   'rating': 4.64,
   'stock': 89,
   'tags': ['beauty', 'face powder'],
   'brand': 'Velvet Touch',
   'sku': 'BEA-VEL-POW-003',
   'weight': 8,
   'dimensions': {'width': 29.27, 'height': 27.93, 'depth': 20.59},
   'warrantyInformation': '3 months warranty',
   'shippingInformation': 'Ships in 1-2 business days',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 4,
     'comment': 'Would buy again!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Alexander Jones',
     'reviewerEmail': 'alexander.jones@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Highly impressed!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Elijah Cruz',
     'reviewerEmail': 'elijah.cruz@x.dummyjson.com'},
    {'rating': 1,
     'comment': 'Very dissatisfied!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Avery Perez',
     'reviewerEmail': 'avery.perez@x.dummyjson.com'}],
   'returnPolicy': 'No return policy',
   'minimumOrderQuantity': 22,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '8418883906837',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp'},
  {'id': 4,
   'title': 'Red Lipstick',
   'description': 'The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.',
   'category': 'beauty',
   'price': 12.99,
   'discountPercentage': 12.16,
   'rating': 4.36,
   'stock': 91,
   'tags': ['beauty', 'lipstick'],
   'brand': 'Chic Cosmetics',
   'sku': 'BEA-CHI-LIP-004',
   'weight': 1,
   'dimensions': {'width': 18.11, 'height': 28.38, 'depth': 22.17},
   'warrantyInformation': '3 year warranty',
   'shippingInformation': 'Ships in 1 week',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 4,
     'comment': 'Great product!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Liam Garcia',
     'reviewerEmail': 'liam.garcia@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Great product!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Ruby Andrews',
     'reviewerEmail': 'ruby.andrews@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Would buy again!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Clara Berry',
     'reviewerEmail': 'clara.berry@x.dummyjson.com'}],
   'returnPolicy': '7 days return policy',
   'minimumOrderQuantity': 40,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '9467746727219',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/beauty/red-lipstick/1.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp'},
  {'id': 5,
   'title': 'Red Nail Polish',
   'description': 'The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.',
   'category': 'beauty',
   'price': 8.99,
   'discountPercentage': 11.44,
   'rating': 4.32,
   'stock': 79,
   'tags': ['beauty', 'nail polish'],
   'brand': 'Nail Couture',
   'sku': 'BEA-NAI-NAI-005',
   'weight': 8,
   'dimensions': {'width': 21.63, 'height': 16.48, 'depth': 29.84},
   'warrantyInformation': '1 month warranty',
   'shippingInformation': 'Ships overnight',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 2,
     'comment': 'Poor quality!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Benjamin Wilson',
     'reviewerEmail': 'benjamin.wilson@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Great product!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Liam Smith',
     'reviewerEmail': 'liam.smith@x.dummyjson.com'},
    {'rating': 1,
     'comment': 'Very unhappy with my purchase!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Clara Berry',
     'reviewerEmail': 'clara.berry@x.dummyjson.com'}],
   'returnPolicy': 'No return policy',
   'minimumOrderQuantity': 22,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '4063010628104',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/1.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/thumbnail.webp'},
  {'id': 6,
   'title': 'Calvin Klein CK One',
   'description': "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It's a versatile fragrance suitable for everyday wear.",
   'category': 'fragrances',
   'price': 49.99,
   'discountPercentage': 1.89,
   'rating': 4.37,
   'stock': 29,
   'tags': ['fragrances', 'perfumes'],
   'brand': 'Calvin Klein',
   'sku': 'FRA-CAL-CAL-006',
   'weight': 7,
   'dimensions': {'width': 29.36, 'height': 27.76, 'depth': 20.72},
   'warrantyInformation': '1 week warranty',
   'shippingInformation': 'Ships overnight',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 2,
     'comment': 'Very disappointed!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Layla Young',
     'reviewerEmail': 'layla.young@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Fast shipping!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Daniel Cook',
     'reviewerEmail': 'daniel.cook@x.dummyjson.com'},
    {'rating': 3,
     'comment': 'Not as described!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Jacob Cooper',
     'reviewerEmail': 'jacob.cooper@x.dummyjson.com'}],
   'returnPolicy': '90 days return policy',
   'minimumOrderQuantity': 9,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '2451534060749',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/1.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/2.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/3.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/thumbnail.webp'},
  {'id': 7,
   'title': 'Chanel Coco Noir Eau De',
   'description': 'Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.',
   'category': 'fragrances',
   'price': 129.99,
   'discountPercentage': 16.51,
   'rating': 4.26,
   'stock': 58,
   'tags': ['fragrances', 'perfumes'],
   'brand': 'Chanel',
   'sku': 'FRA-CHA-CHA-007',
   'weight': 7,
   'dimensions': {'width': 24.5, 'height': 25.7, 'depth': 25.98},
   'warrantyInformation': '3 year warranty',
   'shippingInformation': 'Ships overnight',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 4,
     'comment': 'Highly impressed!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Ruby Andrews',
     'reviewerEmail': 'ruby.andrews@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Awesome product!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Leah Henderson',
     'reviewerEmail': 'leah.henderson@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Very happy with my purchase!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Xavier Wright',
     'reviewerEmail': 'xavier.wright@x.dummyjson.com'}],
   'returnPolicy': 'No return policy',
   'minimumOrderQuantity': 1,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '4091737746820',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/1.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/2.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/3.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/thumbnail.webp'},
  {'id': 8,
   'title': "Dior J'adore",
   'description': "J'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.",
   'category': 'fragrances',
   'price': 89.99,
   'discountPercentage': 14.72,
   'rating': 3.8,
   'stock': 98,
   'tags': ['fragrances', 'perfumes'],
   'brand': 'Dior',
   'sku': 'FRA-DIO-DIO-008',
   'weight': 4,
   'dimensions': {'width': 27.67, 'height': 28.28, 'depth': 11.83},
   'warrantyInformation': '1 week warranty',
   'shippingInformation': 'Ships in 2 weeks',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 5,
     'comment': 'Great value for money!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Nicholas Bailey',
     'reviewerEmail': 'nicholas.bailey@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Great value for money!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Penelope Harper',
     'reviewerEmail': 'penelope.harper@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Great product!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Emma Miller',
     'reviewerEmail': 'emma.miller@x.dummyjson.com'}],
   'returnPolicy': '7 days return policy',
   'minimumOrderQuantity': 10,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '1445086097250',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ["https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/1.webp",
    "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/2.webp",
    "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/3.webp"],
   'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"},
  {'id': 9,
   'title': 'Dolce Shine Eau de',
   'description': "Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It's a joyful and youthful scent.",
   'category': 'fragrances',
   'price': 69.99,
   'discountPercentage': 0.62,
   'rating': 3.96,
   'stock': 4,
   'tags': ['fragrances', 'perfumes'],
   'brand': 'Dolce & Gabbana',
   'sku': 'FRA-DOL-DOL-009',
   'weight': 6,
   'dimensions': {'width': 27.28, 'height': 29.88, 'depth': 18.3},
   'warrantyInformation': '3 year warranty',
   'shippingInformation': 'Ships in 1 month',
   'availabilityStatus': 'Low Stock',
   'reviews': [{'rating': 4,
     'comment': 'Would buy again!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Mateo Bennett',
     'reviewerEmail': 'mateo.bennett@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Highly recommended!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Nolan Gonzalez',
     'reviewerEmail': 'nolan.gonzalez@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Very happy with my purchase!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Aurora Lawson',
     'reviewerEmail': 'aurora.lawson@x.dummyjson.com'}],
   'returnPolicy': '7 days return policy',
   'minimumOrderQuantity': 2,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '3023868210708',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/1.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/2.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/3.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp'},
  {'id': 10,
   'title': 'Gucci Bloom Eau de',
   'description': "Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It's a modern and romantic scent.",
   'category': 'fragrances',
   'price': 79.99,
   'discountPercentage': 14.39,
   'rating': 2.74,
   'stock': 91,
   'tags': ['fragrances', 'perfumes'],
   'brand': 'Gucci',
   'sku': 'FRA-GUC-GUC-010',
   'weight': 7,
   'dimensions': {'width': 20.92, 'height': 21.68, 'depth': 11.2},
   'warrantyInformation': '6 months warranty',
   'shippingInformation': 'Ships overnight',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 1,
     'comment': 'Very dissatisfied!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Cameron Perez',
     'reviewerEmail': 'cameron.perez@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Very happy with my purchase!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Daniel Cook',
     'reviewerEmail': 'daniel.cook@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Highly impressed!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Addison Wright',
     'reviewerEmail': 'addison.wright@x.dummyjson.com'}],
   'returnPolicy': 'No return policy',
   'minimumOrderQuantity': 2,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '3170832177880',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/1.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/2.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/3.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/thumbnail.webp'},
  {'id': 11,
   'title': 'Annibale Colombo Bed',
   'description': 'The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.',
   'category': 'furniture',
   'price': 1899.99,
   'discountPercentage': 8.57,
   'rating': 4.77,
   'stock': 88,
   'tags': ['furniture', 'beds'],
   'brand': 'Annibale Colombo',
   'sku': 'FUR-ANN-ANN-011',
   'weight': 10,
   'dimensions': {'width': 28.16, 'height': 25.36, 'depth': 17.28},
   'warrantyInformation': '1 year warranty',
   'shippingInformation': 'Ships in 1 month',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 2,
     'comment': 'Would not recommend!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Christopher West',
     'reviewerEmail': 'christopher.west@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Highly impressed!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Vivian Carter',
     'reviewerEmail': 'vivian.carter@x.dummyjson.com'},
    {'rating': 1,
     'comment': 'Poor quality!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Mason Wright',
     'reviewerEmail': 'mason.wright@x.dummyjson.com'}],
   'returnPolicy': 'No return policy',
   'minimumOrderQuantity': 1,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '3610757456581',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/1.webp',
    'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/2.webp',
    'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/3.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp'},
  {'id': 12,
   'title': 'Annibale Colombo Sofa',
   'description': 'The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.',
   'category': 'furniture',
   'price': 2499.99,
   'discountPercentage': 14.4,

In [ ]:
res.status_code

200

In [ ]:
import pandas as pd

In [ ]:
# Create a DataFrame from the JSON response
dataProduts = pd.DataFrame(res.json()['products'])
dataProduts

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,dimensions,warrantyInformation,shippingInformation,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,"{'width': 15.14, 'height': 13.08, 'depth': 22.99}",1 week warranty,Ships in 3-5 business days,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",No return policy,48,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,"{'width': 9.26, 'height': 22.47, 'depth': 27.67}",1 year warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,20,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,...,"{'width': 29.27, 'height': 27.93, 'depth': 20.59}",3 months warranty,Ships in 1-2 business days,In Stock,"[{'rating': 4, 'comment': 'Would buy again!', ...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,...,"{'width': 18.11, 'height': 28.38, 'depth': 22.17}",3 year warranty,Ships in 1 week,In Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",7 days return policy,40,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,...,"{'width': 21.63, 'height': 16.48, 'depth': 29.84}",1 month warranty,Ships overnight,In Stock,"[{'rating': 2, 'comment': 'Poor quality!', 'da...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
5,6,Calvin Klein CK One,CK One by Calvin Klein is a classic unisex fra...,fragrances,49.99,1.89,4.37,29,"[fragrances, perfumes]",Calvin Klein,...,"{'width': 29.36, 'height': 27.76, 'depth': 20.72}",1 week warranty,Ships overnight,In Stock,"[{'rating': 2, 'comment': 'Very disappointed!'...",90 days return policy,9,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...
6,7,Chanel Coco Noir Eau De,Coco Noir by Chanel is an elegant and mysterio...,fragrances,129.99,16.51,4.26,58,"[fragrances, perfumes]",Chanel,...,"{'width': 24.5, 'height': 25.7, 'depth': 25.98}",3 year warranty,Ships overnight,In Stock,"[{'rating': 4, 'comment': 'Highly impressed!',...",No return policy,1,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...
7,8,Dior J'adore,J'adore by Dior is a luxurious and floral frag...,fragrances,89.99,14.72,3.80,98,"[fragrances, perfumes]",Dior,...,"{'width': 27.67, 'height': 28.28, 'depth': 11.83}",1 week warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Great value for mon...",7 days return policy,10,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...
8,9,Dolce Shine Eau de,Dolce Shine by Dolce & Gabbana is a vibrant an...,fragrances,69.99,0.62,3.96,4,"[fragrances, perfumes]",Dolce & Gabbana,...,"{'width': 27.28, 'height': 29.88, 'depth': 18.3}",3 year warranty,Ships in 1 month,Low Stock,"[{'rating': 4, 'comment': 'Would buy again!', ...",7 days return policy,2,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...
9,10,Gucci Bloom Eau de,Gucci Bloom by Gucci is a floral and captivati...,fragrances,79.99,14.39,2.74,91,"[fragrances, perfumes]",Gucci,...,"{'width': 20.92, 'height': 21.68, 'depth': 11.2}",6 months warranty,Ships overnight,In Stock,"[{'rating': 1, 'comment': 'Very dissatisfied!'...",No return policy,2,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...
10,11,Annibale Colombo Bed,The Annibale Colombo Bed is a luxurious and el...,furniture,1899.99,8.57,4.77,88,"[furniture, beds]",Annibale Colombo,...,"{'width': 28.16, 'height': 25.36, 'depth': 17.28}",1 year warranty,Ships in 1 month,In Stock,"[{'rating': 2, 'comment': 'Would not recommend...",No return policy,1,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...
11,12,Annibale Colombo Sofa,The Annibale Colombo Sofa is a sophisticated a...,furniture,2499.99,14.40,3.92,60,"[furniture, sofas]",Annibale Colombo,...,"{'width': 12.75, 'height': 20.55, 'depth': 19.06}",Lifetime warranty,Ships in 1 week,In Stock,"[{'rating': 3, 'comment': 'Very unhappy with m...",7 days return policy,1,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...
12,13,Bedside Table African Cherry,The Bedside Table in African Cherry is a styli...,furniture,299.99,19.09,2.87,64,"[furniture, bedside tables]",Furniture Co.,...,"{'width': 13.47, 'height': 24.99, 'depth': 27.35}",5 year warranty,Ships overnight,In Stock,"[{'rating': 4, 'comment': 'Excellent quality!'...",7 days return policy,3,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...
13,14,Knoll Saarinen Executive Conference Chair,The Knoll Saarinen Executive Conference Chair ...,furniture,499.99,2.01,4.88,26,"[furniture, office chairs]",Knoll,...,"{'width': 13.81, 'height': 7.5, 'depth': 5.62}",2 year warranty,Ships overnight,In Stock,"[{'rating': 2, 'comment': 'Waste of money!', '...",60 days return policy,5,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...
14,15,Wooden Bathroom Sink With Mirror,The Wooden Bathroom Sink with Mirror is a uniq...,furniture,799.99,8.80,3.59,7,"[furniture, bathroom]",Bath Trends,...,"{'width': 7.98, 'height': 8.88, 'depth': 28.46}",3 year warranty,Ships in 3-5 business days,Low Stock,"[{'rating': 4, 'comment': 'Fast shipping!', 'd...",60 days return policy,2,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...
15,16,Apple,"Fresh and crisp apples, perfect for snacking o...",groceries,1.99,12.62,4.19,8,[fruits],NaN,...,"{'width': 13.66, 'height': 11.01, 'depth': 9.73}",3 year warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Very satisfied!', '...",90 days return policy,7,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
16,17,Beef Steak,"High-quality beef steak, great for grilling or...",groceries,12.99,9.61,4.47,86,[meat],NaN,...,"{'width': 18.9, 'height': 5.77, 'depth': 18.57}",3 year warranty,Ships overnight,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",60 days return policy,43,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
17,18,Cat Food,Nutritious cat food formulated to meet the die...,groceries,8.99,9.58,3.13,46,"[pet supplies, cat food]",NaN,...,"{'width': 18.08, 'height': 9.26, 'depth': 21.86}",1 year warranty,Ships overnight,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",No return policy,18,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
18,19,Chicken Meat,"Fresh and tender chicken meat, suitable for va...",groceries,9.99,13.70,3.19,97,[meat],NaN,...,"{'width': 11.03, 'height': 22.11, 'depth': 16.01}",1 year warranty,Ships in 1 month,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
19,20,Cooking Oil,"Versatile cooking oil suitable for frying, sau...",groceries,4.99,9.33,4.80,10,[cooking essentials],NaN,...,"{'width': 19.95, 'height': 27.54, 'depth': 24.86}",Lifetime warranty,Ships in 1-2 business days,In Stock,"[{'rating': 5, 'comment': 'Very happy with my ...",30 days return policy,46,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
20,21,Cucumber,"Crisp and hydrating cucumbers, ideal for salad...",groceries,1.49,0.16,4.07,84,[vegetables],NaN,...,"{'width': 12.8, 'height': 28.38, 'depth': 21.34}",2 year warranty,Ships in 1-2 business days,In Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",7 days return policy,2,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
21,22,Dog Food,Specially formulated dog food designed to prov...,groceries,10.99,10.27,4.55,71,"[pet supplies, dog food]",NaN,...,"{'width': 16.93, 'height': 27.15, 'depth': 9.29}",No warranty,Ships in 1-2 business days,In Stock,"[{'rating': 5, 'comment': 'Excellent quality!'...",60 days return policy,43,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
22,23,Eggs,"Fresh eggs, a versatile ingredient for baking,...",groceries,2.99,11.05,2.53,9,[dairy],NaN,...,"{'width': 11.42, 'height': 7.44, 'depth': 16.95}",1 week warranty,Ships in 1 week,In Stock,"[{'rating': 3, 'comment': 'Disappointing produ...",No return policy,32,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
23,24,Fish Steak,"Quality fish steak, suitable for grilling, bak...",groceries,14.99,4.23,3.78,74,[seafood],NaN,...,"{'width': 14.95, 'height': 26.31, 'depth': 11.27}",1 month warranty,Ships in 3-5 business days,In Stock,"[{'rating': 2, 'comment': 'Would not buy again...",60 days return policy,50,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
24,25,Green Bell Pepper,"Fresh and vibrant green bell pepper, perfect f...",groceries,1.29,0.16,3.25,33,[vegetables],NaN,...,"{'width': 15.33, 'height': 26.65, 'depth': 14.44}",1 month warranty,Ships in 1 week,In Stock,"[{'rating': 4, 'comment': 'Highly recommended!...",30 days return policy,12,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
25,26,Green Chili Pepper,"Spicy green chili pepper, ideal for adding hea...",groceries,0.99,1.00,3.66,3,[vegetables],NaN,...,"{'width': 15.38, 'height': 18.12, 'depth': 19.92}",2 year warranty,Ships in 1 week,Low Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",30 days return policy,39,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
26,27,Honey Jar,"Pure and natural honey in a convenient jar, pe...",groceries,6.99,14.40,3.97,34,[condiments],NaN,...,"{'width': 9.28, 'height': 21.72, 'depth': 17.74}",1 month warranty,Ships in 1-2 business days,In Stock,"[{'rating': 1, 'comment': 'Very disappointed!'...",90 days return policy,47,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
27,28,Ice Cream,"Creamy and delicious ice cream, available in v...",groceries,5.49,8.69,3.39,27,[desserts],NaN,...,"{'width': 14.83, 'height': 15.07, 'depth': 24.2}",1 month warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Very pleased!', 'da...",No return policy,42,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
28,29,Juice,"Refreshing fruit juice, packed with vitamins a...",groceries,3.99,12.06,3.94,50,[beverages],NaN,...,"{'width': 18.56, 'height': 21.46, 'depth': 28.02}",6 months warranty,Ships in 1 week,In Stock,"[{'rating': 5, 'comment': 'Excellent quality!'...",No return policy,25,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
29,30,Kiwi,"Nutrient-rich kiwi, perfect for snacking or ad...",groceries,2.49,15.22,4.93,99,[fruits],NaN,...,"{'width': 19.4, 'height': 18.67, 'depth': 17.13}",6 months warranty,Ships overnight,In Stock,"[{'rating': 4, 'comment': 'Highly recommended!...",7 days return policy,30,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...

In [21]:
# Normalize the JSON data to create a flat table
normalized_data = pd.json_normalize(res.json(), 'products')
normalized_data

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,minimumOrderQuantity,images,thumbnail,dimensions.width,dimensions.height,dimensions.depth,meta.createdAt,meta.updatedAt,meta.barcode,meta.qrCode
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,48,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,15.14,13.08,22.99,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,5784719087687,https://cdn.dummyjson.com/public/qr-code.png
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,20,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,9.26,22.47,27.67,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9170275171413,https://cdn.dummyjson.com/public/qr-code.png
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,...,22,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,29.27,27.93,20.59,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,8418883906837,https://cdn.dummyjson.com/public/qr-code.png
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,...,40,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,18.11,28.38,22.17,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9467746727219,https://cdn.dummyjson.com/public/qr-code.png
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,...,22,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,21.63,16.48,29.84,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,4063010628104,https://cdn.dummyjson.com/public/qr-code.png
5,6,Calvin Klein CK One,CK One by Calvin Klein is a classic unisex fra...,fragrances,49.99,1.89,4.37,29,"[fragrances, perfumes]",Calvin Klein,...,9,[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...,29.36,27.76,20.72,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,2451534060749,https://cdn.dummyjson.com/public/qr-code.png
6,7,Chanel Coco Noir Eau De,Coco Noir by Chanel is an elegant and mysterio...,fragrances,129.99,16.51,4.26,58,"[fragrances, perfumes]",Chanel,...,1,[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...,24.50,25.70,25.98,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,4091737746820,https://cdn.dummyjson.com/public/qr-code.png
7,8,Dior J'adore,J'adore by Dior is a luxurious and floral frag...,fragrances,89.99,14.72,3.80,98,"[fragrances, perfumes]",Dior,...,10,[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...,27.67,28.28,11.83,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,1445086097250,https://cdn.dummyjson.com/public/qr-code.png
8,9,Dolce Shine Eau de,Dolce Shine by Dolce & Gabbana is a vibrant an...,fragrances,69.99,0.62,3.96,4,"[fragrances, perfumes]",Dolce & Gabbana,...,2,[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...,27.28,29.88,18.30,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,3023868210708,https://cdn.dummyjson.com/public/qr-code.png
9,10,Gucci Bloom Eau de,Gucci Bloom by Gucci is a floral and captivati...,fragrances,79.99,14.39,2.74,91,"[fragrances, perfumes]",Gucci,...,2,[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...,20.92,21.68,11.20,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,3170832177880,https://cdn.dummyjson.com/public/qr-code.png
10,11,Annibale Colombo Bed,The Annibale Colombo Bed is a luxurious and el...,furniture,1899.99,8.57,4.77,88,"[furniture, beds]",Annibale Colombo,...,1,[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...,28.16,25.36,17.28,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,3610757456581,https://cdn.dummyjson.com/public/qr-code.png
11,12,Annibale Colombo Sofa,The Annibale Colombo Sofa is a sophisticated a...,furniture,2499.99,14.40,3.92,60,"[furniture, sofas]",Annibale Colombo,...,1,[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...,12.75,20.55,19.06,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,1777662847736,https://cdn.dummyjson.com/public/qr-code.png
12,13,Bedside Table African Cherry,The Bedside Table in African Cherry is a styli...,furniture,299.99,19.09,2.87,64,"[furniture, bedside tables]",Furniture Co.,...,3,[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...,13.47,24.99,27.35,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,6441287925979,https://cdn.dummyjson.com/public/qr-code.png
13,14,Knoll Saarinen Executive Conference Chair,The Knoll Saarinen Executive Conference Chair ...,furniture,499.99,2.01,4.88,26,"[furniture, office chairs]",Knoll,...,5,[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...,13.81,7.50,5.62,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,8919386859966,https://cdn.dummyjson.com/public/qr-code.png
14,15,Wooden Bathroom Sink With Mirror,The Wooden Bathroom Sink with Mirror is a uniq...,furniture,799.99,8.80,3.59,7,"[furniture, bathroom]",Bath Trends,...,2,[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...,7.98,8.88,28.46,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,1958104402873,https://cdn.dummyjson.com/public/qr-code.png
15,16,Apple,"Fresh and crisp apples, perfect for snacking o...",groceries,1.99,12.62,4.19,8,[fruits],NaN,...,7,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,13.66,11.01,9.73,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,7962803553314,https://cdn.dummyjson.com/public/qr-code.png
16,17,Beef Steak,"High-quality beef steak, great for grilling or...",groceries,12.99,9.61,4.47,86,[meat],NaN,...,43,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,18.90,5.77,18.57,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,5640063409695,https://cdn.dummyjson.com/public/qr-code.png
17,18,Cat Food,Nutritious cat food formulated to meet the die...,groceries,8.99,9.58,3.13,46,"[pet supplies, cat food]",NaN,...,18,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,18.08,9.26,21.86,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,1483991328610,https://cdn.dummyjson.com/public/qr-code.png
18,19,Chicken Meat,"Fresh and tender chicken meat, suitable for va...",groceries,9.99,13.70,3.19,97,[meat],NaN,...,22,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,11.03,22.11,16.01,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,8829514594521,https://cdn.dummyjson.com/public/qr-code.png
19,20,Cooking Oil,"Versatile cooking oil suitable for frying, sau...",groceries,4.99,9.33,4.80,10,[cooking essentials],NaN,...,46,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,19.95,27.54,24.86,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,4874727824518,https://cdn.dummyjson.com/public/qr-code.png
20,21,Cucumber,"Crisp and hydrating cucumbers, ideal for salad...",groceries,1.49,0.16,4.07,84,[vegetables],NaN,...,2,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,12.80,28.38,21.34,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,5300066378225,https://cdn.dummyjson.com/public/qr-code.png
21,22,Dog Food,Specially formulated dog food designed to prov...,groceries,10.99,10.27,4.55,71,"[pet supplies, dog food]",NaN,...,43,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,16.93,27.15,9.29,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,5906686116469,https://cdn.dummyjson.com/public/qr-code.png
22,23,Eggs,"Fresh eggs, a versatile ingredient for baking,...",groceries,2.99,11.05,2.53,9,[dairy],NaN,...,32,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,11.42,7.44,16.95,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,3478638588469,https://cdn.dummyjson.com/public/qr-code.png
23,24,Fish Steak,"Quality fish steak, suitable for grilling, bak...",groceries,14.99,4.23,3.78,74,[seafood],NaN,...,50,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,14.95,26.31,11.27,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9595036192098,https://cdn.dummyjson.com/public/qr-code.png
24,25,Green Bell Pepper,"Fresh and vibrant green bell pepper, perfect f...",groceries,1.29,0.16,3.25,33,[vegetables],NaN,...,12,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,15.33,26.65,14.44,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,2365227493323,https://cdn.dummyjson.com/public/qr-code.png
25,26,Green Chili Pepper,"Spicy green chili pepper, ideal for adding hea...",groceries,0.99,1.00,3.66,3,[vegetables],NaN,...,39,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,15.38,18.12,19.92,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9335000538563,https://cdn.dummyjson.com/public/qr-code.png
26,27,Honey Jar,"Pure and natural honey in a convenient jar, pe...",groceries,6.99,14.40,3.97,34,[condiments],NaN,...,47,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,9.28,21.72,17.74,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,6354306346329,https://cdn.dummyjson.com/public/qr-code.png
27,28,Ice Cream,"Creamy and delicious ice cream, available in v...",groceries,5.49,8.69,3.39,27,[desserts],NaN,...,42,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,14.83,15.07,24.20,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,0788954559076,https://cdn.dummyjson.com/public/qr-code.png
28,29,Juice,"Refreshing fruit juice, packed with vitamins a...",groceries,3.99,12.06,3.94,50,[beverages],NaN,...,25,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,18.56,21.46,28.02,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,6936112580956,https://cdn.dummyjson.com/public/qr-code.png
29,30,Kiwi,"Nutrient-rich kiwi, perfect for snacking or ad...",groceries,2.49,15.22,4.93,99,[fruits],NaN,...,30,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,19.40,18.67,17.13,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,2530169917252,https://cdn.dummyjson.com/public/qr-code.png

In [26]:
# Pandas have loc & iloc methods to select data from a DataFrame. The loc method is used to select data by label, while the iloc method is used to select data by index.
#  Loc method is used to select data by label, while the iloc method is used to select data by index.
# iloc method is used to select data by index, while the loc method is used to select data by label.
normalized_data.loc[0:5, ['id', 'reviews', 'title', 'price']]

,id,reviews,title,price
0,1,"[{'rating': 3, 'comment': 'Would not recommend...",Essence Mascara Lash Princess,9.99
1,2,"[{'rating': 5, 'comment': 'Great product!', 'd...",Eyeshadow Palette with Mirror,19.99
2,3,"[{'rating': 4, 'comment': 'Would buy again!', ...",Powder Canister,14.99
3,4,"[{'rating': 4, 'comment': 'Great product!', 'd...",Red Lipstick,12.99
4,5,"[{'rating': 2, 'comment': 'Poor quality!', 'da...",Red Nail Polish,8.99
5,6,"[{'rating': 2, 'comment': 'Very disappointed!'...",Calvin Klein CK One,49.99

In [28]:
normalized_data.shape #tell s the number of rows and columns in the DataFrame. It returns a tuple where the first element is the number of rows and the second element is the number of columns.

(30, 27)

In [29]:
normalized_data.info() # provides a concise summary of the DataFrame, including the number of non-null entries, data types of each column, and memory usage.

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    30 non-null     int64
 1   title                 30 non-null     str
 2   description           30 non-null     str
 3   category              30 non-null     str
 4   price                 30 non-null     float64
 5   discountPercentage    30 non-null     float64
 6   rating                30 non-null     float64
 7   stock                 30 non-null     int64
 8   tags                  30 non-null     object
 9   brand                 15 non-null     str
 10  sku                   30 non-null     str
 11  weight                30 non-null     int64
 12  warrantyInformation   30 non-null     str
 13  shippingInformation   30 non-null     str
 14  availabilityStatus    30 non-null     str
 15  reviews               30 non-null     object
 16  returnPolicy          30 non-null     str
 17  minimumOrderQuantity  30 non-null     int64
 18  images                30 non-null     object
 19  thumbnail             30 non-null     str
 20  dimensions.width      30 non-null     float64
 21  dimensions.height     30 non-null     float64
 22  dimensions.depth      30 non-null     float64
 23  meta.createdAt        30 non-null     str
 24  meta.updatedAt        30 non-null     str
 25  meta.barcode          30 non-null     str
 26  meta.qrCode           30 non-null     str
dtypes: float64(6), int64(4), object(3), str(14)
memory usage: 18.5+ KB

In [30]:
normalized_data.describe() # provides a statistical summary of the numerical columns in the DataFrame, including count, mean, standard deviation, minimum, maximum, and quartile values.

,id,price,discountPercentage,rating,stock,weight,minimumOrderQuantity,dimensions.width,dimensions.height,dimensions.depth
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,15.500000,219.250000,9.839667,3.858333,54.933333,5.800000,21.533333,17.660333,20.519333,19.346333
std,8.803408,570.491833,5.456157,0.714660,33.816883,3.231312,17.571005,6.173358,7.530940,6.323488
min,1.000000,0.990000,0.160000,2.530000,3.000000,1.000000,1.000000,7.980000,5.770000,5.620000
25%,8.250000,5.115000,8.600000,3.285000,27.500000,2.500000,3.500000,13.517500,15.422500,16.245000
50%,15.500000,11.990000,10.375000,3.950000,59.000000,6.000000,21.000000,16.155000,21.915000,19.490000
75%,22.750000,77.490000,14.217500,4.367500,87.500000,8.750000,39.750000,20.677500,27.025000,23.897500
max,30.000000,2499.990000,19.090000,4.930000,99.000000,10.000000,50.000000,29.360000,29.880000,29.840000

In [32]:
normalized_data.isnull() #is null() method is used to detect missing values in a DataFrame. It returns a DataFrame of the same shape as the original, where each cell contains a boolean value indicating whether the corresponding cell in the original DataFrame is null (True) or not null (False).

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,minimumOrderQuantity,images,thumbnail,dimensions.width,dimensions.height,dimensions.depth,meta.createdAt,meta.updatedAt,meta.barcode,meta.qrCode
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
# In sum we can pass axis=0 to count the number of missing values in each column, or axis=1 to count the number of missing values in each row.
normalized_data.isnull().sum() #isnull().sum() method is used to count the number of missing values in each column of a DataFrame. It returns a Series where the index represents the column names and the values represent the count of missing values in each column.

id                       0
title                    0
description              0
category                 0
price                    0
discountPercentage       0
rating                   0
stock                    0
tags                     0
brand                   15
sku                      0
weight                   0
warrantyInformation      0
shippingInformation      0
availabilityStatus       0
reviews                  0
returnPolicy             0
minimumOrderQuantity     0
images                   0
thumbnail                0
dimensions.width         0
dimensions.height        0
dimensions.depth         0
meta.createdAt           0
meta.updatedAt           0
meta.barcode             0
meta.qrCode              0
dtype: int64

In [34]:
normalized_data.describe().T

,count,mean,std,min,25%,50%,75%,max
id,30.0,15.500000,8.803408,1.00,8.2500,15.500,22.7500,30.00
price,30.0,219.250000,570.491833,0.99,5.1150,11.990,77.4900,2499.99
discountPercentage,30.0,9.839667,5.456157,0.16,8.6000,10.375,14.2175,19.09
rating,30.0,3.858333,0.714660,2.53,3.2850,3.950,4.3675,4.93
stock,30.0,54.933333,33.816883,3.00,27.5000,59.000,87.5000,99.00
weight,30.0,5.800000,3.231312,1.00,2.5000,6.000,8.7500,10.00
minimumOrderQuantity,30.0,21.533333,17.571005,1.00,3.5000,21.000,39.7500,50.00
dimensions.width,30.0,17.660333,6.173358,7.98,13.5175,16.155,20.6775,29.36
dimensions.height,30.0,20.519333,7.530940,5.77,15.4225,21.915,27.0250,29.88
dimensions.depth,30.0,19.346333,6.323488,5.62,16.2450,19.490,23.8975,29.84

In [37]:
normalized_data.sort_values(by='title') #sort_values() method is used to sort the DataFrame by one or more columns. It returns a new DataFrame with the rows sorted in ascending or descending order based on the specified column(s).

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,minimumOrderQuantity,images,thumbnail,dimensions.width,dimensions.height,dimensions.depth,meta.createdAt,meta.updatedAt,meta.barcode,meta.qrCode
10,11,Annibale Colombo Bed,The Annibale Colombo Bed is a luxurious and el...,furniture,1899.99,8.57,4.77,88,"[furniture, beds]",Annibale Colombo,...,1,[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...,28.16,25.36,17.28,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,3610757456581,https://cdn.dummyjson.com/public/qr-code.png
11,12,Annibale Colombo Sofa,The Annibale Colombo Sofa is a sophisticated a...,furniture,2499.99,14.40,3.92,60,"[furniture, sofas]",Annibale Colombo,...,1,[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...,12.75,20.55,19.06,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,1777662847736,https://cdn.dummyjson.com/public/qr-code.png
15,16,Apple,"Fresh and crisp apples, perfect for snacking o...",groceries,1.99,12.62,4.19,8,[fruits],NaN,...,7,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,13.66,11.01,9.73,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,7962803553314,https://cdn.dummyjson.com/public/qr-code.png
12,13,Bedside Table African Cherry,The Bedside Table in African Cherry is a styli...,furniture,299.99,19.09,2.87,64,"[furniture, bedside tables]",Furniture Co.,...,3,[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...,13.47,24.99,27.35,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,6441287925979,https://cdn.dummyjson.com/public/qr-code.png
16,17,Beef Steak,"High-quality beef steak, great for grilling or...",groceries,12.99,9.61,4.47,86,[meat],NaN,...,43,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,18.90,5.77,18.57,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,5640063409695,https://cdn.dummyjson.com/public/qr-code.png
5,6,Calvin Klein CK One,CK One by Calvin Klein is a classic unisex fra...,fragrances,49.99,1.89,4.37,29,"[fragrances, perfumes]",Calvin Klein,...,9,[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...,29.36,27.76,20.72,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,2451534060749,https://cdn.dummyjson.com/public/qr-code.png
17,18,Cat Food,Nutritious cat food formulated to meet the die...,groceries,8.99,9.58,3.13,46,"[pet supplies, cat food]",NaN,...,18,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,18.08,9.26,21.86,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,1483991328610,https://cdn.dummyjson.com/public/qr-code.png
6,7,Chanel Coco Noir Eau De,Coco Noir by Chanel is an elegant and mysterio...,fragrances,129.99,16.51,4.26,58,"[fragrances, perfumes]",Chanel,...,1,[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...,24.50,25.70,25.98,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,4091737746820,https://cdn.dummyjson.com/public/qr-code.png
18,19,Chicken Meat,"Fresh and tender chicken meat, suitable for va...",groceries,9.99,13.70,3.19,97,[meat],NaN,...,22,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,11.03,22.11,16.01,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,8829514594521,https://cdn.dummyjson.com/public/qr-code.png
19,20,Cooking Oil,"Versatile cooking oil suitable for frying, sau...",groceries,4.99,9.33,4.80,10,[cooking essentials],NaN,...,46,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,19.95,27.54,24.86,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,4874727824518,https://cdn.dummyjson.com/public/qr-code.png
20,21,Cucumber,"Crisp and hydrating cucumbers, ideal for salad...",groceries,1.49,0.16,4.07,84,[vegetables],NaN,...,2,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,12.80,28.38,21.34,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,5300066378225,https://cdn.dummyjson.com/public/qr-code.png
7,8,Dior J'adore,J'adore by Dior is a luxurious and floral frag...,fragrances,89.99,14.72,3.80,98,"[fragrances, perfumes]",Dior,...,10,[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...,27.67,28.28,11.83,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,1445086097250,https://cdn.dummyjson.com/public/qr-code.png
21,22,Dog Food,Specially formulated dog food designed to prov...,groceries,10.99,10.27,4.55,71,"[pet supplies, dog food]",NaN,...,43,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,16.93,27.15,9.29,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,5906686116469,https://cdn.dummyjson.com/public/qr-code.png
8,9,Dolce Shine Eau de,Dolce Shine by Dolce & Gabbana is a vibrant an...,fragrances,69.99,0.62,3.96,4,"[fragrances, perfumes]",Dolce & Gabbana,...,2,[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...,27.28,29.88,18.30,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,3023868210708,https://cdn.dummyjson.com/public/qr-code.png
22,23,Eggs,"Fresh eggs, a versatile ingredient for baking,...",groceries,2.99,11.05,2.53,9,[dairy],NaN,...,32,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,11.42,7.44,16.95,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,3478638588469,https://cdn.dummyjson.com/public/qr-code.png
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,48,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,15.14,13.08,22.99,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,5784719087687,https://cdn.dummyjson.com/public/qr-code.png
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,20,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,9.26,22.47,27.67,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9170275171413,https://cdn.dummyjson.com/public/qr-code.png
23,24,Fish Steak,"Quality fish steak, suitable for grilling, bak...",groceries,14.99,4.23,3.78,74,[seafood],NaN,...,50,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,14.95,26.31,11.27,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9595036192098,https://cdn.dummyjson.com/public/qr-code.png
24,25,Green Bell Pepper,"Fresh and vibrant green bell pepper, perfect f...",groceries,1.29,0.16,3.25,33,[vegetables],NaN,...,12,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,15.33,26.65,14.44,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,2365227493323,https://cdn.dummyjson.com/public/qr-code.png
25,26,Green Chili Pepper,"Spicy green chili pepper, ideal for adding hea...",groceries,0.99,1.00,3.66,3,[vegetables],NaN,...,39,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,15.38,18.12,19.92,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9335000538563,https://cdn.dummyjson.com/public/qr-code.png
9,10,Gucci Bloom Eau de,Gucci Bloom by Gucci is a floral and captivati...,fragrances,79.99,14.39,2.74,91,"[fragrances, perfumes]",Gucci,...,2,[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...,20.92,21.68,11.20,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,3170832177880,https://cdn.dummyjson.com/public/qr-code.png
26,27,Honey Jar,"Pure and natural honey in a convenient jar, pe...",groceries,6.99,14.40,3.97,34,[condiments],NaN,...,47,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,9.28,21.72,17.74,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,6354306346329,https://cdn.dummyjson.com/public/qr-code.png
27,28,Ice Cream,"Creamy and delicious ice cream, available in v...",groceries,5.49,8.69,3.39,27,[desserts],NaN,...,42,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,14.83,15.07,24.20,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,0788954559076,https://cdn.dummyjson.com/public/qr-code.png
28,29,Juice,"Refreshing fruit juice, packed with vitamins a...",groceries,3.99,12.06,3.94,50,[beverages],NaN,...,25,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,18.56,21.46,28.02,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,6936112580956,https://cdn.dummyjson.com/public/qr-code.png
29,30,Kiwi,"Nutrient-rich kiwi, perfect for snacking or ad...",groceries,2.49,15.22,4.93,99,[fruits],NaN,...,30,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,19.40,18.67,17.13,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,2530169917252,https://cdn.dummyjson.com/public/qr-code.png
13,14,Knoll Saarinen Executive Conference Chair,The Knoll Saarinen Executive Conference Chair ...,furniture,499.99,2.01,4.88,26,"[furniture, office chairs]",Knoll,...,5,[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...,13.81,7.50,5.62,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,8919386859966,https://cdn.dummyjson.com/public/qr-code.png
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,...,22,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,29.27,27.93,20.59,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,8418883906837,https://cdn.dummyjson.com/public/qr-code.png
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,...,40,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,18.11,28.38,22.17,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9467746727219,https://cdn.dummyjson.com/public/qr-code.png
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,...,22,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,21.63,16.48,29.84,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,4063010628104,https://cdn.dummyjson.com/public/qr-code.png
14,15,Wooden Bathroom Sink With Mirror,The Wooden Bathroom Sink with Mirror is a uniq...,furniture,799.99,8.80,3.59,7,"[furniture, bathroom]",Bath Trends,...,2,[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...,7.98,8.88,28.46,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,1958104402873,https://cdn.dummyjson.com/public/qr-code.png

In [38]:
normalized_data['brand'].nunique() #nunique() method is used to count the number of unique values in a column. It returns an integer representing the count of unique values in the specified column.

14

In [39]:
normalized_data['brand'].unique() #unique() method is used to get the unique values in a column of a DataFrame. It returns an array of unique values present in the specified column.

<ArrowStringArray>
[         'Essence',   'Glamour Beauty',     'Velvet Touch',
   'Chic Cosmetics',     'Nail Couture',     'Calvin Klein',
           'Chanel',             'Dior',  'Dolce & Gabbana',
            'Gucci', 'Annibale Colombo',    'Furniture Co.',
            'Knoll',      'Bath Trends',                nan]
Length: 15, dtype: str

In [41]:
normalized_data[normalized_data.duplicated(subset=['brand'], keep=False)] #duplicated() method is used to identify duplicate rows in a DataFrame based on one or more columns. It returns a boolean Series indicating whether each row is a duplicate (True) or not (False). The subset parameter specifies the column(s) to consider for identifying duplicates, and the keep parameter determines which duplicates to mark as True (first occurrence, last occurrence, or all occurrences).

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,minimumOrderQuantity,images,thumbnail,dimensions.width,dimensions.height,dimensions.depth,meta.createdAt,meta.updatedAt,meta.barcode,meta.qrCode
10,11,Annibale Colombo Bed,The Annibale Colombo Bed is a luxurious and el...,furniture,1899.99,8.57,4.77,88,"[furniture, beds]",Annibale Colombo,...,1,[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...,28.16,25.36,17.28,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,3610757456581,https://cdn.dummyjson.com/public/qr-code.png
11,12,Annibale Colombo Sofa,The Annibale Colombo Sofa is a sophisticated a...,furniture,2499.99,14.40,3.92,60,"[furniture, sofas]",Annibale Colombo,...,1,[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...,12.75,20.55,19.06,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,1777662847736,https://cdn.dummyjson.com/public/qr-code.png
15,16,Apple,"Fresh and crisp apples, perfect for snacking o...",groceries,1.99,12.62,4.19,8,[fruits],NaN,...,7,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,13.66,11.01,9.73,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,7962803553314,https://cdn.dummyjson.com/public/qr-code.png
16,17,Beef Steak,"High-quality beef steak, great for grilling or...",groceries,12.99,9.61,4.47,86,[meat],NaN,...,43,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,18.90,5.77,18.57,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,5640063409695,https://cdn.dummyjson.com/public/qr-code.png
17,18,Cat Food,Nutritious cat food formulated to meet the die...,groceries,8.99,9.58,3.13,46,"[pet supplies, cat food]",NaN,...,18,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,18.08,9.26,21.86,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,1483991328610,https://cdn.dummyjson.com/public/qr-code.png
18,19,Chicken Meat,"Fresh and tender chicken meat, suitable for va...",groceries,9.99,13.70,3.19,97,[meat],NaN,...,22,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,11.03,22.11,16.01,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,8829514594521,https://cdn.dummyjson.com/public/qr-code.png
19,20,Cooking Oil,"Versatile cooking oil suitable for frying, sau...",groceries,4.99,9.33,4.80,10,[cooking essentials],NaN,...,46,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,19.95,27.54,24.86,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,4874727824518,https://cdn.dummyjson.com/public/qr-code.png
20,21,Cucumber,"Crisp and hydrating cucumbers, ideal for salad...",groceries,1.49,0.16,4.07,84,[vegetables],NaN,...,2,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,12.80,28.38,21.34,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,5300066378225,https://cdn.dummyjson.com/public/qr-code.png
21,22,Dog Food,Specially formulated dog food designed to prov...,groceries,10.99,10.27,4.55,71,"[pet supplies, dog food]",NaN,...,43,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,16.93,27.15,9.29,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,5906686116469,https://cdn.dummyjson.com/public/qr-code.png
22,23,Eggs,"Fresh eggs, a versatile ingredient for baking,...",groceries,2.99,11.05,2.53,9,[dairy],NaN,...,32,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,11.42,7.44,16.95,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,3478638588469,https://cdn.dummyjson.com/public/qr-code.png
23,24,Fish Steak,"Quality fish steak, suitable for grilling, bak...",groceries,14.99,4.23,3.78,74,[seafood],NaN,...,50,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,14.95,26.31,11.27,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9595036192098,https://cdn.dummyjson.com/public/qr-code.png
24,25,Green Bell Pepper,"Fresh and vibrant green bell pepper, perfect f...",groceries,1.29,0.16,3.25,33,[vegetables],NaN,...,12,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,15.33,26.65,14.44,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,2365227493323,https://cdn.dummyjson.com/public/qr-code.png
25,26,Green Chili Pepper,"Spicy green chili pepper, ideal for adding hea...",groceries,0.99,1.00,3.66,3,[vegetables],NaN,...,39,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,15.38,18.12,19.92,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9335000538563,https://cdn.dummyjson.com/public/qr-code.png
26,27,Honey Jar,"Pure and natural honey in a convenient jar, pe...",groceries,6.99,14.40,3.97,34,[condiments],NaN,...,47,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,9.28,21.72,17.74,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,6354306346329,https://cdn.dummyjson.com/public/qr-code.png
27,28,Ice Cream,"Creamy and delicious ice cream, available in v...",groceries,5.49,8.69,3.39,27,[desserts],NaN,...,42,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,14.83,15.07,24.20,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,0788954559076,https://cdn.dummyjson.com/public/qr-code.png
28,29,Juice,"Refreshing fruit juice, packed with vitamins a...",groceries,3.99,12.06,3.94,50,[beverages],NaN,...,25,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,18.56,21.46,28.02,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,6936112580956,https://cdn.dummyjson.com/public/qr-code.png
29,30,Kiwi,"Nutrient-rich kiwi, perfect for snacking or ad...",groceries,2.49,15.22,4.93,99,[fruits],NaN,...,30,[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...,19.40,18.67,17.13,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,2530169917252,https://cdn.dummyjson.com/public/qr-code.png

In [ ]:
a=5
a

5

In [ ]:
a=5
print(a)

5

In [ ]:
res.text[0]

'{'

In [ ]:
import json
json.loads(res.text)['products']

[{'id': 1,
  'title': 'Essence Mascara Lash Princess',
  'description': 'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
  'category': 'beauty',
  'price': 9.99,
  'discountPercentage': 10.48,
  'rating': 2.56,
  'stock': 99,
  'tags': ['beauty', 'mascara'],
  'brand': 'Essence',
  'sku': 'BEA-ESS-ESS-001',
  'weight': 4,
  'dimensions': {'width': 15.14, 'height': 13.08, 'depth': 22.99},
  'warrantyInformation': '1 week warranty',
  'shippingInformation': 'Ships in 3-5 business days',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 3,
    'comment': 'Would not recommend!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Eleanor Collins',
    'reviewerEmail': 'eleanor.collins@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Very satisfied!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Lucas Gordon',
    'reviewerEmail': 'lucas.gordon@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Highly impressed!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Eleanor Collins',
    'reviewerEmail': 'eleanor.collins@x.dummyjson.com'}],
  'returnPolicy': 'No return policy',
  'minimumOrderQuantity': 48,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '5784719087687',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp'},
 {'id': 2,
  'title': 'Eyeshadow Palette with Mirror',
  'description': "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application.",
  'category': 'beauty',
  'price': 19.99,
  'discountPercentage': 18.19,
  'rating': 2.86,
  'stock': 34,
  'tags': ['beauty', 'eyeshadow'],
  'brand': 'Glamour Beauty',
  'sku': 'BEA-GLA-EYE-002',
  'weight': 9,
  'dimensions': {'width': 9.26, 'height': 22.47, 'depth': 27.67},
  'warrantyInformation': '1 year warranty',
  'shippingInformation': 'Ships in 2 weeks',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 5,
    'comment': 'Great product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Savannah Gomez',
    'reviewerEmail': 'savannah.gomez@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Awesome product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Christian Perez',
    'reviewerEmail': 'christian.perez@x.dummyjson.com'},
   {'rating': 1,
    'comment': 'Poor quality!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Nicholas Bailey',
    'reviewerEmail': 'nicholas.bailey@x.dummyjson.com'}],
  'returnPolicy': '7 days return policy',
  'minimumOrderQuantity': 20,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '9170275171413',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp'},
 {'id': 3,
  'title': 'Powder Canister',
  'description': 'The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.',
  'category': 'beauty',
  'price': 14.99,
  'discountPercentage': 9.84,
  'rating': 4.64,
  'stock': 89,
  'tags': ['beauty', 'face powder'],
  'brand': 'Velvet Touch',
  'sku': 'BEA-VEL-POW-003',
  'weight': 8,
  'dimensions': {'width': 29.27, 'height': 27.93, 'depth': 20.59},
  'warrantyInformation': '3 months warranty',
  'shippingInformation': 'Ships in 1-2 business days',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 4,
    'comment': 'Would buy again!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Alexander Jones',
    'reviewerEmail': 'alexander.jones@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Highly impressed!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Elijah Cruz',
    'reviewerEmail': 'elijah.cruz@x.dummyjson.com'},
   {'rating': 1,
    'comment': 'Very dissatisfied!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Avery Perez',
    'reviewerEmail': 'avery.perez@x.dummyjson.com'}],
  'returnPolicy': 'No return policy',
  'minimumOrderQuantity': 22,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '8418883906837',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp'},
 {'id': 4,
  'title': 'Red Lipstick',
  'description': 'The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.',
  'category': 'beauty',
  'price': 12.99,
  'discountPercentage': 12.16,
  'rating': 4.36,
  'stock': 91,
  'tags': ['beauty', 'lipstick'],
  'brand': 'Chic Cosmetics',
  'sku': 'BEA-CHI-LIP-004',
  'weight': 1,
  'dimensions': {'width': 18.11, 'height': 28.38, 'depth': 22.17},
  'warrantyInformation': '3 year warranty',
  'shippingInformation': 'Ships in 1 week',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 4,
    'comment': 'Great product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Liam Garcia',
    'reviewerEmail': 'liam.garcia@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Great product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Ruby Andrews',
    'reviewerEmail': 'ruby.andrews@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Would buy again!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Clara Berry',
    'reviewerEmail': 'clara.berry@x.dummyjson.com'}],
  'returnPolicy': '7 days return policy',
  'minimumOrderQuantity': 40,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '9467746727219',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/beauty/red-lipstick/1.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp'},
 {'id': 5,
  'title': 'Red Nail Polish',
  'description': 'The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.',
  'category': 'beauty',
  'price': 8.99,
  'discountPercentage': 11.44,
  'rating': 4.32,
  'stock': 79,
  'tags': ['beauty', 'nail polish'],
  'brand': 'Nail Couture',
  'sku': 'BEA-NAI-NAI-005',
  'weight': 8,
  'dimensions': {'width': 21.63, 'height': 16.48, 'depth': 29.84},
  'warrantyInformation': '1 month warranty',
  'shippingInformation': 'Ships overnight',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 2,
    'comment': 'Poor quality!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Benjamin Wilson',
    'reviewerEmail': 'benjamin.wilson@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Great product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Liam Smith',
    'reviewerEmail': 'liam.smith@x.dummyjson.com'},
   {'rating': 1,
    'comment': 'Very unhappy with my purchase!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Clara Berry',
    'reviewerEmail': 'clara.berry@x.dummyjson.com'}],
  'returnPolicy': 'No return policy',
  'minimumOrderQuantity': 22,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '4063010628104',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/1.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/thumbnail.webp'},
 {'id': 6,
  'title': 'Calvin Klein CK One',
  'description': "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It's a versatile fragrance suitable for everyday wear.",
  'category': 'fragrances',
  'price': 49.99,
  'discountPercentage': 1.89,
  'rating': 4.37,
  'stock': 29,
  'tags': ['fragrances', 'perfumes'],
  'brand': 'Calvin Klein',
  'sku': 'FRA-CAL-CAL-006',
  'weight': 7,
  'dimensions': {'width': 29.36, 'height': 27.76, 'depth': 20.72},
  'warrantyInformation': '1 week warranty',
  'shippingInformation': 'Ships overnight',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 2,
    'comment': 'Very disappointed!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Layla Young',
    'reviewerEmail': 'layla.young@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Fast shipping!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Daniel Cook',
    'reviewerEmail': 'daniel.cook@x.dummyjson.com'},
   {'rating': 3,
    'comment': 'Not as described!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Jacob Cooper',
    'reviewerEmail': 'jacob.cooper@x.dummyjson.com'}],
  'returnPolicy': '90 days return policy',
  'minimumOrderQuantity': 9,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '2451534060749',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/1.webp',
   'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/2.webp',
   'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/3.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/thumbnail.webp'},
 {'id': 7,
  'title': 'Chanel Coco Noir Eau De',
  'description': 'Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.',
  'category': 'fragrances',
  'price': 129.99,
  'discountPercentage': 16.51,
  'rating': 4.26,
  'stock': 58,
  'tags': ['fragrances', 'perfumes'],
  'brand': 'Chanel',
  'sku': 'FRA-CHA-CHA-007',
  'weight': 7,
  'dimensions': {'width': 24.5, 'height': 25.7, 'depth': 25.98},
  'warrantyInformation': '3 year warranty',
  'shippingInformation': 'Ships overnight',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 4,
    'comment': 'Highly impressed!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Ruby Andrews',
    'reviewerEmail': 'ruby.andrews@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Awesome product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Leah Henderson',
    'reviewerEmail': 'leah.henderson@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Very happy with my purchase!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Xavier Wright',
    'reviewerEmail': 'xavier.wright@x.dummyjson.com'}],
  'returnPolicy': 'No return policy',
  'minimumOrderQuantity': 1,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '4091737746820',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/1.webp',
   'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/2.webp',
   'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/3.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/thumbnail.webp'},
 {'id': 8,
  'title': "Dior J'adore",
  'description': "J'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.",
  'category': 'fragrances',
  'price': 89.99,
  'discountPercentage': 14.72,
  'rating': 3.8,
  'stock': 98,
  'tags': ['fragrances', 'perfumes'],
  'brand': 'Dior',
  'sku': 'FRA-DIO-DIO-008',
  'weight': 4,
  'dimensions': {'width': 27.67, 'height': 28.28, 'depth': 11.83},
  'warrantyInformation': '1 week warranty',
  'shippingInformation': 'Ships in 2 weeks',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 5,
    'comment': 'Great value for money!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Nicholas Bailey',
    'reviewerEmail': 'nicholas.bailey@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Great value for money!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Penelope Harper',
    'reviewerEmail': 'penelope.harper@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Great product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Emma Miller',
    'reviewerEmail': 'emma.miller@x.dummyjson.com'}],
  'returnPolicy': '7 days return policy',
  'minimumOrderQuantity': 10,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '1445086097250',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ["https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/1.webp",
   "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/2.webp",
   "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/3.webp"],
  'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"},
 {'id': 9,
  'title': 'Dolce Shine Eau de',
  'description': "Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It's a joyful and youthful scent.",
  'category': 'fragrances',
  'price': 69.99,
  'discountPercentage': 0.62,
  'rating': 3.96,
  'stock': 4,
  'tags': ['fragrances', 'perfumes'],
  'brand': 'Dolce & Gabbana',
  'sku': 'FRA-DOL-DOL-009',
  'weight': 6,
  'dimensions': {'width': 27.28, 'height': 29.88, 'depth': 18.3},
  'warrantyInformation': '3 year warranty',
  'shippingInformation': 'Ships in 1 month',
  'availabilityStatus': 'Low Stock',
  'reviews': [{'rating': 4,
    'comment': 'Would buy again!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Mateo Bennett',
    'reviewerEmail': 'mateo.bennett@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Highly recommended!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Nolan Gonzalez',
    'reviewerEmail': 'nolan.gonzalez@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Very happy with my purchase!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Aurora Lawson',
    'reviewerEmail': 'aurora.lawson@x.dummyjson.com'}],
  'returnPolicy': '7 days return policy',
  'minimumOrderQuantity': 2,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '3023868210708',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/1.webp',
   'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/2.webp',
   'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/3.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp'},
 {'id': 10,
  'title': 'Gucci Bloom Eau de',
  'description': "Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It's a modern and romantic scent.",
  'category': 'fragrances',
  'price': 79.99,
  'discountPercentage': 14.39,
  'rating': 2.74,
  'stock': 91,
  'tags': ['fragrances', 'perfumes'],
  'brand': 'Gucci',
  'sku': 'FRA-GUC-GUC-010',
  'weight': 7,
  'dimensions': {'width': 20.92, 'height': 21.68, 'depth': 11.2},
  'warrantyInformation': '6 months warranty',
  'shippingInformation': 'Ships overnight',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 1,
    'comment': 'Very dissatisfied!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Cameron Perez',
    'reviewerEmail': 'cameron.perez@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Very happy with my purchase!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Daniel Cook',
    'reviewerEmail': 'daniel.cook@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Highly impressed!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Addison Wright',
    'reviewerEmail': 'addison.wright@x.dummyjson.com'}],
  'returnPolicy': 'No return policy',
  'minimumOrderQuantity': 2,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '3170832177880',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/1.webp',
   'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/2.webp',
   'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/3.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/thumbnail.webp'},
 {'id': 11,
  'title': 'Annibale Colombo Bed',
  'description': 'The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.',
  'category': 'furniture',
  'price': 1899.99,
  'discountPercentage': 8.57,
  'rating': 4.77,
  'stock': 88,
  'tags': ['furniture', 'beds'],
  'brand': 'Annibale Colombo',
  'sku': 'FUR-ANN-ANN-011',
  'weight': 10,
  'dimensions': {'width': 28.16, 'height': 25.36, 'depth': 17.28},
  'warrantyInformation': '1 year warranty',
  'shippingInformation': 'Ships in 1 month',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 2,
    'comment': 'Would not recommend!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Christopher West',
    'reviewerEmail': 'christopher.west@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Highly impressed!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Vivian Carter',
    'reviewerEmail': 'vivian.carter@x.dummyjson.com'},
   {'rating': 1,
    'comment': 'Poor quality!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Mason Wright',
    'reviewerEmail': 'mason.wright@x.dummyjson.com'}],
  'returnPolicy': 'No return policy',
  'minimumOrderQuantity': 1,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '3610757456581',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/1.webp',
   'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/2.webp',
   'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/3.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp'},
 {'id': 12,
  'title': 'Annibale Colombo Sofa',
  'description': 'The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.',
  'category': 'furniture',
  'price': 2499.99,
  'discountPercentage': 14.4,
  'rating': 3.92,
  'stock': 60,
  'tags': ['furniture', 'sofas'],
  'brand': 'Annibale Colombo',
  'sku': 'FUR-ANN-ANN-012',
  'weight': 6,
  'dimensions': {'width': 12.75, 'height': 20.55, 'depth': 19.06},
  'warrantyInformation': 'Lifetime warranty',
  'shippingInformation': 'Ships in 1 week',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 3,
    'comment': 'Very unhappy with my purchase!',
    'date': '2025-04-30T09:41:02.053Z',

In [ ]:
res.json()['products']

[{'id': 1,
  'title': 'Essence Mascara Lash Princess',
  'description': 'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
  'category': 'beauty',
  'price': 9.99,
  'discountPercentage': 10.48,
  'rating': 2.56,
  'stock': 99,
  'tags': ['beauty', 'mascara'],
  'brand': 'Essence',
  'sku': 'BEA-ESS-ESS-001',
  'weight': 4,
  'dimensions': {'width': 15.14, 'height': 13.08, 'depth': 22.99},
  'warrantyInformation': '1 week warranty',
  'shippingInformation': 'Ships in 3-5 business days',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 3,
    'comment': 'Would not recommend!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Eleanor Collins',
    'reviewerEmail': 'eleanor.collins@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Very satisfied!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Lucas Gordon',
    'reviewerEmail': 'lucas.gordon@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Highly impressed!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Eleanor Collins',
    'reviewerEmail': 'eleanor.collins@x.dummyjson.com'}],
  'returnPolicy': 'No return policy',
  'minimumOrderQuantity': 48,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '5784719087687',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp'},
 {'id': 2,
  'title': 'Eyeshadow Palette with Mirror',
  'description': "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application.",
  'category': 'beauty',
  'price': 19.99,
  'discountPercentage': 18.19,
  'rating': 2.86,
  'stock': 34,
  'tags': ['beauty', 'eyeshadow'],
  'brand': 'Glamour Beauty',
  'sku': 'BEA-GLA-EYE-002',
  'weight': 9,
  'dimensions': {'width': 9.26, 'height': 22.47, 'depth': 27.67},
  'warrantyInformation': '1 year warranty',
  'shippingInformation': 'Ships in 2 weeks',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 5,
    'comment': 'Great product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Savannah Gomez',
    'reviewerEmail': 'savannah.gomez@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Awesome product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Christian Perez',
    'reviewerEmail': 'christian.perez@x.dummyjson.com'},
   {'rating': 1,
    'comment': 'Poor quality!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Nicholas Bailey',
    'reviewerEmail': 'nicholas.bailey@x.dummyjson.com'}],
  'returnPolicy': '7 days return policy',
  'minimumOrderQuantity': 20,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '9170275171413',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp'},
 {'id': 3,
  'title': 'Powder Canister',
  'description': 'The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.',
  'category': 'beauty',
  'price': 14.99,
  'discountPercentage': 9.84,
  'rating': 4.64,
  'stock': 89,
  'tags': ['beauty', 'face powder'],
  'brand': 'Velvet Touch',
  'sku': 'BEA-VEL-POW-003',
  'weight': 8,
  'dimensions': {'width': 29.27, 'height': 27.93, 'depth': 20.59},
  'warrantyInformation': '3 months warranty',
  'shippingInformation': 'Ships in 1-2 business days',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 4,
    'comment': 'Would buy again!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Alexander Jones',
    'reviewerEmail': 'alexander.jones@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Highly impressed!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Elijah Cruz',
    'reviewerEmail': 'elijah.cruz@x.dummyjson.com'},
   {'rating': 1,
    'comment': 'Very dissatisfied!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Avery Perez',
    'reviewerEmail': 'avery.perez@x.dummyjson.com'}],
  'returnPolicy': 'No return policy',
  'minimumOrderQuantity': 22,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '8418883906837',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp'},
 {'id': 4,
  'title': 'Red Lipstick',
  'description': 'The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.',
  'category': 'beauty',
  'price': 12.99,
  'discountPercentage': 12.16,
  'rating': 4.36,
  'stock': 91,
  'tags': ['beauty', 'lipstick'],
  'brand': 'Chic Cosmetics',
  'sku': 'BEA-CHI-LIP-004',
  'weight': 1,
  'dimensions': {'width': 18.11, 'height': 28.38, 'depth': 22.17},
  'warrantyInformation': '3 year warranty',
  'shippingInformation': 'Ships in 1 week',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 4,
    'comment': 'Great product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Liam Garcia',
    'reviewerEmail': 'liam.garcia@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Great product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Ruby Andrews',
    'reviewerEmail': 'ruby.andrews@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Would buy again!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Clara Berry',
    'reviewerEmail': 'clara.berry@x.dummyjson.com'}],
  'returnPolicy': '7 days return policy',
  'minimumOrderQuantity': 40,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '9467746727219',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/beauty/red-lipstick/1.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp'},
 {'id': 5,
  'title': 'Red Nail Polish',
  'description': 'The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.',
  'category': 'beauty',
  'price': 8.99,
  'discountPercentage': 11.44,
  'rating': 4.32,
  'stock': 79,
  'tags': ['beauty', 'nail polish'],
  'brand': 'Nail Couture',
  'sku': 'BEA-NAI-NAI-005',
  'weight': 8,
  'dimensions': {'width': 21.63, 'height': 16.48, 'depth': 29.84},
  'warrantyInformation': '1 month warranty',
  'shippingInformation': 'Ships overnight',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 2,
    'comment': 'Poor quality!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Benjamin Wilson',
    'reviewerEmail': 'benjamin.wilson@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Great product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Liam Smith',
    'reviewerEmail': 'liam.smith@x.dummyjson.com'},
   {'rating': 1,
    'comment': 'Very unhappy with my purchase!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Clara Berry',
    'reviewerEmail': 'clara.berry@x.dummyjson.com'}],
  'returnPolicy': 'No return policy',
  'minimumOrderQuantity': 22,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '4063010628104',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/1.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/thumbnail.webp'},
 {'id': 6,
  'title': 'Calvin Klein CK One',
  'description': "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It's a versatile fragrance suitable for everyday wear.",
  'category': 'fragrances',
  'price': 49.99,
  'discountPercentage': 1.89,
  'rating': 4.37,
  'stock': 29,
  'tags': ['fragrances', 'perfumes'],
  'brand': 'Calvin Klein',
  'sku': 'FRA-CAL-CAL-006',
  'weight': 7,
  'dimensions': {'width': 29.36, 'height': 27.76, 'depth': 20.72},
  'warrantyInformation': '1 week warranty',
  'shippingInformation': 'Ships overnight',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 2,
    'comment': 'Very disappointed!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Layla Young',
    'reviewerEmail': 'layla.young@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Fast shipping!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Daniel Cook',
    'reviewerEmail': 'daniel.cook@x.dummyjson.com'},
   {'rating': 3,
    'comment': 'Not as described!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Jacob Cooper',
    'reviewerEmail': 'jacob.cooper@x.dummyjson.com'}],
  'returnPolicy': '90 days return policy',
  'minimumOrderQuantity': 9,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '2451534060749',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/1.webp',
   'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/2.webp',
   'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/3.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/thumbnail.webp'},
 {'id': 7,
  'title': 'Chanel Coco Noir Eau De',
  'description': 'Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.',
  'category': 'fragrances',
  'price': 129.99,
  'discountPercentage': 16.51,
  'rating': 4.26,
  'stock': 58,
  'tags': ['fragrances', 'perfumes'],
  'brand': 'Chanel',
  'sku': 'FRA-CHA-CHA-007',
  'weight': 7,
  'dimensions': {'width': 24.5, 'height': 25.7, 'depth': 25.98},
  'warrantyInformation': '3 year warranty',
  'shippingInformation': 'Ships overnight',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 4,
    'comment': 'Highly impressed!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Ruby Andrews',
    'reviewerEmail': 'ruby.andrews@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Awesome product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Leah Henderson',
    'reviewerEmail': 'leah.henderson@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Very happy with my purchase!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Xavier Wright',
    'reviewerEmail': 'xavier.wright@x.dummyjson.com'}],
  'returnPolicy': 'No return policy',
  'minimumOrderQuantity': 1,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '4091737746820',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/1.webp',
   'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/2.webp',
   'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/3.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/thumbnail.webp'},
 {'id': 8,
  'title': "Dior J'adore",
  'description': "J'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.",
  'category': 'fragrances',
  'price': 89.99,
  'discountPercentage': 14.72,
  'rating': 3.8,
  'stock': 98,
  'tags': ['fragrances', 'perfumes'],
  'brand': 'Dior',
  'sku': 'FRA-DIO-DIO-008',
  'weight': 4,
  'dimensions': {'width': 27.67, 'height': 28.28, 'depth': 11.83},
  'warrantyInformation': '1 week warranty',
  'shippingInformation': 'Ships in 2 weeks',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 5,
    'comment': 'Great value for money!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Nicholas Bailey',
    'reviewerEmail': 'nicholas.bailey@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Great value for money!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Penelope Harper',
    'reviewerEmail': 'penelope.harper@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Great product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Emma Miller',
    'reviewerEmail': 'emma.miller@x.dummyjson.com'}],
  'returnPolicy': '7 days return policy',
  'minimumOrderQuantity': 10,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '1445086097250',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ["https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/1.webp",
   "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/2.webp",
   "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/3.webp"],
  'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"},
 {'id': 9,
  'title': 'Dolce Shine Eau de',
  'description': "Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It's a joyful and youthful scent.",
  'category': 'fragrances',
  'price': 69.99,
  'discountPercentage': 0.62,
  'rating': 3.96,
  'stock': 4,
  'tags': ['fragrances', 'perfumes'],
  'brand': 'Dolce & Gabbana',
  'sku': 'FRA-DOL-DOL-009',
  'weight': 6,
  'dimensions': {'width': 27.28, 'height': 29.88, 'depth': 18.3},
  'warrantyInformation': '3 year warranty',
  'shippingInformation': 'Ships in 1 month',
  'availabilityStatus': 'Low Stock',
  'reviews': [{'rating': 4,
    'comment': 'Would buy again!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Mateo Bennett',
    'reviewerEmail': 'mateo.bennett@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Highly recommended!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Nolan Gonzalez',
    'reviewerEmail': 'nolan.gonzalez@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Very happy with my purchase!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Aurora Lawson',
    'reviewerEmail': 'aurora.lawson@x.dummyjson.com'}],
  'returnPolicy': '7 days return policy',
  'minimumOrderQuantity': 2,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '3023868210708',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/1.webp',
   'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/2.webp',
   'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/3.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp'},
 {'id': 10,
  'title': 'Gucci Bloom Eau de',
  'description': "Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It's a modern and romantic scent.",
  'category': 'fragrances',
  'price': 79.99,
  'discountPercentage': 14.39,
  'rating': 2.74,
  'stock': 91,
  'tags': ['fragrances', 'perfumes'],
  'brand': 'Gucci',
  'sku': 'FRA-GUC-GUC-010',
  'weight': 7,
  'dimensions': {'width': 20.92, 'height': 21.68, 'depth': 11.2},
  'warrantyInformation': '6 months warranty',
  'shippingInformation': 'Ships overnight',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 1,
    'comment': 'Very dissatisfied!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Cameron Perez',
    'reviewerEmail': 'cameron.perez@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Very happy with my purchase!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Daniel Cook',
    'reviewerEmail': 'daniel.cook@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Highly impressed!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Addison Wright',
    'reviewerEmail': 'addison.wright@x.dummyjson.com'}],
  'returnPolicy': 'No return policy',
  'minimumOrderQuantity': 2,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '3170832177880',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/1.webp',
   'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/2.webp',
   'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/3.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/thumbnail.webp'},
 {'id': 11,
  'title': 'Annibale Colombo Bed',
  'description': 'The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.',
  'category': 'furniture',
  'price': 1899.99,
  'discountPercentage': 8.57,
  'rating': 4.77,
  'stock': 88,
  'tags': ['furniture', 'beds'],
  'brand': 'Annibale Colombo',
  'sku': 'FUR-ANN-ANN-011',
  'weight': 10,
  'dimensions': {'width': 28.16, 'height': 25.36, 'depth': 17.28},
  'warrantyInformation': '1 year warranty',
  'shippingInformation': 'Ships in 1 month',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 2,
    'comment': 'Would not recommend!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Christopher West',
    'reviewerEmail': 'christopher.west@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Highly impressed!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Vivian Carter',
    'reviewerEmail': 'vivian.carter@x.dummyjson.com'},
   {'rating': 1,
    'comment': 'Poor quality!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Mason Wright',
    'reviewerEmail': 'mason.wright@x.dummyjson.com'}],
  'returnPolicy': 'No return policy',
  'minimumOrderQuantity': 1,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '3610757456581',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/1.webp',
   'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/2.webp',
   'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/3.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp'},
 {'id': 12,
  'title': 'Annibale Colombo Sofa',
  'description': 'The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.',
  'category': 'furniture',
  'price': 2499.99,
  'discountPercentage': 14.4,
  'rating': 3.92,
  'stock': 60,
  'tags': ['furniture', 'sofas'],
  'brand': 'Annibale Colombo',
  'sku': 'FUR-ANN-ANN-012',
  'weight': 6,
  'dimensions': {'width': 12.75, 'height': 20.55, 'depth': 19.06},
  'warrantyInformation': 'Lifetime warranty',
  'shippingInformation': 'Ships in 1 week',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 3,
    'comment': 'Very unhappy with my purchase!',
    'date': '2025-04-30T09:41:02.053Z',

In [ ]:
products = res.json()['products']

for i in products[:5]:
    print(i['reviews'])
    print(i['title'])
    print('-'*30)

[{'rating': 3, 'comment': 'Would not recommend!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Eleanor Collins', 'reviewerEmail': 'eleanor.collins@x.dummyjson.com'}, {'rating': 4, 'comment': 'Very satisfied!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Lucas Gordon', 'reviewerEmail': 'lucas.gordon@x.dummyjson.com'}, {'rating': 5, 'comment': 'Highly impressed!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Eleanor Collins', 'reviewerEmail': 'eleanor.collins@x.dummyjson.com'}]
Essence Mascara Lash Princess
------------------------------
[{'rating': 5, 'comment': 'Great product!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Savannah Gomez', 'reviewerEmail': 'savannah.gomez@x.dummyjson.com'}, {'rating': 4, 'comment': 'Awesome product!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Christian Perez', 'reviewerEmail': 'christian.perez@x.dummyjson.com'}, {'rating': 1, 'comment': 'Poor quality!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Nicholas Bailey', 'reviewerEmail': 'nicholas.bailey@x.dummyjson.com'}]
Eyeshadow Palette with Mirror
------------------------------
[{'rating': 4, 'comment': 'Would buy again!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Alexander Jones', 'reviewerEmail': 'alexander.jones@x.dummyjson.com'}, {'rating': 5, 'comment': 'Highly impressed!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Elijah Cruz', 'reviewerEmail': 'elijah.cruz@x.dummyjson.com'}, {'rating': 1, 'comment': 'Very dissatisfied!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Avery Perez', 'reviewerEmail': 'avery.perez@x.dummyjson.com'}]
Powder Canister
------------------------------
[{'rating': 4, 'comment': 'Great product!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Liam Garcia', 'reviewerEmail': 'liam.garcia@x.dummyjson.com'}, {'rating': 5, 'comment': 'Great product!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Ruby Andrews', 'reviewerEmail': 'ruby.andrews@x.dummyjson.com'}, {'rating': 5, 'comment': 'Would buy again!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Clara Berry', 'reviewerEmail': 'clara.berry@x.dummyjson.com'}]
Red Lipstick
------------------------------
[{'rating': 2, 'comment': 'Poor quality!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Benjamin Wilson', 'reviewerEmail': 'benjamin.wilson@x.dummyjson.com'}, {'rating': 5, 'comment': 'Great product!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Liam Smith', 'reviewerEmail': 'liam.smith@x.dummyjson.com'}, {'rating': 1, 'comment': 'Very unhappy with my purchase!', 'date': '2025-04-30T09:41:02.053Z', 'reviewerName': 'Clara Berry', 'reviewerEmail': 'clara.berry@x.dummyjson.com'}]
Red Nail Polish
------------------------------

In [ ]:
print(f"this is the value of a variable {a}")

this is the value of a variable 5

In [ ]:
print("this is the value of variable", a)

this is the value of variable 5

In [ ]:
request = 'https://old.openweathermap.org/'
response = requests.get(request)

In [ ]:
response

In [ ]:
response.text

'<!DOCTYPE html>\n<html lang="en">\n\n<head>\n  <title> Current weather and forecast - OpenWeatherMap</title>\n  <meta name="apple-itunes-app" content="app-id=1535923697">\n  <!-- Google tag (gtag.js) -->\n<script async src="https://www.googletagmanager.com/gtag/js?id=G-JZLBC3RVK2"></script>\n<script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag() { dataLayer.push(arguments); }\n  gtag(\'js\', new Date());\n\n  gtag(\'config\', \'G-JZLBC3RVK2\');\n</script>\n    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">\n<meta name="viewport" content="width=device-width, initial-scale=1.0">\n<meta name="keywords" content="weather, world, Openstreetmap, forecast, Openweather, current">\n<meta name="description" content="OpenWeather provides comprehensive weather data services, including current, forecast, and historical\nweather information. Explore a wide range of APIs for solar radiation, road risk assessment, solar energy prediction,\nand more, with global coverage and user-friendly access. Ideal for developers and businesses seeking accurate and\nreliable weather insights.">\n<meta name="author" content="OpenWeatherMap.org">\n<meta name="domain" content="OpenWeatherMap.org">\n<meta name="p:domain_verify" content="34fe229eab8562dca90f4a5962ff80a9">\n<meta property="title" content="Current weather and forecast">  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">  <link rel="shortcut icon" href="/themes/openweathermap/assets/vendor/owm/img/icons/favicon.ico">\n<link rel="icon" href="/themes/openweathermap/assets/vendor/owm/img/icons/logo_16x16.png" sizes="16x16"\n  type="image/png">\n<link rel="icon" href="/themes/openweathermap/assets/vendor/owm/img/icons/logo_32x32.png" sizes="32x32"\n  type="image/png">\n<link rel="icon" href="/themes/openweathermap/assets/vendor/owm/img/icons/logo_60x60.png" sizes="60x60"\n  type="image/png">  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">\n\n<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oswald:400,700,300">\n<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700,500,400italic,500italic">  <link rel="stylesheet" href="https://openweathermap.org/plugins/offline/gdpr/assets/cookieBanner/banner.css">\n  <link href="/combine/f715fd89ab078cb9d62b06cf2ebe66e0-1770630134" rel="stylesheet">\n<!-- <link href="https://old.openweathermap.org/combine/9e05934b20b1168fe3f391e409e227a4-1770630134" rel="stylesheet"> -->\n<!-- <link href="/themes/openweathermap/assets/css/new_design.css" rel="stylesheet"> -->  <script src="/combine/d8fb6d080cb70d894318fcae14526239-1770630134"></script>\n<!-- <script src="https://old.openweathermap.org/combine/9dc69b9a99b742c8cd4a003c67dfede2-1770630134"></script> -->  </head>\n\n<body class="body-orange" onClick="closePopUps()">\n  <link href="/themes/openweathermap/assets/css/smart_banner_android.css" rel="stylesheet">\n\n<div id="banner_android" class="banner_stripe">\n    <div class="banner_container">\n        <a class="smartbanner__exit" onClick="bannerClose()"></a>\n        <img src="/themes/openweathermap/assets/img/mobile_app/android-app-top-banner.png" class="banner_icon"\n            alt="banner android">\n        <div>\n            <p class="smartbanner-text">OpenWeather</p>\n            <p class="smartbanner-text">OpenWeather Ltd.</p>\n            <p class="smartbanner-text">GET - on Google Play</p>\n        </div>\n    </div>\n    <a class="google_button" href="https://play.google.com/store/apps/details?id=uk.co.openweather">VIEW</a>\n</div>\n\n<script src="/themes/openweathermap/assets/js/smart_banner_android.js"></script>  <nav id="nav-website" onClick="toggleMenu(event)">\n  <ul id="first-level-nav">\n    <li class="logo">\n      <a href="/">\n        <img src="/themes/openweathermap/assets/img/logo_white_cropped.png" alt="logo">\n      </a>\n    </li>\n    <li id="hamburger">\n      <img src="/themes/openweathermap/assets/img/owm_icons/icon_hamburger.svg" alt="icon hamburger">\n    </li>\n    <li id="desktop-menu">\n      <form role="search" action="/find" method="get">\n        <input type="text" name="q" placeholder="Weather in your city">\n        <input type="submit" class="submit">\n      </form>\n      <ul>\n        <li>\n          <a href="/guide">Guide</a>\n        </li>\n        <li>\n          <a href="/api">API</a>\n        </li>\n        <!-- <li>\n          <a href="https://dashboard.openweather.co.uk/" target="_blank">Dashboard</a>\n        </li> -->\n        <li class="with-dropdown">\n          <div id="dashboards-dropdown">Dashboards</div>\n          <ul class="dropdown-menu" id="dashboards-dropdown-menu" style="width: 230px !important; left: 20% !important;">\n            <li><a href="https://dashboard.openweather.co.uk/">Weather Dashboard</a></li>\n            <li><a href="https://openweather.co.uk/products/energy-dashboard">Energy Dashboard</a></li>\n            <li><a href="https://openweather.co.uk/products/extreme-weather-dashboard">Extreme Weather Dashboard</a></li>\n          </ul>\n        </li>\n\n        <li>\n          <a href="https://home.openweathermap.org/marketplace" target="_blank">Marketplace</a>\n        </li>\n        <li>\n          <a href="/price">Pricing</a>\n        </li>\n        <li>\n          <a href="/weathermap">Maps</a>\n        </li>\n        <li>\n          <a href="/our-initiatives">Our Initiatives</a>\n        </li>\n        <!-- <li>\n          <a href="/examples">Partners</a>\n        </li> -->\n        <li>\n          <a href="https://openweather.co.uk/blog" target="_blank">Blog</a>\n        </li>\n        <li>\n          <a href="https://openweather.co.uk" class="marketplace" target="_blank">For Business</a>\n        </li>\n                <li class="user-li"><a href="https://openweathermap.org/home/sign_in">Sign in</a></li>\n                <li><a href="/support-centre">Support centre</a></li>\n    </li>\n  </ul>\n  </li>\n  </ul>\n  <ul id="mobile-menu">\n    <li>\n      <form role="search" action="/find" method="get">\n        <input type="text" name="q" placeholder="Weather in your city">\n        <input type="submit" class="submit">\n      </form>\n    </li>\n    <li>\n      <a href="/guide">Guide</a>\n    </li>\n    <li>\n      <a href="/api">API</a>\n    </li>\n    <li>\n      <a href="https://dashboard.openweather.co.uk/" target="_blank">Dashboard</a>\n    </li>\n    <li>\n      <a href="https://home.openweathermap.org/marketplace" target="_blank">Marketplace</a>\n    </li>\n    <li>\n      <a href="/price">Pricing</a>\n    </li>\n    <li>\n      <a href="/weathermap">Maps</a>\n    </li>\n    <li>\n      <a href="/our-initiatives">Our Initiatives</a>\n    </li>\n    <li>\n      <a href="/examples">Partners</a>\n    </li>\n    <li>\n      <a href="https://openweather.co.uk/blog" target="_blank">Blog</a>\n    </li>\n    <li>\n      <a href="https://openweather.co.uk" class="marketplace" target="_blank">For Business</a>\n    </li>\n    <li><a href="/support-centre">Support centre</a></li>\n        <li><a href="https://openweathermap.org/home/sign_in">Sign in</a></li>\n      </ul>\n</nav>\n<div class="nav-styles"></div>  <main class="wrapper">\n        <div class="section where-to">\n   <div class="section-content grid-container grid-1-1">\n      <div class="mobile-padding main-page banner-content main-website ">\n         <h1><span class="orange-text">OpenWeather</span></h1>\n         <h2><span>Weather forecasts, nowcasts and history in a fast and elegant way</span>\n         </h2>\n      </div>\n      <a href="https://discord.com/invite/YyPZCXb4Jq" target="_blank" class="discord-link">\n         <img src="/themes/openweathermap/assets/img/discord.svg" alt="Discord" />\n         <p>Join our community</p>\n      </a>\n   </div>\n</div>\n\n<!-- <a href="https://challenge.openweather.co.uk/" target="_blank"><div class="section where-to"></div></a> -->\n\n<div id="weather-widget"></div>\n\n<div class="section grey-background logos-background">\n   <div class="section-content mobile-padding logos-scroll">\n      <div class="logos">\n         <img src="/themes/openweathermap/assets/img/owm-clients-logos-2.png" alt="ow clients logos">\n      </div>\n      <div class="logos logos2">\n         <img src="/themes/openweathermap/assets/img/owm-clients-logos-2.png" alt="ow clients logos">\n      </div>\n   </div>\n</div>\n\n<div class="section">\n   <div class="section-content grid-container grid-1-1 mobile-padding">\n      <div>\n         <span class="orange-text">APIs</span>\n         <h2 class="main-page-subheaders"><a href="/api/one-call-3">One Call API 3.0</a></h2>\n         <p>Choose the subscription plan <a href="/price"><b>"One Call by Call"</b></a> and get access to the various\n            data for any coordinates<b><a href="/api/one-call-3"> with One Call API 3.0</a>.</b><br>\n            1,000 API calls per day for free! <a href="/price"><span class="orange-text">Pay as you call</span></a>.\n         </p>\n         <table class="table-one-call">\n            <tr>\n               <th>Included data</th>\n               <th>Time</th>\n            </tr>\n            <tr>\n               <td><b>Current</b> weather</td>\n               <td>Now</td>\n            </tr>\n            <tr>\n               <td><b>Minute</b> forecast</td>\n               <td>Next hour</td>\n            </tr>\n            <tr>\n               <td><b>Hourly</b> forecast</td>\n               <td>Next 48 hours</td>\n            </tr>\n            <tr>\n               <td><b>Daily</b> forecast</td>\n               <td>Next 8 days</td>\n            </tr>\n            <tr>\n               <td><b>Weather data</b> by any timestamp</td>\n               <td>47+ years back - 4 days ahead forecast</td>\n            </tr>\n            <tr>\n               <td>National weather alerts</td>\n               <td>All available data</td>\n            </tr>\n            <tr>\n               <td><b>Daily aggregation</b></td>\n               <td>47+ years back - 1,5 years ahead forecast</td>\n            </tr>\n            <tr>\n               <td><b>Weather overview</b></td>\n               <td>Human-readable weather summary</td>\n            </tr>\n            <tr>\n               <td><b>AI Weather Assistant</b></td>\n               <td>Weather and weather-related advice in a human-readable format</td>\n            </tr>\n         </table>\n      </div>\n      <div class="desktop-only">\n         <img src="/themes/openweathermap/assets/img/landing/one_call_api.png" class="feature-img" alt="one-call api">\n      </div>\n   </div>\n</div>\n\n\n<div class="section orange-background white-text">\n   <div class="section-content grid-container mobile-padding">\n      <div>\n         <p class="main-page-slogan">Use our <span style="color:#48484a;"><a href="/api#pro">Professional\n                  collections</a></span> to get extended weather data for any\n            coordinates on the globe</p><br>\n         <span>For professionals and specialists with middle and large sized projects, we recommend our Professional\n            collections. They include either an extended data set, or various tools for receiving and displaying data and more.</span>\n      </div>\n      <div class="grid-container api-icons">\n         <a href="/current" class="stats white-text">\n            <div>\n               <img src="/themes/openweathermap/assets/img/landing/icon-1.png" alt="icon">\n            </div>\n            <h3>current<br>weather</h3>\n            <span>(current)</span>\n         </a>\n         <a href="/api/hourly-forecast" class="stats white-text">\n            <div>\n               <img src="/themes/openweathermap/assets/img/landing/icon-2.png" alt="icon">\n            </div>\n            <h3>hourly<br>forecast</h3>\n            <span>(4 days)</span>\n         </a>\n         <a href="/forecast16" class="stats white-text">\n            <div>\n               <img src="/themes/openweathermap/assets/img/landing/icon-3.png" alt="icon">\n            </div>\n            <h3>daily<br>forecast</h3>\n            <span>(16 days)</span>\n         </a>\n         <a href="/api/forecast30" class="stats white-text">\n            <div>\n               <img src="/themes/openweathermap/assets/img/landing/icon-4.png" alt="icon">\n            </div>\n            <h3>climatic<br>forecast</h3>\n            <span>(30 days)</span>\n         </a>\n         <a href="/history" class="stats white-text">\n            <div>\n               <img src="/themes/openweathermap/assets/img/landing/icon-5.png" alt="icon">\n            </div>\n            <h3>historical<br>weather</h3>\n            <span>(47+ years back)</span>\n         </a>\n      </div>\n      <div>\n         <p><b>Called by:</b><br>\n            geographic coordinates, zip/post code, city name, city ID, number of cities (only in current weather and\n            forecast APIs)\n         </p>\n         <a href="/api#pro" class="ow-btn round btn-black">Learn more</a>\n      </div>\n   </div>\n</div>\n\n\n<div class="section">\n   <div class="section-content grid-container grid-1-1 grid-reverse mobile-padding">\n      <div>\n         <span class="orange-text">Weather data</span>\n         <h2 class="main-page-subheaders">Weather for <span class="orange-text">any</span> geographic coordinates on the\n            globe\n         </h2>\n         <img src="/themes/openweathermap/assets/img/landing/historical_data_any_location_new.png" class="feature-img"\n            alt="weather data">\n      </div>\n      <div>\n         <p>For each point on the globe, we provide historical, current and forecasted weather data via light-speed\n            APIs.</p>\n         <p><b><a href="/api/one-call-3">Minute-by-minute forecast</a></b></p>\n         <p><b>Other forecasts:</b><br><a href="/api/hourly-forecast">hourly (4-day)</a>, <a href="/forecast16">daily\n               (16-day)</a>, <a href="/api/forecast30">30-day climatic forecast</a></p>\n         <p><b><a href="/history-bulk">Historical data</a></b><br>with 47+ years archive for any\n            coordinates</p>\n      </div>\n\n   </div>\n</div>\n<div class="section grey-background">\n   <div class="section-content grid-container grid-1-1 mobile-padding">\n      <div>\n         <span class="orange-text">Weather data</span>\n         <h2 class="main-page-subheaders">Forecasted weather data</h2>\n         <img src="/themes/openweathermap/assets/img/landing/forecasted_weather_data.png" class="feature-img"\n            alt="weather data">\n      </div>\n      <div>\n         <p>Detailed forecasts available by city name, city ID, geographic coordinates or postal/ZIP code. </p>\n         <div class="text-block orange-side">\n            <h3>How to obtain</h3>\n            <p><a href="/api">API</a><br>\n               <a href="/bulk">Bulks</a>\n            </p>\n            <p>A variety of subscriptions with various limits on calls/min, data availability, and service</p>\n         </div>\n      </div>\n   </div>\n</div>\n<div class="section">\n   <div class="section-content grid-container grid-1-1 grid-reverse mobile-padding">\n      <div>\n         <span class="orange-text">Weather data</span>\n         <h2 class="main-page-subheaders">Historical weather data</h2>\n         <img class="feature-img" src="/themes/openweathermap/assets/img/landing/historical_data_new.png"\n            alt="weather data">\n      </div>\n      <div>\n         <div>\n            <p>Our technology <b>Time Machine</b>, has allowed us to enhance data in the <a\n                  href="/api#history">Historical Weather Collection</a>: historical weather data is now available for\n               any coordinates and the depth of historical data has been extended to 47+ years.</p>\n            <h3>How to obtain</h3>\n            <p><b><a href="https://home.openweathermap.org/marketplace">Marketplace</a> of prepared data\n                  sets</b><br>(cities, zip codes, grids)</p>\n            <p><b><a href="https://home.openweathermap.org/marketplace">On-the-fly bulks</a></b><br>for customized\n               lists of coordinates</p>\n            <p><b><a href="/api#history">APIs</a></b> (city-based, up to 1 year back; subscriptions with various limits\n               on calls/min, data availability, and service) </p>\n         </div>\n      </div>\n   </div>\n</div>\n\n<div class="section grey-background">\n   <div class="section-content grid-container grid-1-1 mobile-padding">\n      <div>\n         <span class="orange-text">Weather data</span>\n         <h2 class="main-page-subheaders"><a href="/api#current">Current weather data</a></h2>\n         <img src="/themes/openweathermap/assets/img/landing/current.png" class="feature-img" alt="weather data">\n      </div>\n      <div>\n         <p>Access current weather data for any location on Earth including over 200,000 cities! The data is frequently\n            updated based on the global and local weather models, satellites, radars and a vast network of weather\n            stations.</p>\n         <div class="text-block orange-side">\n            <h3>how to obtain</h3>\n            <p><b><a href="/current">APIs</a></b><br>\n               (subscriptions with various limits on calls/min, data availability, and service)\n            </p>\n            <p><b><a href="/bulk">Prepared bulks</a></b><br>\n               (cities, zip codes)\n            </p>\n         </div>\n      </div>\n   </div>\n</div>\n\n\n<div class="section">\n   <div class="section-content no-mobile-padding text-center">\n      <h2>Our <span class="orange-text">new</span> products</h2>\n      <div class="grid-container grid-3 product-boxes">\n         <div class="grey-background">\n            <img src="/themes/openweathermap/assets/img/energy-dashboard.jpg" alt="icon">\n            <p class="orange-text"><a href="https://openweather.co.uk/products/energy-dashboard">Energy Dashboard</a>\n            </p>\n            <p>\n               A comprehensive visual tool for the renewable energy sector. Access crucial historical, current, and \n               forecast solar data, including power generation output and irradiance metrics (GHI, DNI, DHI), to optimize \n               grid management and energy trading decisions.\n            </p>\n            <a href="https://openweather.co.uk/products/energy-dashboard" target="_blank" class="ow-btn round btn-black">\n               Learn more\n            </a>\n         </div>\n         <div class="grey-background">\n            <img src="/themes/openweathermap/assets/img/extreme-weather-dashboard.jpg" alt="icon">\n            <p class="orange-text"><a href="https://openweather.co.uk/products/extreme-weather-dashboard">Extreme Weather Dashboard</a></p>\n            <p>\n               Stay ahead of high-impact weather events. This dashboard provides timely alerts, forecasts, and historical \n               data for extreme phenomena like storms and heatwaves, enabling proactive risk assessment and operational \n               planning for any location on the globe.\n            </p>\n            <a href="https://openweather.co.uk/products/extreme-weather-dashboard" target="_blank" class="ow-btn round btn-black">\n               Learn more\n            </a>\n         </div>\n         <div class="grey-background">\n            <img src="themes/openweathermap/assets/img/globe-with-weather-symbols.webp" alt="icon">\n            <p class="orange-text"><a href="https://dashboard.openweather.co.uk/">Weather Dashboard</a>\n            </p>\n            <p>\n               Your go-to source for global weather insights. Instantly visualize current conditio

In [ ]:
json.loads(response.text)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame(res.json())

                                             products  total  skip  limit
0   {'id': 1, 'title': 'Essence Mascara Lash Princ...    194     0     30
1   {'id': 2, 'title': 'Eyeshadow Palette with Mir...    194     0     30
2   {'id': 3, 'title': 'Powder Canister', 'descrip...    194     0     30
3   {'id': 4, 'title': 'Red Lipstick', 'descriptio...    194     0     30
4   {'id': 5, 'title': 'Red Nail Polish', 'descrip...    194     0     30
5   {'id': 6, 'title': 'Calvin Klein CK One', 'des...    194     0     30
6   {'id': 7, 'title': 'Chanel Coco Noir Eau De', ...    194     0     30
7   {'id': 8, 'title': 'Dior J'adore', 'descriptio...    194     0     30
8   {'id': 9, 'title': 'Dolce Shine Eau de', 'desc...    194     0     30
9   {'id': 10, 'title': 'Gucci Bloom Eau de', 'des...    194     0     30
10  {'id': 11, 'title': 'Annibale Colombo Bed', 'd...    194     0     30
11  {'id': 12, 'title': 'Annibale Colombo Sofa', '...    194     0     30
12  {'id': 13, 'title': 'Bedside Table African Che...    194     0     30
13  {'id': 14, 'title': 'Knoll Saarinen Executive ...    194     0     30
14  {'id': 15, 'title': 'Wooden Bathroom Sink With...    194     0     30
15  {'id': 16, 'title': 'Apple', 'description': 'F...    194     0     30
16  {'id': 17, 'title': 'Beef Steak', 'description...    194     0     30
17  {'id': 18, 'title': 'Cat Food', 'description':...    194     0     30
18  {'id': 19, 'title': 'Chicken Meat', 'descripti...    194     0     30
19  {'id': 20, 'title': 'Cooking Oil', 'descriptio...    194     0     30
20  {'id': 21, 'title': 'Cucumber', 'description':...    194     0     30
21  {'id': 22, 'title': 'Dog Food', 'description':...    194     0     30
22  {'id': 23, 'title': 'Eggs', 'description': 'Fr...    194     0     30
23  {'id': 24, 'title': 'Fish Steak', 'description...    194     0     30
24  {'id': 25, 'title': 'Green Bell Pepper', 'desc...    194     0     30
25  {'id': 26, 'title': 'Green Chili Pepper', 'des...    194     0     30
26  {'id': 27, 'title': 'Honey Jar', 'description'...    194     0     30
27  {'id': 28, 'title': 'Ice Cream', 'description'...    194     0     30
28  {'id': 29, 'title': 'Juice', 'description': 'R...    194     0     30
29  {'id': 30, 'title': 'Kiwi', 'description': 'Nu...    194     0     30

In [ ]:
products = res.json()['products']
tmp = pd.DataFrame(products)

In [ ]:
tmp

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,dimensions,warrantyInformation,shippingInformation,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,"{'width': 15.14, 'height': 13.08, 'depth': 22.99}",1 week warranty,Ships in 3-5 business days,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",No return policy,48,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,"{'width': 9.26, 'height': 22.47, 'depth': 27.67}",1 year warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,20,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,...,"{'width': 29.27, 'height': 27.93, 'depth': 20.59}",3 months warranty,Ships in 1-2 business days,In Stock,"[{'rating': 4, 'comment': 'Would buy again!', ...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,...,"{'width': 18.11, 'height': 28.38, 'depth': 22.17}",3 year warranty,Ships in 1 week,In Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",7 days return policy,40,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,...,"{'width': 21.63, 'height': 16.48, 'depth': 29.84}",1 month warranty,Ships overnight,In Stock,"[{'rating': 2, 'comment': 'Poor quality!', 'da...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
5,6,Calvin Klein CK One,CK One by Calvin Klein is a classic unisex fra...,fragrances,49.99,1.89,4.37,29,"[fragrances, perfumes]",Calvin Klein,...,"{'width': 29.36, 'height': 27.76, 'depth': 20.72}",1 week warranty,Ships overnight,In Stock,"[{'rating': 2, 'comment': 'Very disappointed!'...",90 days return policy,9,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...
6,7,Chanel Coco Noir Eau De,Coco Noir by Chanel is an elegant and mysterio...,fragrances,129.99,16.51,4.26,58,"[fragrances, perfumes]",Chanel,...,"{'width': 24.5, 'height': 25.7, 'depth': 25.98}",3 year warranty,Ships overnight,In Stock,"[{'rating': 4, 'comment': 'Highly impressed!',...",No return policy,1,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...
7,8,Dior J'adore,J'adore by Dior is a luxurious and floral frag...,fragrances,89.99,14.72,3.80,98,"[fragrances, perfumes]",Dior,...,"{'width': 27.67, 'height': 28.28, 'depth': 11.83}",1 week warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Great value for mon...",7 days return policy,10,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...
8,9,Dolce Shine Eau de,Dolce Shine by Dolce & Gabbana is a vibrant an...,fragrances,69.99,0.62,3.96,4,"[fragrances, perfumes]",Dolce & Gabbana,...,"{'width': 27.28, 'height': 29.88, 'depth': 18.3}",3 year warranty,Ships in 1 month,Low Stock,"[{'rating': 4, 'comment': 'Would buy again!', ...",7 days return policy,2,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...
9,10,Gucci Bloom Eau de,Gucci Bloom by Gucci is a floral and captivati...,fragrances,79.99,14.39,2.74,91,"[fragrances, perfumes]",Gucci,...,"{'width': 20.92, 'height': 21.68, 'depth': 11.2}",6 months warranty,Ships overnight,In Stock,"[{'rating': 1, 'comment': 'Very dissatisfied!'...",No return policy,2,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/frag...,https://cdn.dummyjson.com/product-images/fragr...
10,11,Annibale Colombo Bed,The Annibale Colombo Bed is a luxurious and el...,furniture,1899.99,8.57,4.77,88,"[furniture, beds]",Annibale Colombo,...,"{'width': 28.16, 'height': 25.36, 'depth': 17.28}",1 year warranty,Ships in 1 month,In Stock,"[{'rating': 2, 'comment': 'Would not recommend...",No return policy,1,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...
11,12,Annibale Colombo Sofa,The Annibale Colombo Sofa is a sophisticated a...,furniture,2499.99,14.40,3.92,60,"[furniture, sofas]",Annibale Colombo,...,"{'width': 12.75, 'height': 20.55, 'depth': 19.06}",Lifetime warranty,Ships in 1 week,In Stock,"[{'rating': 3, 'comment': 'Very unhappy with m...",7 days return policy,1,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...
12,13,Bedside Table African Cherry,The Bedside Table in African Cherry is a styli...,furniture,299.99,19.09,2.87,64,"[furniture, bedside tables]",Furniture Co.,...,"{'width': 13.47, 'height': 24.99, 'depth': 27.35}",5 year warranty,Ships overnight,In Stock,"[{'rating': 4, 'comment': 'Excellent quality!'...",7 days return policy,3,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...
13,14,Knoll Saarinen Executive Conference Chair,The Knoll Saarinen Executive Conference Chair ...,furniture,499.99,2.01,4.88,26,"[furniture, office chairs]",Knoll,...,"{'width': 13.81, 'height': 7.5, 'depth': 5.62}",2 year warranty,Ships overnight,In Stock,"[{'rating': 2, 'comment': 'Waste of money!', '...",60 days return policy,5,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...
14,15,Wooden Bathroom Sink With Mirror,The Wooden Bathroom Sink with Mirror is a uniq...,furniture,799.99,8.80,3.59,7,"[furniture, bathroom]",Bath Trends,...,"{'width': 7.98, 'height': 8.88, 'depth': 28.46}",3 year warranty,Ships in 3-5 business days,Low Stock,"[{'rating': 4, 'comment': 'Fast shipping!', 'd...",60 days return policy,2,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/furn...,https://cdn.dummyjson.com/product-images/furni...
15,16,Apple,"Fresh and crisp apples, perfect for snacking o...",groceries,1.99,12.62,4.19,8,[fruits],NaN,...,"{'width': 13.66, 'height': 11.01, 'depth': 9.73}",3 year warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Very satisfied!', '...",90 days return policy,7,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
16,17,Beef Steak,"High-quality beef steak, great for grilling or...",groceries,12.99,9.61,4.47,86,[meat],NaN,...,"{'width': 18.9, 'height': 5.77, 'depth': 18.57}",3 year warranty,Ships overnight,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",60 days return policy,43,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
17,18,Cat Food,Nutritious cat food formulated to meet the die...,groceries,8.99,9.58,3.13,46,"[pet supplies, cat food]",NaN,...,"{'width': 18.08, 'height': 9.26, 'depth': 21.86}",1 year warranty,Ships overnight,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",No return policy,18,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
18,19,Chicken Meat,"Fresh and tender chicken meat, suitable for va...",groceries,9.99,13.70,3.19,97,[meat],NaN,...,"{'width': 11.03, 'height': 22.11, 'depth': 16.01}",1 year warranty,Ships in 1 month,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
19,20,Cooking Oil,"Versatile cooking oil suitable for frying, sau...",groceries,4.99,9.33,4.80,10,[cooking essentials],NaN,...,"{'width': 19.95, 'height': 27.54, 'depth': 24.86}",Lifetime warranty,Ships in 1-2 business days,In Stock,"[{'rating': 5, 'comment': 'Very happy with my ...",30 days return policy,46,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
20,21,Cucumber,"Crisp and hydrating cucumbers, ideal for salad...",groceries,1.49,0.16,4.07,84,[vegetables],NaN,...,"{'width': 12.8, 'height': 28.38, 'depth': 21.34}",2 year warranty,Ships in 1-2 business days,In Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",7 days return policy,2,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
21,22,Dog Food,Specially formulated dog food designed to prov...,groceries,10.99,10.27,4.55,71,"[pet supplies, dog food]",NaN,...,"{'width': 16.93, 'height': 27.15, 'depth': 9.29}",No warranty,Ships in 1-2 business days,In Stock,"[{'rating': 5, 'comment': 'Excellent quality!'...",60 days return policy,43,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
22,23,Eggs,"Fresh eggs, a versatile ingredient for baking,...",groceries,2.99,11.05,2.53,9,[dairy],NaN,...,"{'width': 11.42, 'height': 7.44, 'depth': 16.95}",1 week warranty,Ships in 1 week,In Stock,"[{'rating': 3, 'comment': 'Disappointing produ...",No return policy,32,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
23,24,Fish Steak,"Quality fish steak, suitable for grilling, bak...",groceries,14.99,4.23,3.78,74,[seafood],NaN,...,"{'width': 14.95, 'height': 26.31, 'depth': 11.27}",1 month warranty,Ships in 3-5 business days,In Stock,"[{'rating': 2, 'comment': 'Would not buy again...",60 days return policy,50,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
24,25,Green Bell Pepper,"Fresh and vibrant green bell pepper, perfect f...",groceries,1.29,0.16,3.25,33,[vegetables],NaN,...,"{'width': 15.33, 'height': 26.65, 'depth': 14.44}",1 month warranty,Ships in 1 week,In Stock,"[{'rating': 4, 'comment': 'Highly recommended!...",30 days return policy,12,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
25,26,Green Chili Pepper,"Spicy green chili pepper, ideal for adding hea...",groceries,0.99,1.00,3.66,3,[vegetables],NaN,...,"{'width': 15.38, 'height': 18.12, 'depth': 19.92}",2 year warranty,Ships in 1 week,Low Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",30 days return policy,39,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
26,27,Honey Jar,"Pure and natural honey in a convenient jar, pe...",groceries,6.99,14.40,3.97,34,[condiments],NaN,...,"{'width': 9.28, 'height': 21.72, 'depth': 17.74}",1 month warranty,Ships in 1-2 business days,In Stock,"[{'rating': 1, 'comment': 'Very disappointed!'...",90 days return policy,47,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
27,28,Ice Cream,"Creamy and delicious ice cream, available in v...",groceries,5.49,8.69,3.39,27,[desserts],NaN,...,"{'width': 14.83, 'height': 15.07, 'depth': 24.2}",1 month warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Very pleased!', 'da...",No return policy,42,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
28,29,Juice,"Refreshing fruit juice, packed with vitamins a...",groceries,3.99,12.06,3.94,50,[beverages],NaN,...,"{'width': 18.56, 'height': 21.46, 'depth': 28.02}",6 months warranty,Ships in 1 week,In Stock,"[{'rating': 5, 'comment': 'Excellent quality!'...",No return policy,25,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
29,30,Kiwi,"Nutrient-rich kiwi, perfect for snacking or ad...",groceries,2.49,15.22,4.93,99,[fruits],NaN,...,"{'width': 19.4, 'height': 18.67, 'depth': 17.13}",6 months warranty,Ships overnight,In Stock,"[{'rating': 4, 'comment': 'Highly recommended!...",7 days return policy,30,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...

In [ ]:
tmp.shape

(30, 22)

In [ ]:
tmp.describe()

,id,price,discountPercentage,rating,stock,weight,minimumOrderQuantity
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,15.500000,219.250000,9.839667,3.858333,54.933333,5.800000,21.533333
std,8.803408,570.491833,5.456157,0.714660,33.816883,3.231312,17.571005
min,1.000000,0.990000,0.160000,2.530000,3.000000,1.000000,1.000000
25%,8.250000,5.115000,8.600000,3.285000,27.500000,2.500000,3.500000
50%,15.500000,11.990000,10.375000,3.950000,59.000000,6.000000,21.000000
75%,22.750000,77.490000,14.217500,4.367500,87.500000,8.750000,39.750000
max,30.000000,2499.990000,19.090000,4.930000,99.000000,10.000000,50.000000

In [ ]:
tmp.dtypes

id                        int64
title                    object
description              object
category                 object
price                   float64
discountPercentage      float64
rating                  float64
stock                     int64
tags                     object
brand                    object
sku                      object
weight                    int64
dimensions               object
warrantyInformation      object
shippingInformation      object
availabilityStatus       object
reviews                  object
returnPolicy             object
minimumOrderQuantity      int64
meta                     object
images                   object
thumbnail                object
dtype: object

In [ ]:
#fetch unique values in a column

tmp['price'].unique()

array([9.99000e+00, 1.99900e+01, 1.49900e+01, 1.29900e+01, 8.99000e+00,
       4.99900e+01, 1.29990e+02, 8.99900e+01, 6.99900e+01, 7.99900e+01,
       1.89999e+03, 2.49999e+03, 2.99990e+02, 4.99990e+02, 7.99990e+02,
       1.99000e+00, 4.99000e+00, 1.49000e+00, 1.09900e+01, 2.99000e+00,
       1.29000e+00, 9.90000e-01, 6.99000e+00, 5.49000e+00, 3.99000e+00,
       2.49000e+00])

In [ ]:
tmp['price'].nunique()

26

In [ ]:
len(list(tmp['price'].unique()))

26

In [ ]:
tmp.isnull().sum()

id                       0
title                    0
description              0
category                 0
price                    0
discountPercentage       0
rating                   0
stock                    0
tags                     0
brand                   15
sku                      0
weight                   0
dimensions               0
warrantyInformation      0
shippingInformation      0
availabilityStatus       0
reviews                  0
returnPolicy             0
minimumOrderQuantity     0
meta                     0
images                   0
thumbnail                0
dtype: int64

In [ ]:
#figure missing values in each columns
tmp.isna().sum()
#tmp.isnull().sum()

id                       0
title                    0
description              0
category                 0
price                    0
discountPercentage       0
rating                   0
stock                    0
tags                     0
brand                   15
sku                      0
weight                   0
dimensions               0
warrantyInformation      0
shippingInformation      0
availabilityStatus       0
reviews                  0
returnPolicy             0
minimumOrderQuantity     0
meta                     0
images                   0
thumbnail                0
dtype: int64

In [ ]:
#names of columns or list all column names
tmp.columns

Index(['id', 'title', 'description', 'category', 'price', 'discountPercentage',
       'rating', 'stock', 'tags', 'brand', 'sku', 'weight', 'dimensions',
       'warrantyInformation', 'shippingInformation', 'availabilityStatus',
       'reviews', 'returnPolicy', 'minimumOrderQuantity', 'meta', 'images',
       'thumbnail'],
      dtype='object')

In [ ]:
tmp.head()

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,dimensions,warrantyInformation,shippingInformation,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,"{'width': 15.14, 'height': 13.08, 'depth': 22.99}",1 week warranty,Ships in 3-5 business days,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",No return policy,48,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,"{'width': 9.26, 'height': 22.47, 'depth': 27.67}",1 year warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,20,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,...,"{'width': 29.27, 'height': 27.93, 'depth': 20.59}",3 months warranty,Ships in 1-2 business days,In Stock,"[{'rating': 4, 'comment': 'Would buy again!', ...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,...,"{'width': 18.11, 'height': 28.38, 'depth': 22.17}",3 year warranty,Ships in 1 week,In Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",7 days return policy,40,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,...,"{'width': 21.63, 'height': 16.48, 'depth': 29.84}",1 month warranty,Ships overnight,In Stock,"[{'rating': 2, 'comment': 'Poor quality!', 'da...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...

In [ ]:
tmp.tail()

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,dimensions,warrantyInformation,shippingInformation,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail
25,26,Green Chili Pepper,"Spicy green chili pepper, ideal for adding hea...",groceries,0.99,1.00,3.66,3,[vegetables],NaN,...,"{'width': 15.38, 'height': 18.12, 'depth': 19.92}",2 year warranty,Ships in 1 week,Low Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",30 days return policy,39,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
26,27,Honey Jar,"Pure and natural honey in a convenient jar, pe...",groceries,6.99,14.40,3.97,34,[condiments],NaN,...,"{'width': 9.28, 'height': 21.72, 'depth': 17.74}",1 month warranty,Ships in 1-2 business days,In Stock,"[{'rating': 1, 'comment': 'Very disappointed!'...",90 days return policy,47,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
27,28,Ice Cream,"Creamy and delicious ice cream, available in v...",groceries,5.49,8.69,3.39,27,[desserts],NaN,...,"{'width': 14.83, 'height': 15.07, 'depth': 24.2}",1 month warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Very pleased!', 'da...",No return policy,42,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
28,29,Juice,"Refreshing fruit juice, packed with vitamins a...",groceries,3.99,12.06,3.94,50,[beverages],NaN,...,"{'width': 18.56, 'height': 21.46, 'depth': 28.02}",6 months warranty,Ships in 1 week,In Stock,"[{'rating': 5, 'comment': 'Excellent quality!'...",No return policy,25,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...
29,30,Kiwi,"Nutrient-rich kiwi, perfect for snacking or ad...",groceries,2.49,15.22,4.93,99,[fruits],NaN,...,"{'width': 19.4, 'height': 18.67, 'depth': 17.13}",6 months warranty,Ships overnight,In Stock,"[{'rating': 4, 'comment': 'Highly recommended!...",7 days return policy,30,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/groc...,https://cdn.dummyjson.com/product-images/groce...

In [ ]:
tmp['sku']

0     BEA-ESS-ESS-001
1     BEA-GLA-EYE-002
2     BEA-VEL-POW-003
3     BEA-CHI-LIP-004
4     BEA-NAI-NAI-005
5     FRA-CAL-CAL-006
6     FRA-CHA-CHA-007
7     FRA-DIO-DIO-008
8     FRA-DOL-DOL-009
9     FRA-GUC-GUC-010
10    FUR-ANN-ANN-011
11    FUR-ANN-ANN-012
12    FUR-FUR-BED-013
13    FUR-KNO-KNO-014
14    FUR-BAT-WOO-015
15    GRO-BRD-APP-016
16    GRO-BRD-BEE-017
17    GRO-BRD-FOO-018
18    GRO-BRD-CHI-019
19    GRO-BRD-COO-020
20    GRO-BRD-CUC-021
21    GRO-BRD-FOO-022
22    GRO-BRD-EGG-023
23    GRO-BRD-FIS-024
24    GRO-BRD-GRE-025
25    GRO-BRD-GRE-026
26    GRO-BRD-HON-027
27    GRO-BRD-CRE-028
28    GRO-BRD-JUI-029
29    GRO-BRD-KIW-030
Name: sku, dtype: object

In [ ]:
import random
random.randint(1,100)

12

In [ ]:
help(random.randint)

Help on method randint in module random:

randint(a, b) method of random.Random instance
    Return random integer in range [a, b], including both end points.

In [ ]:
tmp['units'] = 15

In [ ]:
tmp['Revenue'] = tmp['price']*tmp['units']

In [ ]:
tmp.head()

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,shippingInformation,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail,units,Revenue
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,Ships in 3-5 business days,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",No return policy,48,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,15,149.85
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,20,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,15,299.85
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,...,Ships in 1-2 business days,In Stock,"[{'rating': 4, 'comment': 'Would buy again!', ...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,15,224.85
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,...,Ships in 1 week,In Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",7 days return policy,40,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,15,194.85
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,...,Ships overnight,In Stock,"[{'rating': 2, 'comment': 'Poor quality!', 'da...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,15,134.85

In [ ]:
#sum all values in a column
tmp['Revenue'].sum()

98662.50000000003

In [ ]:
import numpy as np

np.round(tmp['Revenue'].sum(),2)

98662.5

In [ ]:
tmp.columns

Index(['id', 'title', 'description', 'category', 'price', 'discountPercentage',
       'rating', 'stock', 'tags', 'brand', 'sku', 'weight', 'dimensions',
       'warrantyInformation', 'shippingInformation', 'availabilityStatus',
       'reviews', 'returnPolicy', 'minimumOrderQuantity', 'meta', 'images',
       'thumbnail', 'units', 'Revenue'],
      dtype='object')

In [ ]:
type(tmp)

pandas.core.frame.DataFrame

In [ ]:
type(tmp['Revenue'])

pandas.core.series.Series

In [ ]:
cp = tmp.copy()

In [ ]:
cp.head()

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,shippingInformation,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail,units,Revenue
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,Ships in 3-5 business days,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",No return policy,48,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,15,149.85
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,20,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,15,299.85
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,...,Ships in 1-2 business days,In Stock,"[{'rating': 4, 'comment': 'Would buy again!', ...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,15,224.85
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,...,Ships in 1 week,In Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",7 days return policy,40,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,15,194.85
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,...,Ships overnight,In Stock,"[{'rating': 2, 'comment': 'Poor quality!', 'da...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,15,134.85

In [ ]:
cp.columns

Index(['id', 'title', 'description', 'category', 'price', 'discountPercentage',
       'rating', 'stock', 'tags', 'brand', 'sku', 'weight', 'dimensions',
       'warrantyInformation', 'shippingInformation', 'availabilityStatus',
       'reviews', 'returnPolicy', 'minimumOrderQuantity', 'meta', 'images',
       'thumbnail', 'units', 'Revenue'],
      dtype='object')

In [ ]:
cp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    30 non-null     int64
 1   title                 30 non-null     object
 2   description           30 non-null     object
 3   category              30 non-null     object
 4   price                 30 non-null     float64
 5   discountPercentage    30 non-null     float64
 6   rating                30 non-null     float64
 7   stock                 30 non-null     int64
 8   tags                  30 non-null     object
 9   brand                 15 non-null     object
 10  sku                   30 non-null     object
 11  weight                30 non-null     int64
 12  dimensions            30 non-null     object
 13  warrantyInformation   30 non-null     object
 14  shippingInformation   30 non-null     object
 15  availabilityStatus    30 non-null     object
 16  reviews               30 non-null     object
 17  returnPolicy          30 non-null     object
 18  minimumOrderQuantity  30 non-null     int64
 19  meta                  30 non-null     object
 20  images                30 non-null     object
 21  thumbnail             30 non-null     object
 22  units                 30 non-null     int64
 23  Revenue               30 non-null     float64
dtypes: float64(4), int64(5), object(15)
memory usage: 5.8+ KB

In [ ]:
tmp.index

RangeIndex(start=0, stop=30, step=1)

In [ ]:
# tmp = tmp.drop('brand',axis=1)
tmp.drop('brand',axis=1, inplace=True)

In [ ]:
tmp.shape

(30, 23)

In [ ]:
unit_price = []
for i in range(len(tmp)):
    unit_price.append(random.randint(10,50))
unit_price

[23,
 41,
 18,
 33,
 40,
 19,
 44,
 25,
 28,
 13,
 15,
 44,
 16,
 47,
 19,
 49,
 49,
 48,
 50,
 13,
 28,
 31,
 36,
 24,
 31,
 10,
 19,
 14,
 38,
 44]

In [ ]:
cp['unit_price'] = unit_price

In [ ]:
cp.head()

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail,units,Revenue,unit_price
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",No return policy,48,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,15,149.85,23
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,20,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,15,299.85,41
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,...,In Stock,"[{'rating': 4, 'comment': 'Would buy again!', ...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,15,224.85,18
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,...,In Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",7 days return policy,40,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,15,194.85,33
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,...,In Stock,"[{'rating': 2, 'comment': 'Poor quality!', 'da...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,15,134.85,40

In [ ]:
# convert json to dataframe
# display no of rows & columns - using shape
# display statistical summary - using describe
# display dataframe info - using info
# unique values in a column - unique
# counted the number of unique in a column - nunique
# create a copy of dataframe - copy
# display top n rows - head
# display last n rows - tail
# add a column
# drop a column
# transform 2 columns to another column
# sum values in a column
# round the sum or total of a column

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
anime = pd.read_csv('anime_data.csv')

In [ ]:
display first 20 rows
last 20 rows
get column names
display no of rows and columns using print statement (rows =, columns = )

In [ ]:
anime.head(20)

,title,description,mediaType,eps,duration,ongoing,sznOfRelease,years_running,studio_primary,studios_colab,...,tag_Supernatural,tag_Magic,tag_Animal_Protagonists,tag_Ecchi,tag_Mecha,tag_Based_on_a_Light_Novel,tag_CG_Animation,tag_Superpowers,tag_Others,tag_missing
0,Fullmetal Alchemist: Brotherhood,The foundation of alchemy is based on the law ...,TV,64,NaN,False,Spring,1,Bones,0,...,0,0,0,0,0,0,0,0,0,0
1,your name.,Mitsuha and Taki are two total strangers livin...,Movie,1,107.0,False,is_missing,0,Others,0,...,1,0,0,0,0,0,0,0,0,0
2,A Silent Voice,"After transferring into a new school, a deaf g...",Movie,1,130.0,False,is_missing,0,Kyoto Animation,0,...,0,0,0,0,0,0,0,0,0,0
3,Haikyuu!! Karasuno High School vs Shiratorizaw...,"Picking up where the second season ended, the ...",TV,10,NaN,False,Fall,0,Production I.G,0,...,0,0,0,0,0,0,0,0,0,0
4,Attack on Titan 3rd Season: Part II,The battle to retake Wall Maria begins now! Wi...,TV,10,NaN,False,Spring,0,Others,0,...,0,0,0,0,0,0,0,0,0,0
5,Demon Slayer: Kimetsu no Yaiba,"Bloodthirsty demons lurk in the woods, and nob...",TV,26,NaN,False,Spring,0,Others,0,...,0,0,0,0,0,0,0,0,0,0
6,Haikyuu!! Second Season,"After losing to Aoba Johsai at the Inter-High,...",TV,25,NaN,False,Fall,1,Production I.G,0,...,0,0,0,0,0,0,0,0,0,0
7,Hunter x Hunter (2011),"Drawn to the mystique of the unknown, Hunters ...",TV,148,NaN,False,Fall,3,MADHOUSE,0,...,0,0,0,0,0,0,0,1,0,0
8,Gintama Kanketsu-hen: Yorozuya yo Eien Nare,"While watching a movie, Gintoki comes upon a ""...",Movie,1,111.0,False,is_missing,0,Sunrise,0,...,0,0,0,0,0,0,0,0,0,0
9,Gintama (2015),Fourth season of Gintama.,TV,51,NaN,False,Spring,1,Others,0,...,0,0,0,0,0,0,0,0,0,0
10,Mob Psycho 100 II,Second Season of Mob Psycho 100.,TV,13,NaN,False,Winter,0,Bones,0,...,1,0,0,0,0,0,0,1,0,0
11,Steins;Gate,"The eccentric mad scientist Okabe, his childho...",TV,24,NaN,False,Spring,0,Others,0,...,0,0,0,0,0,0,0,0,0,0
12,Code Geass: Lelouch of the Rebellion R2,Area 11 is still under Britannian rule and the...,TV,25,NaN,False,Spring,0,Sunrise,0,...,0,0,0,0,1,0,0,1,0,0
13,Kaguya-sama: Love Is War?,The battle between love and pride continues! N...,TV,10,NaN,True,Spring,0,A-1 Pictures,0,...,0,0,0,0,0,0,0,0,0,0
14,Haikyuu!! To the Top,The Karasuno High School Volleyball Club final...,TV,13,NaN,False,Winter,0,Production I.G,0,...,0,0,0,0,0,0,0,0,0,0
15,The Promised Neverland,"Emma, Norman, Ray, and many other ""siblings"" l...",TV,12,NaN,False,Winter,0,Others,0,...,0,0,0,0,0,0,0,0,0,0
16,My Hero Academia 3,"Summer is here,and the heroes of Class 1-A and...",TV,25,NaN,False,Spring,0,Bones,0,...,0,0,0,0,0,0,0,1,0,0
17,March Comes in like a Lion 2nd Season,Rei continues to work hard at improving his sh...,TV,22,NaN,False,Fall,1,Shaft,0,...,0,0,0,0,0,0,0,0,0,0
18,Mushishi Zoku Shou 2nd Season,Continuation of Mushishi Zoku Shou.,TV,10,NaN,False,Fall,0,Others,0,...,1,0,0,0,0,0,0,0,0,0
19,My Hero Academia 2,In a world where eighty percent of the populat...,TV,25,NaN,False,Spring,0,Bones,0,...,0,0,0,0,0,0,0,1,0,0

In [ ]:
anime.tail(20)

,title,description,mediaType,eps,duration,ongoing,sznOfRelease,years_running,studio_primary,studios_colab,...,tag_Supernatural,tag_Magic,tag_Animal_Protagonists,tag_Ecchi,tag_Mecha,tag_Based_on_a_Light_Novel,tag_CG_Animation,tag_Superpowers,tag_Others,tag_missing
12081,Oshiri Mae Man: Akagi Nyugyo Chocomint CM,NaN,Web,1,1.0,False,is_missing,0,is_missing,0,...,0,0,0,0,0,0,0,0,0,0
12082,Forest Fairy Five,"A beautiful nation, prospering since ancient t...",TV,13,11.0,False,Winter,0,is_missing,0,...,0,0,0,0,0,0,1,0,0,0
12083,Kinako Nishinakajima: Danbou to Reibou,NaN,Music Video,1,2.0,False,is_missing,0,is_missing,0,...,0,0,0,0,0,0,0,0,1,0
12084,Nani no Yaku ni Mo Tatanai Karappona Hanashi,NaN,Web,2,2.0,False,is_missing,0,is_missing,0,...,0,0,0,0,0,0,0,0,0,0
12085,Madonna (Keiichi TANAAMI),NaN,Movie,1,4.0,False,is_missing,0,is_missing,0,...,0,0,0,0,0,0,0,0,0,0
12086,Puzzle of Autumn,NaN,Movie,1,4.0,False,is_missing,0,is_missing,0,...,0,0,0,0,0,0,0,0,0,0
12087,Mars of Destruction,"In the year 2010 the Mars Exploration Vessel, ...",OVA,1,20.0,False,is_missing,0,Others,0,...,0,0,0,0,0,0,0,0,0,0
12088,Kokuhaku,NaN,Web,1,1.0,False,is_missing,0,is_missing,0,...,0,0,0,0,0,0,1,0,0,0
12089,Nami,NaN,Movie,1,3.0,False,is_missing,0,is_missing,0,...,0,0,0,0,0,0,0,0,0,0
12090,Utsu-Musume Sayuri,NaN,Movie,1,3.0,False,is_missing,0,is_missing,0,...,0,0,0,0,0,0,0,0,0,0
12091,Tenkuu Danzai Skelter Heaven,Hovering above the streets of a futuristic Tok...,OVA,1,19.0,False,is_missing,0,Others,0,...,0,0,0,0,1,0,0,0,0,0
12092,ONE OK ROCK: I Was King,NaN,Music Video,1,4.0,False,is_missing,0,is_missing,0,...,0,0,0,0,0,0,0,0,0,1
12093,Knyacki!,NaN,TV,48,5.0,True,Spring,25,is_missing,0,...,0,0,0,0,0,0,0,0,0,0
12094,Da Li Si Ri Zhi,NaN,Web,7,17.0,True,is_missing,0,is_missing,0,...,0,0,1,0,0,0,0,0,0,0
12095,Bonobono: Uchuu kara Kita Tomodachi,The anime will feature an original story where...,Movie,1,22.0,False,is_missing,0,Others,0,...,0,0,1,0,0,0,0,0,0,0
12096,Sore Ike! Anpanman: Kirameke! Ice no Kuni no V...,Princess Vanilla is a princess in a land of ic...,Movie,1,NaN,False,is_missing,0,TMS Entertainment,0,...,0,0,0,0,0,0,0,0,0,0
12097,Hulaing Babies Petit,NaN,TV,12,5.0,False,Winter,0,Others,0,...,0,0,0,0,0,0,0,0,0,0
12098,Marco & The Galaxy Dragon,NaN,OVA,1,NaN,False,is_missing,0,is_missing,0,...,0,0,0,0,0,0,0,0,0,0
12099,Xing Chen Bian 2nd Season,Second season of Xing Chen Bian.,Web,3,24.0,True,is_missing,0,is_missing,0,...,0,0,0,0,0,0,1,0,0,0
12100,Ultra B: Black Hole kara no Dokusaisha BB!!,NaN,Movie,1,20.0,False,is_missing,0,Shin-Ei Animation,0,...,0,0,0,0,0,0,0,1,0,0

In [ ]:
anime.columns

Index(['title', 'description', 'mediaType', 'eps', 'duration', 'ongoing',
       'sznOfRelease', 'years_running', 'studio_primary', 'studios_colab',
       'contentWarn', 'watched', 'watching', 'wantWatch', 'dropped', 'rating',
       'votes', 'tag_Based_on_a_Manga', 'tag_Comedy', 'tag_Action',
       'tag_Fantasy', 'tag_Sci_Fi', 'tag_Shounen', 'tag_Original_Work',
       'tag_Non_Human_Protagonists', 'tag_Drama', 'tag_Adventure',
       'tag_Family_Friendly', 'tag_Short_Episodes', 'tag_School_Life',
       'tag_Romance', 'tag_Shorts', 'tag_Slice_of_Life', 'tag_Seinen',
       'tag_Supernatural', 'tag_Magic', 'tag_Animal_Protagonists', 'tag_Ecchi',
       'tag_Mecha', 'tag_Based_on_a_Light_Novel', 'tag_CG_Animation',
       'tag_Superpowers', 'tag_Others', 'tag_missing'],
      dtype='object')

In [ ]:
print(f'now of rows: {anime.shape[0]} and no of columns: {anime.shape[1]} ' )

now of rows: 12101 and no of columns: 44

In [ ]:
# duplicates?
anime.duplicated().sum()

0

In [ ]:
# find missing values
anime.isnull().sum()

title                            0
description                   4468
mediaType                        0
eps                              0
duration                      4636
ongoing                          0
sznOfRelease                     0
years_running                    0
studio_primary                   0
studios_colab                    0
contentWarn                      0
watched                          0
watching                         0
wantWatch                        0
dropped                          0
rating                           0
votes                            0
tag_Based_on_a_Manga             0
tag_Comedy                       0
tag_Action                       0
tag_Fantasy                      0
tag_Sci_Fi                       0
tag_Shounen                      0
tag_Original_Work                0
tag_Non_Human_Protagonists       0
tag_Drama                        0
tag_Adventure                    0
tag_Family_Friendly              0
tag_Short_Episodes               0
tag_School_Life                  0
tag_Romance                      0
tag_Shorts                       0
tag_Slice_of_Life                0
tag_Seinen                       0
tag_Supernatural                 0
tag_Magic                        0
tag_Animal_Protagonists          0
tag_Ecchi                        0
tag_Mecha                        0
tag_Based_on_a_Light_Novel       0
tag_CG_Animation                 0
tag_Superpowers                  0
tag_Others                       0
tag_missing                      0
dtype: int64

In [ ]:
anime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12101 entries, 0 to 12100
Data columns (total 44 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   title                       12101 non-null  object
 1   description                 7633 non-null   object
 2   mediaType                   12101 non-null  object
 3   eps                         12101 non-null  int64
 4   duration                    7465 non-null   float64
 5   ongoing                     12101 non-null  bool
 6   sznOfRelease                12101 non-null  object
 7   years_running               12101 non-null  int64
 8   studio_primary              12101 non-null  object
 9   studios_colab               12101 non-null  int64
 10  contentWarn                 12101 non-null  int64
 11  watched                     12101 non-null  float64
 12  watching                    12101 non-null  int64
 13  wantWatch                   12101 non-null  int64
 14  dropped                     12101 non-null  int64
 15  rating                      12101 non-null  float64
 16  votes                       12101 non-null  int64
 17  tag_Based_on_a_Manga        12101 non-null  int64
 18  tag_Comedy                  12101 non-null  int64
 19  tag_Action                  12101 non-null  int64
 20  tag_Fantasy                 12101 non-null  int64
 21  tag_Sci_Fi                  12101 non-null  int64
 22  tag_Shounen                 12101 non-null  int64
 23  tag_Original_Work           12101 non-null  int64
 24  tag_Non_Human_Protagonists  12101 non-null  int64
 25  tag_Drama                   12101 non-null  int64
 26  tag_Adventure               12101 non-null  int64
 27  tag_Family_Friendly         12101 non-null  int64
 28  tag_Short_Episodes          12101 non-null  int64
 29  tag_School_Life             12101 non-null  int64
 30  tag_Romance                 12101 non-null  int64
 31  tag_Shorts                  12101 non-null  int64
 32  tag_Slice_of_Life           12101 non-null  int64
 33  tag_Seinen                  12101 non-null  int64
 34  tag_Supernatural            12101 non-null  int64
 35  tag_Magic                   12101 non-null  int64
 36  tag_Animal_Protagonists     12101 non-null  int64
 37  tag_Ecchi                   12101 non-null  int64
 38  tag_Mecha                   12101 non-null  int64
 39  tag_Based_on_a_Light_Novel  12101 non-null  int64
 40  tag_CG_Animation            12101 non-null  int64
 41  tag_Superpowers             12101 non-null  int64
 42  tag_Others                  12101 non-null  int64
 43  tag_missing                 12101 non-null  int64
dtypes: bool(1), float64(3), int64(35), object(5)
memory usage: 4.0+ MB

In [ ]:
# smallest duration of a title
anime['duration'].describe()

count    7465.000000
mean       24.230141
std        31.468171
min         1.000000
25%         4.000000
50%         8.000000
75%        30.000000
max       163.000000
Name: duration, dtype: float64

In [ ]:
dur_val = anime['duration'].min()

In [ ]:
#filter where duration is min
# write the condition - syntax: df[condition]
filter_df = anime[anime['duration']==dur_val]

In [ ]:
filter_df

,title,description,mediaType,eps,duration,ongoing,sznOfRelease,years_running,studio_primary,studios_colab,...,tag_Supernatural,tag_Magic,tag_Animal_Protagonists,tag_Ecchi,tag_Mecha,tag_Based_on_a_Light_Novel,tag_CG_Animation,tag_Superpowers,tag_Others,tag_missing
914,Saiyuki Reload: Urasai,"Now that the series has finished airing, it’s ...",DVD Special,24,1.0,False,is_missing,1,Studio Pierrot,0,...,0,0,0,0,0,0,0,0,0,0
1088,Aggretsuko (2016),Retsuko is a 25-year old red panda who works i...,TV,100,1.0,False,Spring,2,Others,0,...,0,0,1,0,0,0,0,0,0,0
1103,Hungry Days x One Piece,NaN,Other,4,1.0,False,is_missing,1,Shaft,0,...,0,0,0,0,0,0,0,0,0,0
1314,Katarina Nounai Kaigi,NaN,Web,26,1.0,True,Winter,0,is_missing,0,...,0,0,0,0,0,1,0,0,0,0
1460,My Bride is a Mermaid OVA Special,NaN,DVD Special,2,1.0,False,is_missing,1,AIC,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12077,3D Onara Gorou ga Dance Dance Dance!!,"Onara Gorou takes the stage to do a smelly, ga...",Web,1,1.0,False,is_missing,0,Others,0,...,0,0,0,0,0,0,1,0,0,0
12079,Pundarika,NaN,Web,1,1.0,False,is_missing,0,is_missing,0,...,0,0,0,0,0,0,0,0,0,0
12080,Ai (2012),NaN,Web,1,1.0,False,is_missing,0,is_missing,0,...,0,0,0,0,0,0,0,0,0,0
12081,Oshiri Mae Man: Akagi Nyugyo Chocomint CM,NaN,Web,1,1.0,False,is_missing,0,is_missing,0,...,0,0,0,0,0,0,0,0,0,0
12088,Kokuhaku,NaN,Web,1,1.0,False,is_missing,0,is_missing,0,...,0,0,0,0,0,0,1,0,0,0

In [ ]:
filter_df['title'].unique()

array(['Saiyuki Reload: Urasai', 'Aggretsuko (2016)',
       'Hungry Days x One Piece', 'Katarina Nounai Kaigi',
       'My Bride is a Mermaid OVA Special',
       'Tanaka-kun wa Kyou mo Kedaruge',
       'Ghost in the Shell: Stand Alone Complex 2nd Gig - Tachikoma Days',
       'Maria-sama ga Miteru 4th Specials',
       'Tentai Senshi Sunred Specials',
       'Ghost in the Shell: Stand Alone Complex - Tachikoma Days',
       'Tanuki to Kitsune', 'When They Cry: Kai - Ura Higu',
       'Nichijou: My Ordinary Life Specials', 'Maho-Yome',
       'Princess Princess Specials', 'Karneval Specials',
       'My Wife Is the Student Council President! Okusama Gekijou',
       'Ani*Kuri15', 'Mameshiba', 'Good Morning!!! Doronjo', 'Gudetama',
       'A Polar Bear in Love', 'Magical Witch Punie-chan Specials',
       'Komatta Jii-san',
       'The Kawai Complex Guide to Manors and Hostel Behavior Specials',
       'Place to Place Youchien', 'Katato The Animation',
       'My-Hime Specials', 'Classroom of the Elite PV',
       'Love Live! x Watering KissMint Collaboration CM',
       'Cells at Work! Commercial', 'Soul Eater: Late Night Show',
       'Tokyo Disney Resort: Yume ga Kanau Basho',
       'Shirotan: Shirotan ga Ippai!',
       'Pokemon: Eevee and Colorful Friends',
       'Aoki Hagane no Arpeggio: Ars Nova - Kirikumas',
       'The iDOLM@STER: Cinderella Girls Theater 2nd Season (Web)',
       "Dog Days '': Gravure Talk", 'Ultimate Otaku Teacher (2012)',
       "Dog Days'' Specials", '22/7: Ano Hi no Kanojo-tachi',
       'Hikaru Utada: Fluximation',
       'The iDOLM@STER: Cinderella Girls Theater (Web)',
       'Monster Musume: Hobo Mainichi OO! Namappoi Douga',
       'Neko ga Kureta Marui Shiawase',
       'Jin: Nihonbashi Koukashita R Keikaku',
       'Kyoto Animation CM: Suiei-hen',
       'Chiba Pedal: Yowamushi Pedal to Manabu Jitensha Koutsuuanzen',
       'Warm, Winter Canada',
       'The iDOLM@STER: Cinderella Girls Theater 3rd Season (Web)',
       'Chicken Ramen CM', 'Choujuu Giga', 'Nisekoimonogatari',
       'Tsubasa to Hotaru (2015)',
       'The iDOLM@STER Million Live! "Dreaming!" Animation PV',
       'Dungeon Meshi CM', 'Ghibli ga Ippai Special Short Short',
       'JR Nishi Nihon: Summer Train!', 'Onikiri Musume Saisen',
       'Hikari no Megami',
       'HENNEKO - The Hentai Prince and the Stony Cat Specials',
       'Sengoku Basara Movie: 4-Koma Gekijou - Another Last Party',
       'A Polar Bear in Love (Web)', 'Golden Douga Gekijou',
       'Isekai Quartet Relay PV', 'Other Worlds', 'True Tears Specials',
       'A Day Before Us: Merry Christmas!',
       'Nekota no Koto ga Ki ni Natte Shikatanai. (2015)', 'Run!',
       'Gakuen Heaven: Hamu Hamu Heaven',
       'Love Live! The School Idol Movie: Manner Movie',
       'Kyoto Animation CM: Megane-hen', 'The Five Killers',
       'Gintama x Mameshiba', 'Super Juniors: Circus',
       'Akame ga Kill! Theater', 'Nisshin Seifun Group CM',
       'Nagareboshi Lens Specials', 'Hairy Tale',
       'Umineko: When They Cry Specials', 'Yozakura Quartet: Yoza-Quar!',
       'Neko Nanka Yonde mo Konai.', 'Car & Tue',
       'Kyoto Animation CM: Ikitaku Naru Omise-hen',
       'Tales of the Rays: Mirrage Prison', 'RIN-NE CM', 'Race Eizou-hen',
       'Mottainai', 'Nekojiru Gekijou', 'Hot Minute: Gudetama',
       'Love, Chunibyo & Other Delusions! Movie: Take On Me Mini-Drama',
       'Cogimyun', 'No Money Specials', 'Ninja Scroll BURST', 'Babyshiba',
       'SKET Dance: SD Character Flash Anime',
       "Cowboy Bebop: Ein's Summer Vacation", 'Yuyushiki: Nyanyashiki',
       'Say "I love you." - Mei and Marshmallow', 'Un-Go: Inga Nikki',
       'Kensaku to Enjin no ABC Days', 'Kyoto Animation CM: Kasa-hen',
       'Dededen', 'Sayonara Zetsubou Sensei Special Omake',
       'Kano: day by day', 'Gerotan', 'Kizuna (Tekken)', 'Trigger-chan',
       'Chokotto Anime Kemono Friends 3', 'Fate/strange Fake PV',
       "Murphy's Irish Stout: Last Orders",
       'Kyoto Animation CM: Hoshi-hen', 'Jurassic!',
       'Inishie no Megami to Houseki no Ite',
       'Wolf Children x House Shokuhin Stew',
       'Taisei Kensetsu: Vietnam Noi Bai Kuukou',
       'Culture City of East Asia 2019 Toshima', 'Neko mo, Ondake',
       'Noragami: Noraneko', 'Pretty Cure kara Minna e no Ouen Movie',
       'Taisei Kensetsu: Sri Lanka Kousokudouro',
       'Sandwhichman Touhoku Ai Bottle', 'Petit Gargantia',
       'TOHO Cinemas x One Piece Film: Gold - Tokubetsu Eizou',
       'Chiisana Oji-san', 'Hirooka Asako', 'Oniwa no Soto',
       'Miracle Train: Chuo-sen e Youkoso', 'A New Journey',
       "I Couldn't Become a Hero, So I Reluctantly Decided to Get a Job. Specials",
       'Eureka Seven Ao: Aratanari Fukaki Ao',
       'Dungeon Meshi: Senshi no Kantan Cooking!', 'Bibury',
       'Taisei Kensetsu: Bosporus Kaikyou Tunnel',
       'Nissin Men-nashi Donbei x Himote House',
       'Curry Meshi x Zombieland Saga',
       'Legend of Basara: Shinbashi Theater',
       'One Piece Film: Gold - Cine Mike Popcorn Kokuchi',
       'Attack on Titan: Attack on Celebrity',
       'Kyoto Animation CM: Hana-hen',
       'Pokemon XY: Hoopa no Odemashi Daisakusen!!',
       'Kensaku to Enjin no Atarashii Tomodachi: Query Toujou!',
       'Princess Lover! Magical Knight Maria-chan',
       'Asobi ni Iku yo! Asobi ni Oide Special', 'Pop Team Epic Specials',
       'Fanta x One Piece', 'Toji no Miko: Kizamishi Issen no Tomoshibi',
       'Hungry Days: Aoharu ka yo.',
       'Asteroid in Love: KiraKira Zoukangou!', 'The Curlydog Story',
       'Code Geass: Lelouch of the Rebellion R2 Flash Specials',
       'Taisei Kensetsu: Shin Doha Kokusai Kuukou',
       'Shounen Sunday CM Gekijou: Inuyasha-hen',
       'The iDOLM@STER Million Live! 1st Anniversary PV',
       'A Branch of a Pine Is Tied up', 'Watashitachi, Luck Logic Bu! 2',
       'All That Gundam', 'Kara no Kyoukai: Cinema Intros',
       'Zoku Natsume Yuujinchou: 3D Nyanko-sensei Gekijou',
       'Youchien Senshi: Hanamaru Girls', 'Kemurikusa (2018)',
       'Lipton #watashitolipton', 'Potecco Babies (2011)',
       'Kyoto Animation Koushiki Twitter: Itsumo Arigatou',
       'Taisei Kensetsu: Singapore', 'Ohayou Hakushon Daimaou ZIP!',
       'Scratch x One Piece Film: Gold', 'Otoboke Beaver: Ikezu',
       'Kyoei Tankou-sho',
       'Taiko Drum Master: 15 Shuunenkinen Short Animation',
       'Shokupan Mimi', 'Mirai Koushi Harima SACLA',
       'Kyoto Animation CM: Hassou-hen', 'Kubbe no Ongakukai',
       'Mazinger ZIP!',
       'Madobe Nanami no Windows 7 de PC Jisaku Ouen Commercial!!',
       'Aoku Tsuzuku Pass', 'Puzzle & Dragons CM', 'Nishitesu CMs',
       'Home-Pato the Movie', 'Mochi Mochi Panda',
       'Kuragehime: Soreike! Amars Tankentai', 'Balloon',
       'Rilakkuma: Strawberry Party', 'Kyoto Animation CM: Sora-hen',
       'Hanamaru Kindergarten: Panda Neko Taisou',
       'Suntory Minami Alps no Tennen Mizu',
       'Morinaga Nyuugyou x Mary to Majo no Hana',
       'Metroid Short Animation',
       'Fate/Grand Order: Servant Summer Festival! Announcement CM',
       'All-Free kono Natsu Ichioshi Monogatari Campaign Kokuchi Douga',
       'Inazma Delivery: Bytheway Dance', 'Donbei x Kemurikusa',
       'Kyoto Animation CM: Ajisai-hen', 'Raldessia Chronicles CM',
       'Hiyoko no Basket Movie: Last Game 0401', 'Hungry to Win',
       'Mini-Chara Macross', 'Kensaku to Enjin no Happy Birthday',
       'Sofy Soft Tampon: Drive Ryokou-hen', 'Tansa Quest! (2015)',
       'HATSUNE MIKU x TETSUYA NOMURA',
       'Persona 3 the Movie Meets “Walkman”',
       'Garo: Crimson Moon - Yurugaro', 'Rokudou Juku', 'Project HAL',
       'Green Dakara x Mirai no Mirai',
       'Yugami-kun ni wa Tomodachi ga Inai CM', 'Fast Week',
       'Patisserie no Monster', 'AKB48 Stage Fighter',
       'Ninja Batman x Poputepipikku Kindan no Collab CM',
       'Okitegami Kyouko no Bibouroku x Monogatari',
       'K: Missing Kings - Manner Movie', 'Toho Cinemas x Pokemon Go',
       'Kyushu Love Milk Club', 'Kotatsu Neko (Web)',
       'Yukimi-ka no Nichijou wa Honwari de Shimeru',
       'Show By Rock!! Plasmagica na Gogo', 'Chicken Ramen x Gudetama',
       'Meiji x Kokosake & Anohana Receipt Oubo Campaign', 'Go Around',
       'Deva Zan', 'Nissin Cup Noodles x Dragon Ball Z', 'MaxValu Kyushu',
       'Puella Magi Sonico Magica', 'Sugar Soldier', 'Plus Kouji',
       'Against', 'Sante FX x One Piece',
       '009 Re:Cyborg: Seishain Cyborg 003', 'Domo-kun',
       'The Anthem of the Heart x Sony Hi-Res "Walkman" and Headphone',
       'Anime-gatari', 'CLAMP School Detectives Shorts',
       '009 Re:Cyborg x Zip', 'BUCK-TICK x HAL',
       'Maria Holic Alive: Runrunriru Ranranrara', 'Hanasu na',
       'Sou x Fireworks', 'Tokino Kousa', 'Psycho Nyanya: Nyanya Song',
       'Pepsi Nex x 009 Re:Cyborg', 'Katsudou Shashin',
       'Green Dakara x Bakemono no Ko', 'PRINTER REC Music',
       'Hatsune Miku: Hiyashite Narasou Okashi no Ii Oto',
       'ADOBE student pack CM', 'Be Blues! Ao ni Nare CM',
       'GANTZ x Senran Kagura New Link PV', 'Asa da yo! Kaishain',
       'Irodorimidori: Brilliant Better',
       'Kamiusagi Rope x Boruto: Naruto Next Generations', 'CoCO & NiCO',
       'Atama wa Tsukaiyou. Card mo Tsukaiyou.', 'Romantica Clock',
       'MTV Japan Station ID',
       'Nora, Princess, and Stray Cat: Nora Fuku Ekichou Shuunin Shiki',
       'New My Tear CL Series', 'Inazuma Eleven x Despicable Me',
       'Watashitachi, Luck Logic Bu!', 'Kakomareta Sekai',
       'Kamen Rider Fourze x Crayon Shin-chan', 'Anison Nippon',
       'Nissin no Donbei x Kemono Friends', 'Yeastken',
       '20-dai no Heya-hen', 'Planet: Valkyrie', 'Fate/Zero Cafe',
       'Kaisoku Tokyo: Kaijuu', 'Tobidase!! Buddy-kun', 'Promedicus CM',
       'Yomiuri Shimbun', 'Uchiko no Mama to Okaasan',
       'Shinano Mainichi Shinbun', 'Nandarou',
       'Jirijiri Moyou no Ryuuryuu Tenten', 'Saitou Kazuyoshi: Car Radio',
       'Origami of Landscape',
       'The Garden of Sinners: Recalled Out Summer - Manner Movie',
       'Kuraki Mai: Stay The Same',
       'Wish Upon the Pleiades: Manner Movie', 'Yanesenondo',
       "Psycho Nyanya: Let's overcome COVID-19!",
       'Jakusansei Million Arthur Specials', 'Gore-Tex Infinium',
       'Kakegae no', 'Match Shoujo', 'Kuroneko Monroe',
       'The Irregular at Magic High School x Mameshiba',
       'PJ Berri no Mogumogu Munyamunya', 'Ki de Tsukurou',
       'Short Animation of Shintaro Kago', '47 Todoufuken',
       'Toei Robot Girls', 'Slow Start: Web Yokoku Movie',
       'The New A-Class: Next Stage with YOU', 'Bloody Bunny',
       'Letchu, Getchu, Saru Getchu',
       'Rudolf to Ippaiattena x Godzilla x Toho Cinemas Moving Logo Eizou',
       'Umacha', 'Ahiru no Otegara', 'Azure Nihon Data Center',
       'Ken to Mahou no Logres: Inishie no Megami x Fate/Extella',
       'Gingirl', 'Chinka', 'Pichiko Dakyuubu USA-hen',
       'Chibi Godzilla: TOHO Cinemas Yokoku Countdown Animation',
       'Estima: Sense of Wonder',
       'Show By Rock!! Legend of Shingan Crimsonz',
       'Imawa no Kuni no Alice CM', 'The Green Wind', 'Pichiko Dakyuubu',
       'Self Portrait', 'Inferno Cop: Fact Files',
       'Fairy Tail x Mameshiba', 'Scandal', 'Wish Me Mell',
       'Ishii Hiroyuki x Saitou Souma Essay-shuu', 'Jingle',
       'Ya-Ne-Sen a Go Go', 'On a Forest, in the Air',
       'Go Go Smile Anime', 'Bouningen Weekend',
       'Calamity of a Zombie Girl PV', 'WAAAH', 'Koshikko', 'Oshiruko',
       'Ikeike! Momon-chan', 'Anime-gatari x Attack on Titan',
       'Convenience Store Senki Purin-tai', 'Mori no Kokoro-Koro',
       'Namakura Gatana: Kunoichi-hen', 'Aoshima Megu', 'Four Birds',
       'Henkei Shoujo', 'Sore Ike! Sabuibo Mask',
       'Yano Akiko & YUKI: Banana ga Suki', 'Kihei Senki Legacies',
       'RAG FAIR: Magical Music Train', 'Ai Sky Tree 21',
       'Animagear (2019)', 'Color Noise', 'Kano: 29-Q',
       'Doubutsu Sumo Taikai', 'Shoujouji no Tanuki-bayashi',
       'Count Down', 'perfume BVH import', 'Tokiwa Kitareri!!',
       'Isobe Isobee with Nakata Yasutaka de Sourou', 'Pacusi',
       'Onnanoko tte.', 'Japanda', 'Urashima Tarou (1918)', 'Hana',
       'YANAKIKU: HACHIKO↑DANCE', 'Beginning of Fashion', 'Timbre A to Z',
       'Kirin Hyoketsu: Atarashiku Ikou Animation Movie', 'Gokiburi-hime',
       'Crayon Shin-chan x Panpaka Pants: Aeon Cinema Manner Movie Collab',
       'Mameshiba Gakuen', 'Choco Kyouju no Oheya',
       'Yowai Robot to 10 no Story Project', 'Akai Kutsu! Onnanoko!',
       'Mini Moni the TV', 'Calbee Hitokuchi Gekijou', "Deniroo's Circus",
       'Rokuko-chan', 'Hinomaru Hatanosuke: Bakemono Yashiki no Maki',
       'Tanahashi Hiroshi x Mameshiba Pro Wrestling', 'zap dog',
       'Ai wa KAT-TUN',
       'Hinomaru Hatanosuke: Inazuma-gumi Tobatsu no Maki',
       'Sanuki Eiga-sai Opening Eizou',
       'InaDan Movie x Mameshiba Collab CM', 'Yodel no Onna',
       'Urashima Tarou (1931)', 'Zarizari mo you no Ruru Tenten',
       'Zonmi-chan: Halloween Special Movie!', 'Joubuna Tire!',
       'Pinky Wakuwaku Tabi Stroll', 'Fly', 'JRA Hokan Keikaku',
       'Yaseruyagi', 'Mameshiba: 5-Shuunen Party-hen', 'Suntory CM',
       'Mameshiba x Kyary Pamyu Pamyu', 'PigMovie Butaodoru',
       'siroPd: Yu', 'Armored Core: Fort Tower Song',
       '2005-nen Uchuu no Tabi', 'Din Dong Specials', 'Fafa Movie',
       'Hakodate Musical', 'Bernard Specials',
       'Ikeike! Momon-chan Specials', 'Ishida and Asakura Special',
       'KochinPa! Dainiki', '12-gatsu no Uta', 'Toshi: Cherry Blossom',
       'Yakan Gakkou no Ura-sensei', 'Show By Rock!! x Joysound',
       'Dappys', 'Synchro Noise', 'Panpaka Pants',
       'Bouken Dankichi: Hyouryuu no Maki', 'Henna Omamesan',
       'Waanabi.jk', 'Straw Mania',
       '"Kiss Dekiru Gyoza" x Mameshiba Movie', 'Shiseido HG Super Hard',
       'Kaisoku Tokyo: Copy', 'Nakanaori', 'Port of Wormy',
       'Kaitei no Boukun', 'Bernard: China Diapers', 'Capsule Samurai',
       'Shin Tenchi Souzou', 'Mameshiba: Sakamichi Korokoro-hen',
       'Issun-boshi no Shusse', 'Kirin no Otenki Mama-san',
       'BAR Kiraware Yasai', 'NO LITTERING', 'Union Union',
       'Elleair x Kamiusagi Rope',
       'Wingcle Bear Hamkkehaneun Lomentig Hwaiteudei',
       'Himitsukessha Taka no Tsume: Teikyou Kakutoku Daisakusen - Sakusen Kaigi',
       'Pinky Monkey x FaFa Collaboration Animation: At Afternoon of Sunny Day',
       'Lilt', "Shinmai 'FUREAI' Net. Concept Movie", 'Aoki Seimei Hoken',
       'A Woman in a Fashion Building', 'Puru Pom', 'KochinPa!',
       'Kodansha Morning Two CM', 'Go! Go! Kadendanshi',
       'Hey, President Trap-kun!', 'Five Fire Fish',
       'Nasu Highland Park Horror Attraction "Sema Kuruoshii Ie"',
       'Taa-chan no Kaitei Ryokou', 'Blue Room', 'Nezumi no Rusuban',
       'Kick!', 'Maruman Loose Leaf', 'MTV Ident',
       'Funassyi no FunaFunaFuna Biyori',
       'Tapuri Card x Kaijuu Sakaba Kanpai: Kanegon no Shuchou', 'a_caFe',
       'Wena Wrist CM', 'Yuuto-kun ga Iku', 'Wego Graphics',
       'Ryuoo Ski Park CM', 'Dead World', 'Osaru no Kantai', 'Rockeppe',
       'Ninjutsu Hinotama Kozou: Edo no Maki',
       'Dekobou no Jidousha Ryokou', 'Kodansha Morning CM',
       'Yodel no Onna: Weather Report', 'Ohisama to Kaeru',
       'Tokyo Art Month', 'Kana Kana Kazoku: Shinnen no Goaisatsu',
       'Adachin Shows Up!', 'Onikiri Shoujo', 'Spring has come!',
       'Hana no Zundamaru: Junk', 'HiGH&LOW g-sword',
       'Mini Moni Yaru no da Pyon!', 'Gondora',
       'Kamiusagi Rope & Taka no Tsume Collab Eizou-hen',
       'O (Sawako Kabuki)', 'Factory',
       'Independent Animation Festival the 08th Opening Animation',
       'Raindrops Falling on My Head', 'Ragnastrike Angels',
       'Kabushikigaisha Aokishouji', 'Battle of Clay (2019)',
       'Kawaii Cook-san', 'Tokyo', 'Battle of Clay 2', 'Goara', '1',
       'Wild Life', 'USA Weather Show', 'Chicken Papa',
       'Direct Animation', 'Aware! Meisaku-kun: Oronamin C',
       'Gohan Kaijuu Pap x Himitsukessha Taka no Tsume',
       'Megane Super x Taka no Tsume',
       'Yamaki x Taka no Tsume: Yoshida Kantoku CM',
       'The Embryo Develops into a Fetus', "Octopus' Inconvenience",
       'Taka no Tsume-dan, Kono Natsu, Mura Hajimemasu.', 'Oi Pii-tan!!',
       'Mochibei', 'Petting a Dog', 'Gohan Kaijuu Pap CM',
       'Gokiburi Taisou', 'Nomura Securities x Taka no Tsume: NISA! CM',
       'Ki ni Masaru Mono', 'Shigeru', 'Kowasugimasu',
       'Yamaki x Taka no Tsume Daisakusen Prologue', 'Shitcom',
       'Nyanpuku Nyaruma', 'Roll', 'Kekkonshiki no Tori',
       '3D Onara Gorou ga Dance Dance Dance!!', 'Pundarika', 'Ai (2012)',
       'Oshiri Mae Man: Akagi Nyugyo Chocomint CM', 'Kokuhaku'],
      dtype=object)

In [ ]:
filter_df['title'].nunique()

514

In [ ]:
ls_mt = list(anime['mediaType'].unique())

In [ ]:
anime[anime['mediaType']=='TV'].shape[0]

3993

In [ ]:
for item in ls_mt:
    print(f"no of items for {item} are {anime[anime['mediaType']==item].shape[0]}")

no of items for TV are 3993
no of items for Movie are 1928
no of items for Web are 1170
no of items for TV Special are 504
no of items for OVA are 1770
no of items for is_missing are 63
no of items for DVD Special are 803
no of items for Other are 580
no of items for Music Video are 1290

In [ ]:
anime['mediaType'].value_counts()

mediaType
TV             3993
Movie          1928
OVA            1770
Music Video    1290
Web            1170
DVD Special     803
Other           580
TV Special      504
is_missing       63
Name: count, dtype: int64

In [ ]:
anime.head()

,title,description,mediaType,eps,duration,ongoing,sznOfRelease,years_running,studio_primary,studios_colab,...,tag_Supernatural,tag_Magic,tag_Animal_Protagonists,tag_Ecchi,tag_Mecha,tag_Based_on_a_Light_Novel,tag_CG_Animation,tag_Superpowers,tag_Others,tag_missing
0,Fullmetal Alchemist: Brotherhood,The foundation of alchemy is based on the law ...,TV,64,NaN,False,Spring,1,Bones,0,...,0,0,0,0,0,0,0,0,0,0
1,your name.,Mitsuha and Taki are two total strangers livin...,Movie,1,107.0,False,is_missing,0,Others,0,...,1,0,0,0,0,0,0,0,0,0
2,A Silent Voice,"After transferring into a new school, a deaf g...",Movie,1,130.0,False,is_missing,0,Kyoto Animation,0,...,0,0,0,0,0,0,0,0,0,0
3,Haikyuu!! Karasuno High School vs Shiratorizaw...,"Picking up where the second season ended, the ...",TV,10,NaN,False,Fall,0,Production I.G,0,...,0,0,0,0,0,0,0,0,0,0
4,Attack on Titan 3rd Season: Part II,The battle to retake Wall Maria begins now! Wi...,TV,10,NaN,False,Spring,0,Others,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# how many movies are there which has tag - Magic
anime['tag_Magic'].sum()

778

In [ ]:
anime[anime['tag_Magic']==1].shape[0]

778

In [ ]:
# fetch all titles where total tags are more than 3
anime.head(3)

,title,description,mediaType,eps,duration,ongoing,sznOfRelease,years_running,studio_primary,studios_colab,...,tag_Supernatural,tag_Magic,tag_Animal_Protagonists,tag_Ecchi,tag_Mecha,tag_Based_on_a_Light_Novel,tag_CG_Animation,tag_Superpowers,tag_Others,tag_missing
0,Fullmetal Alchemist: Brotherhood,The foundation of alchemy is based on the law ...,TV,64,NaN,False,Spring,1,Bones,0,...,0,0,0,0,0,0,0,0,0,0
1,your name.,Mitsuha and Taki are two total strangers livin...,Movie,1,107.0,False,is_missing,0,Others,0,...,1,0,0,0,0,0,0,0,0,0
2,A Silent Voice,"After transferring into a new school, a deaf g...",Movie,1,130.0,False,is_missing,0,Kyoto Animation,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
anime.columns

Index(['title', 'description', 'mediaType', 'eps', 'duration', 'ongoing',
       'sznOfRelease', 'years_running', 'studio_primary', 'studios_colab',
       'contentWarn', 'watched', 'watching', 'wantWatch', 'dropped', 'rating',
       'votes', 'tag_Based_on_a_Manga', 'tag_Comedy', 'tag_Action',
       'tag_Fantasy', 'tag_Sci_Fi', 'tag_Shounen', 'tag_Original_Work',
       'tag_Non_Human_Protagonists', 'tag_Drama', 'tag_Adventure',
       'tag_Family_Friendly', 'tag_Short_Episodes', 'tag_School_Life',
       'tag_Romance', 'tag_Shorts', 'tag_Slice_of_Life', 'tag_Seinen',
       'tag_Supernatural', 'tag_Magic', 'tag_Animal_Protagonists', 'tag_Ecchi',
       'tag_Mecha', 'tag_Based_on_a_Light_Novel', 'tag_CG_Animation',
       'tag_Superpowers', 'tag_Others', 'tag_missing'],
      dtype='object')

In [ ]:
# sum on row-wise
anime['total_genre'] = anime[['tag_Based_on_a_Manga', 'tag_Comedy', 'tag_Action',
       'tag_Fantasy', 'tag_Sci_Fi', 'tag_Shounen', 'tag_Original_Work',
       'tag_Non_Human_Protagonists', 'tag_Drama', 'tag_Adventure',
       'tag_Family_Friendly', 'tag_Short_Episodes', 'tag_School_Life',
       'tag_Romance', 'tag_Shorts', 'tag_Slice_of_Life', 'tag_Seinen',
       'tag_Supernatural', 'tag_Magic', 'tag_Animal_Protagonists', 'tag_Ecchi',
       'tag_Mecha', 'tag_Based_on_a_Light_Novel', 'tag_CG_Animation',
       'tag_Superpowers', 'tag_Others', 'tag_missing']].sum(axis=1)

In [ ]:
anime.columns.difference(['title', 'description', 'mediaType', 'eps', 'duration', 'ongoing',
       'sznOfRelease', 'years_running', 'studio_primary', 'studios_colab',
       'contentWarn', 'watched', 'watching', 'wantWatch', 'dropped', 'rating',
       'votes'])

Index(['tag_Action', 'tag_Adventure', 'tag_Animal_Protagonists',
       'tag_Based_on_a_Light_Novel', 'tag_Based_on_a_Manga',
       'tag_CG_Animation', 'tag_Comedy', 'tag_Drama', 'tag_Ecchi',
       'tag_Family_Friendly', 'tag_Fantasy', 'tag_Magic', 'tag_Mecha',
       'tag_Non_Human_Protagonists', 'tag_Original_Work', 'tag_Others',
       'tag_Romance', 'tag_School_Life', 'tag_Sci_Fi', 'tag_Seinen',
       'tag_Short_Episodes', 'tag_Shorts', 'tag_Shounen', 'tag_Slice_of_Life',
       'tag_Supernatural', 'tag_Superpowers', 'tag_missing', 'total_genre'],
      dtype='object')

In [ ]:
anime[anime['total_genre']>3]['title'].tolist()

['Fullmetal Alchemist: Brotherhood',
 'your name.',
 'A Silent Voice',
 'Attack on Titan 3rd Season: Part II',
 'Demon Slayer: Kimetsu no Yaiba',
 'Hunter x Hunter (2011)',
 'Gintama Kanketsu-hen: Yorozuya yo Eien Nare',
 'Gintama (2015)',
 'Mob Psycho 100 II',
 'Code Geass: Lelouch of the Rebellion R2',
 'Kaguya-sama: Love Is War?',
 'The Promised Neverland',
 'My Hero Academia 3',
 'March Comes in like a Lion 2nd Season',
 'Mushishi Zoku Shou 2nd Season',
 'My Hero Academia 2',
 "Natsume's Book of Friends Season 6",
 "Gintama'",
 'Gintama.: Shirogane no Tamashii-hen 2',
 'Gintama.',
 "Gintama': Enchousen",
 'One-Punch Man',
 'Spirited Away',
 'Mushishi Zoku Shou',
 'Gintama.: Shirogane no Tamashii-hen',
 'Rascal Does Not Dream of a Dreaming Girl',
 "Natsume's Book of Friends Season 4",
 'Made in Abyss',
 'Hajime no Ippo: New Challenger',
 "Natsume's Book of Friends Season 5",
 'Hajime no Ippo: The Fighting!',
 "Howl's Moving Castle",
 'Code Geass: Lelouch of the Rebellion',
 'Kizumonogatari Movie 3: Reiketsu',
 "JoJo's Bizarre Adventure: Golden Wind",
 'Princess Mononoke',
 'Monogatari Series: Second Season',
 'Gintama: Porori-hen',
 'My Hero Academia 4',
 'Luo Xiao Hei Zhan Ji Movie',
 'KonoSuba – God’s blessing on this wonderful world! Movie: Legend of Crimson',
 'Mushishi Zoku Shou: Suzu no Shizuku',
 'Assassination Classroom 2nd Season',
 "Natsume's Book of Friends Season 3",
 'Mushishi: Hihamukage',
 'Mo Dao Zu Shi',
 'The Disappearance of Haruhi Suzumiya',
 'Hajime no Ippo: Rising',
 'Fate/Zero 2',
 'Cowboy Bebop',
 'ERASED',
 'I Want to Eat Your Pancreas',
 'Dr. Stone',
 'The Disastrous Life of Saiki K. 2nd Season',
 'Fruits Basket 2nd Season',
 'Hotarubi no Mori e',
 'Yona of the Dawn: Zeno Arc',
 'Great Teacher Onizuka',
 "Natsume's Book of Friends Season 2",
 'Your lie in April',
 'Mushishi Zoku Shou: Odoro no Michi',
 'Kizumonogatari Movie 2: Nekketsu',
 'Chihayafuru 3',
 "JoJo's Bizarre Adventure: Diamond is Unbreakable",
 "Natsume's Book of Friends Movie: Ephemeral Bond",
 'My Hero Academia',
 'JoJo’s Bizarre Adventure: Stardust Crusaders - Battle in Egypt',
 'That Time I Got Reincarnated as a Slime',
 'Kamisama Kiss: Kako-hen',
 "Natsume's Book of Friends Season 6 Specials",
 'The Boy and the Beast',
 'Parasyte -the maxim-',
 'Food Wars! The Second Plate',
 'Fruits Basket 1st Season',
 'Made in Abyss Movie: Dawn of the Deep Soul',
 'The Rising of the Shield Hero',
 'Mob Psycho 100',
 'Mushishi',
 "Fate/stay night: Heaven's Feel II. lost butterfly",
 'Attack on Titan',
 'Gintama: Shinyaku Benizakura-hen',
 'Ascendance of a Bookworm: Part II',
 'Hellsing Ultimate',
 'My Hero Academia Movie 2: Heroes:Rising',
 'Food Wars! Shokugeki no Souma',
 'Food Wars! The Third Plate',
 'Barakamon',
 'No Game No Life: Zero',
 'Kingdom 3',
 'Noragami Aragoto',
 'Chihayafuru 2',
 'Attack on Titan 2nd Season',
 'Kono Oto Tomare! 2nd Season',
 'Tengen Toppa Gurren Lagann',
 'Black Butler: Book of the Atlantic',
 'No Game No Life',
 'Anohana: The Flower We Saw That Day',
 'Food Wars! The Third Plate: Totsuki Train Arc',
 'Dororo (2019)',
 'The Seven Deadly Sins: Revival of The Commandments',
 'Overlord III',
 'Spice and Wolf II',
 'The Disastrous Life of Saiki K. 3',
 'Evangelion: 2.0 You Can (Not) Advance',
 'One Piece Movie 10: Strong World',
 'Hajime no Ippo: Champion Road',
 'Rascal Does Not Dream of Bunny Girl Senpai',
 'Kamisama Kiss 2nd Season',
 'The Disastrous Life of Saiki K.',
 'Gintama: Aizome Kaori-hen',
 'Natsume Yuujinchou: Itsuka Yuki no Hi ni',
 'Maquia - When the Promised Flower Blooms',
 'Magi: The Kingdom of Magic',
 'Zoku Owarimonogatari',
 'Fate/stay night: Unlimited Blade Works 2',
 'Kaguya-sama: Love Is War',
 'My Neighbor Totoro',
 'Toradora!',
 'Fullmetal Alchemist',
 'Doukyuusei',
 'The Girl Who Leapt Through Time',
 'Fate/Zero',
 'Tengen Toppa Gurren Lagann: Lagann-hen',
 'Gintama: Yorinuki Gintama-san on Theater 2D',
 'Samurai Champloo',
 'A Place Further Than the Universe',
 'Snow White with the Red Hair 2nd Season',
 'Fate/stay night: Unlimited Blade Works',
 'Silver Spoon 2nd Season',
 'Bungou Stray Dogs 3rd Season',
 'Black Butler: Book of Murder',
 'The Seven Deadly Sins',
 'Kingdom 2',
 'One Piece Movie 14: Stampede',
 'Nodame Cantabile',
 'Black Butler: Book of Circus',
 'Summer Wars',
 'Dragon Ball Super Movie: Broly',
 'Re:ZERO -Starting Life in Another World-',
 'Bungou Stray Dogs 2nd Season',
 'Kizumonogatari Movie 1: Tekketsu',
 'Gintama: Shinyaku Benizakura-hen Special',
 "The Ancient Magus' Bride: Those Awaiting a Star",
 'Mobile Suit Gundam: The Origin',
 'Hunter x Hunter OVA 3: Greed Island Final',
 'Kamisama Kiss: Kamisama, Shiawase ni Naru',
 "KonoSuba – God's blessing on this wonderful world! 2",
 'K-On! Movie',
 'One Piece Film: Z',
 'Castlevania Season 2',
 'Yona of the Dawn',
 'Beastars',
 "The Ancient Magus' Bride",
 'Puella Magi Madoka Magica',
 'My Hero Academia The Movie: Two Heroes',
 'ReLIFE: Kanketsu-hen',
 'The Disastrous Life of Saiki K. - Reawakened',
 'Katanagatari',
 'One Piece',
 'Golden Kamuy 2nd Season',
 'Castlevania Season 3',
 'xxxHOLiC Kei',
 'Maid-sama!',
 'Tsubasa Reservoir Chronicle: Tokyo Revelations',
 'Detective Conan Movie 20: The Darkest Nightmare',
 'Space Brothers',
 "Fate/stay night: Heaven's Feel I. presage flower",
 "Natsume's Book of Friends",
 'Hunter x Hunter OVA',
 "JoJo's Bizarre Adventure: Stardust Crusaders",
 "History's Strongest Disciple Kenichi",
 'xxxHOLiC Rou',
 'Berserk: Golden Age Arc III - The Advent',
 'In This Corner of the World',
 'Tower of God',
 'Angel Beats!',
 'Karakai Jouzu no Takagi-san 2',
 'Fairy Tail 2',
 'Overlord',
 'Tokyo Godfathers',
 'Gintama: Jump Festa 2008',
 'Hajime no Ippo: Mashiba vs Kimura',
 'Hunter x Hunter OVA 2: Greed Island',
 'Detective Conan Movie 14: The Lost Ship in the Sky',
 'Fairy Tail: Final Season',
 'Durarara!!',
 'Trigun',
 'Mobile Suit Gundam 00 Second Season',
 'Mobile Suit Gundam: Iron-Blooded Orphans 2',
 'T-sensei',
 'Land of the Lustrous',
 'Initial D Fourth Stage',
 'Redline',
 'Youjo Senki: Saga of Tanya the Evil',
 "JoJo's Bizarre Adventure (2012)",
 'Log Horizon',
 'Full Metal Panic? Fumoffu',
 'Made in Abyss: Hourou Suru Tasogare',
 'Hinamatsuri',
 'Whisper of the Heart',
 'Ascendance of a Bookworm',
 'Gintama',
 'Hunter x Hunter',
 'Spice and Wolf',
 'Kamisama Kiss',
 'The House of Small Cubes',
 'Wu Geng Ji 3rd Season',
 'Laputa: Castle in the Sky',
 "Sekai-ichi Hatsukoi: World's Greatest First Love 2",
 'Magi: Adventure of Sinbad',
 'March Comes in like a Lion',
 "Hozuki's Coolheadedness 2nd Season: Part II",
 'A Certain Scientific Railgun T',
 'Dorohedoro',
 'Fate/stay night: Unlimited Blade Works Prologue',
 'Working!!! Lord of the Takanashi',
 'Welcome to the NHK!',
 'Assassination Classroom',
 'Nichijou: My Ordinary Life',
 'Promare',
 'Wan Sheng Jie',
 "Beyond the Boundary Movie: I'll Be Here - Future",
 'Overlord II',
 'Detective Conan Movie 13: The Raven Chaser',
 'Durarara!! X2',
 'Noragami',
 'Full Metal Panic! The Second Raid',
 'Nisemonogatari',
 'Junjou Romantica 2',
 "Kino's Journey",
 'My Next Life as a Villainess: All Routes Lead to Doom!',
 'A Certain Scientific Railgun S',
 'Darker than Black',
 'Food Wars! The Fourth Plate',
 'ReLIFE',
 'Hi Score Girl: Extra Stage',
 'Initial D Fifth Stage',
 "Miss Kobayashi's Dragon Maid",
 'Durarara!! X2 The Third Arc',
 "Kiki's Delivery Service",
 'GATE (2016)',
 'My Teen Romantic Comedy SNAFU TOO!',
 'Astra Lost in Space',
 'Welcome to the Ballroom',
 'Daily Lives of High School Boys',
 'Hi Score Girl II',
 'Clannad',
 'The World God Only Knows: Goddesses Arc',
 'Non Non Biyori Repeat',
 'Love, Chunibyo & Other Delusions! Movie: Take On Me',
 'Tenchi Muyo! War on Geminar',
 'Grand Blue',
 'Berserk: Golden Age Arc II - The Battle for Doldrey',
 'Laid-Back Camp',
 'Nura: Rise of the Youkai Clan - Demon Capital',
 "Magical Girl Lyrical Nanoha: The Movie 2nd A's",
 'Aggretsuko 2',
 'Chihayafuru',
 'Berserk',
 'Kimi ni Todoke - From Me To You 2nd Season',
 'Working!!!',
 'Ling Jian Zun 3rd Season',
 'One Piece Film: Gold',
 'Broken Blade Movie 4: The Land of Calamity',
 'Initial D Second Stage',
 'Evangelion: 1.0 You Are (Not) Alone',
 'Junjou Romantica 3',
 'The Pet Girl of Sakurasou',
 'Gintama: Jump Festa 2015',
 'Durarara!! X2 The Second Arc',
 'KonoSuba – God’s blessing on this wonderful world! 2 OVA',
 'Mobile Suit Gundam 00',
 "JoJo's Bizarre Adventure: Phantom Blood",
 'Magi: Adventure of Sinbad OVA',
 "Hozuki's Coolheadedness 2nd Season",
 'Honey and Clover II',
 'xxxHOLiC Shunmuki',
 'From the New World',
 'Kimi ni Todoke - From Me To You',
 'Planetes',
 'Drifters',
 "Monthly Girls' Nozaki-kun",
 'School Rumble: 2nd Semester',
 'Magi: The Labyrinth of Magic',
 'Nekomonogatari (Black)',
 'The World God Only Knows II',
 'Bungou Stray Dogs Movie: Dead Apple',
 'The Eccentric Family 2',
 'Saint Seiya: The Lost Canvas - Meiou Shinwa 2nd Chapter',
 'Silver Spoon',
 'Broken Blade Movie 5: The Gap Between Life & Death',
 'Hajime no Ippo: The Fighting! Special',
 'My Love Story!!',
 'Snow White with the Red Hair',
 'Kamisama Kiss OVA',
 'Space Dandy 2',
 'Somali and the Forest Spirit',
 'Made in Abyss: Tabidachi no Yoake',
 "KonoSuba – God's blessing on this wonderful world!",
 "Broken Blade Movie 3: Scars from an Assassin's Blade",
 'Gintama: Dai Hanseikai',
 'Yaoshenji 3rd Season',
 'Yu Yu Hakusho',
 'One-Punch Man: Road to Hero',
 'Fairy Tail',
 'Code Geass: Lelouch of the Rebellion I - Initiation',
 'Shirobako',
 'Sekai-ichi Hatsukoi: Yokozawa Takafumi no Baai',
 'Noragami Aragoto OVA',
 'One Piece: Episode of Merry - Mou Hitori no Nakama no Monogatari',
 'Slayers Next',
 'Fullmetal Alchemist: Brotherhood Specials',
 'Wotakoi: Love is Hard for Otaku - Youth',
 'The Anthem of the Heart',
 'One Piece: Episode of Nami - Koukaishi no Namida to Nakama no Kizuna',
 'GATE',
 'One-Punch Man 2',
 'Little Busters! Refrain',
 "One Piece 3D2Y: Overcoming Ace's Death! Luffy's Pledge to His Friends!",
 'Mobile Suit Gundam Unicorn',
 'Tokyo Ghoul',
 'School Babysitters',
 'Tong Ling Fei',
 'Erin',
 'Castlevania',
 'Junjou Romantica OVA 2',
 'Sword Art Online: Alicization - War of Underworld',
 'Big Windup! 2',
 'K-On!!',
 'Tsubasa: Spring Thunder Chronicle',
 'My Roommate is a Cat',
 'Darker than Black: Kuro no Keiyakusha Gaiden',
 'Gintama: Jump Festa 2005',
 'The Garden of Sinners Movie 2: ...And Nothing Heart. (Murder Speculation Part A)',
 "Working'!!",
 "Gurren Lagann Movie 1: Childhood's End",
 'Kanon (2006)',
 'Mobile Suit Gundam: The Origin - Advent of the Red Comet',
 'Toilet-Bound Hanako-kun',
 'Detective Conan Movie 19: The Hellfire Sunflowers',
 'Ne Zha',
 'Spice and Wolf II OVA',
 'Is It Wrong to Try to Pick Up Girls in a Dungeon?',
 'Kokoro Connect: Michi Random',
 'From Up On Poppy Hill',
 'Initial D',
 'Aggretsuko',
 'One Piece: Strong World - Episode 0',
 'Soul Eater',
 'Mobile Suit Gundam: Iron-Blooded Orphans',
 'Broken Blade Movie 2: The Path of Separation',
 "Hozuki's Coolheadedness OVA",
 'Little Witch Academia TV',
 'Food Wars! The Fifth Plate',
 "Sekai-ichi Hatsukoi: World's Greatest First Love",
 'Snow White with the Red Hair OVA',
 "Sekai-ichi Hatsukoi: World's Greatest First Love OVA",
 'Assassination Classroom 2nd Season: Kagaijugyou-hen',
 'Broken Blade Movie 6: Fortress of Lamentation',
 'The Devil is a Part-Timer!',
 'BOFURI: I Don’t Want to Get Hurt, so I’ll Max Out My Defense.',
 'Slam Dunk',
 'My Teen Romantic Comedy SNAFU TOO! OVA',
 'Naruto Shippuden',
 'Fire Force',
 'Classroom of the Elite',
 'Lovely Complex',
 'Ushio and Tora TV (2016)',
 'Blood Blockade Battlefront & Beyond',
 'Berserk: Golden Age Arc I - The Egg of the King',
 'Mobile Suit Gundam: The 08th MS Team',
 'Brand New Animal',
 'One-Punch Man Specials',
 'The Melancholy of Haruhi Suzumiya',
 'Log Horizon 2',
 "Wolf's Rain OVA",
 'Overlord: Shikkoku no Senshi',
 'Blue Exorcist',
 'Seitokai Yakuindomo* OVA',
 'Sket Dance OVA',
 'Saiunkoku Monogatari 2nd Series',
 'Psycho-Pass: The Movie',
 'Ajin: Demi-Human 2nd Season',
 'Welcome to Demon School, Iruma-kun',
 'Alderamin on the Sky',
 'The Seven Deadly Sins Movie: Prisoners of the Sky',
 'Broken Blade Movie 1: The Time of Awakening',
 'Overlord: Fushisha no Ou',
 "Natsume's Book of Friends: Nyanko-sensei & The First Errand",
 'Wu Geng Ji 2nd Season',
 'One Piece: Episode of East Blue',
 'Goblin Slayer',
 'My Teen Romantic Comedy SNAFU',
 'One Piece: Episode of Sabo',
 'The Cat Returns',
 'The Last: Naruto the Movie',
 'Pokemon: The Origin',
 'Seraph of the End: Battle in Nagoya',
 'Kill La Kill',
 "Girls' Last Tour",
 'Kaiba',
 'Hellsing Ultimate: Digest for Freaks',
 'Dragon Ball Z Kai: The Final Chapters',
 "Magical Girl Lyrical Nanoha A's",
 'Macross Frontier',
 'Tanaka-kun is Always Listless',
 'Stand by Me Doraemon',
 'Interviews with Monster Girls',
 "Miss Kobayashi's Dragon Maid: Valentines and Hot Springs! (Please Don't Get Your Hopes Up)",
 'Mobile Suit Gundam: Thunderbolt - December Sky',
 'Saint Seiya: The Lost Canvas - Meiou Shinwa',
 'Yaoshenji 4th Season',
 'REBORN!',
 'Charlotte',
 'Anohana: The Flower We Saw That Day Movie',
 'Hidamari Sketch: Sae Hiro Sotsugyou-hen',
 'Transformers: The Movie',
 'Yuru Yuri San☆Hai!',
 'Hanasaku Iroha',
 'Magic Kaito',
 'Slayers Try',
 'Haré+Guu DELUXE',
 'Ascendance of a Bookworm OVA',
 'Outlaw Star',
 'Ponyo on the Cliff by the Sea',
 'D.Gray-man',
 'Blast of Tempest',
 'Junjou Romantica',
 'Saint Seiya: The Hades Chapter - Sanctuary',
 'Cardcaptor Sakura: The Movie 2: The Sealed Card',
 'Baka and Test - Summon the Beasts 2',
 'Fate/Kaleid Liner Prisma Illya Movie: Vow in the Snow',
 'Knights of Sidonia: Battle for Planet Nine',
 'Little Witch Academia',
 "Poco's Udon World",
 'Re:ZERO -Starting Life in Another World- The Frozen Bonds',
 "Kino's Journey: Life Goes On",
 'Toshokan Sensou: Kakumei no Tsubasa',
 'Bungou Stray Dogs',
 'Detective Conan Movie 12: Full Score of Fear',
 "Lupin III: Goemon's Blood Spray",
 'Lucky Star OVA',
 'Seitokai Yakuindomo OVA',
 'Full Metal Panic!',
 "Monthly Girls' Nozaki-kun Specials",
 'Dragon Ball Z',
 'Emma: A Victorian Romance - Second Act',
 'Big Windup!',
 'Tiger & Bunny',
 'Bungou Stray Dogs: Walking Alone',
 'You and Me. 2',
 'The World God Only Knows: Tenri Arc',
 "Hozuki's Coolheadedness OVA 2",
 'Fairy Tail Movie 2: Dragon Cry',
 'Ride Your Wave',
 'The Heroic Legend of Arslan: Dust Storm Dance',
 'Yaoshenji 2nd Season',
 'Black Butler',
 'Silver Fang',
 'A Lull in the Sea',
 'Hidamari Sketch x 365 EX',
 'D.Gray-man Hallow',
 'Kengan Ashura 2',
 'Hanada Shounen-shi',
 'Eureka Seven',
 'Macross Frontier Movie 2: Sayonara no Tsubasa',
 'Little Witch Academia: The Enchanted Parade',
 'Blue Spring Ride',
 'Assassination Classroom: Jump Festa 2013 Special',
 'Zoku Sayonara Zetsubou Sensei',
 'Quanzhi Fashi 4th Season',
 'Kyou Kara Ore Wa!!',
 'Radiant 2nd Season',
 'Love, Chunibyo & Other Delusions!',
 'That Time I Got Reincarnated as a Slime OVA',
 'Daily Lives of High School Boys Specials',
 "JoJo's Bizarre Adventure Re-Edited",
 'A Certain Magical Index II',
 'Genshiken 2',
 'Towa no Quon 6: Towa no Quon',
 'A Certain Scientific Railgun',
 'Kokoro Connect',
 'Free! Eternal Summer',
 'Future Diary',
 'Claymore',
 'Sword Art Online',
 'Noragami OVA',
 'Blue Exorcist Movie',
 'Golden Boy',
 'Tiger & Bunny The Movie: The Rising',
 'Saiunkoku Monogatari',
 'Luo Xiao Hei Zhan Ji',
 'Non Non Biyori',
 'Blue Exorcist: Kyoto Saga',
 'Tenchi Muyo! Ryo-Ohki 2',
 'My Hero Academia - All Might: Rising The Animation',
 'Goku Sayonara Zetsubou Sensei',
 'Cells at Work!',
 'InuYasha: Kuroi Tessaiga',
 'The World God Only Knows',
 'K: Missing Kings',
 'Towa no Quon 4: Guren no Shoushin',
 'Super Dimensional Fortress Macross',
 'High School DxD NEW',
 'Akame ga Kill!',
 'The Seven Deadly Sins OVA',
 'There She Is!!',
 'Colorful (2010)',
 'GaoGaiGar Final',
 'Hidamari Sketch x Honeycomb',
 'Shakugan no Shana II',
 'Seitokai Yakuindomo*',
 'Interspecies Reviewers',
 'KonoSuba – God’s blessing on this wonderful world! OVA',
 'Elfen Lied',
 'Magic Kaito 1412',
 'She and Her Cat: Everything Flows',
 'The Heroic Legend of Arslan',
 'xxxHOLiC',
 'Dragon Ball',
 'To Love Ru: Darkness 2nd Specials',
 'Hidamari Sketch x Hoshimittsu Specials',
 "Problem Children Are Coming From Another World, Aren't They?",
 'Akira',
 'Last Exile',
 'Kakuriyo: Bed & Breakfast for Spirits',
 'Zan Sayonara Zetsubou Sensei Bangaichi',
 'Dusk Maiden of Amnesia',
 'Drifters Specials',
 'The Morose Mononokean II',
 "Goblin Slayer: Goblin's Crown",
 'Is It Wrong to Try to Pick Up Girls in a Dungeon? Movie: Arrow of the Orion',
 'Yamada-kun and the Seven Witches',
 'Saint Young Men Movie',
 'Tsuredure Children',
 'Food Wars! Shokugeki no Souma OVA',
 'Irresponsible Captain Tylor',
 'Pretty Guardian Sailor Moon Crystal (2016)',
 'Symphogear XV',
 'K-On!',
 'Tales of Vesperia ~The First Strike~',
 'School Rumble: Extra Class',
 'The Kawai Complex Guide to Manors and Hostel Behavior',
 'Good Luck Girl!',
 'Kyo Kara Maoh! 3rd Series',
 "Interviews with Monster Girls: The Demi-chans' Summer Break",
 'K-On!!: Plan!',
 'Minami-ke Tadaima',
 "Heaven's Lost Property: Forte",
 'My Little Monster',
 'Working!!',
 "Chi's New Address",
 'Bloom Into You',
 'Maison Ikkoku',
 'Yuru Yuri Nachu Yachumi!',
 'Hello World',
 'Inuyashiki: Last Hero',
 'Hidamari Sketch x Hoshimittsu',
 'School Rumble',
 'Yuru Yuri ♪♪',
 "Kuroko's Basketball OVA",
 'Orange',
 'Sword Art Online: Alicization',
 'Sing "Yesterday" for Me',
 'Genshiken OVA',
 'Azumanga Daioh',
 'Full Metal Panic! Invisible Victory',
 'Towa no Quon 5: Souzetsu no Raifuku',
 'Fate/stay night: Unlimited Blade Works Movie',
 'Kill La Kill Special',
 'Grimgar of Fantasy and Ash',
 'Haré+Guu FINAL',
 'The Kawai Complex Guide to Manors and Hostel Behavior: First Time',
 'Quanzhi Fashi 3rd Season',
 'Space Brothers: Number Zero',
 'Hi Score Girl',
 'K: Return of Kings',
 'City Hunter 2',
 'Sayonara, Zetsubou-Sensei',
 'Hidamari Sketch x 365',
 'Non Non Biyori Repeat OVA',
 'Kakushigoto',
 'Yumeiro Pâtissière',
 'Angel Beats! Stairway to Heaven',
 'Hakkenden: Eight Dogs of the East 2',
 "Attack on Titan: Ilse's Notebook",
 'Hybrid Child',
 'The Irregular at Magic High School Movie: The Girl Who Summons the Stars',
 'Kingsglaive: Final Fantasy XV',
 'Beelzebub',
 'Princess Tutu',
 'Tekkon Kinkreet',
 'Fruits Basket',
 'Bleach Movie 4: Hell Verse',
 'Seraph of the End',
 'Strawberry Marshmallow OVA',
 'The Familiar of Zero: Knight of the Twin Moons',
 'Gabriel Dropout Specials',
 'One Piece: Episode of Luffy - Hand Island no Bouken',
 'Strawberry Marshmallow Encore',
 'Saiyuki Reload: Burial',
 'Sket Dance',
 'Kono Oto Tomare!',
 'Is this a Zombie? Of the Dead',
 'Fate/Grand Order: Absolute Demonic Front - Babylonia',
 "Darwin's Game",
 'Penguindrum',
 'Nura: Rise of the Youkai Clan',
 'Is It Wrong to Try to Pick Up Girls in a Dungeon? II',
 'The Irregular at Magic High School',
 'FLCL',
 'Noblesse: Awakening',
 'Mob Psycho 100 II: The First Spirits and Such Company Trip - A Journey that Mends the Heart and Heals the Soul',
 'The Quintessential Quintuplets',
 'Eyeshield 21',
 'Gargantia on the Verdurous Planet',
 'Sweetness & Lightning',
 'Mitsudomoe Zouryouchuu!',
 'Kabaneri of the Iron Fortress Movie: The Battle of Unato',
 'Knights of Sidonia',
 'The Legend of the Legendary Heroes',
 'Bleach',
 "Xam'd: Lost Memories",
 'Inu X Boku Secret Service Special',
 'Mobile Suit Gundam Wing',
 'Dragon Ball Super',
 'Yumeiro Pâtissière SP Professional',
 'City Hunter 3',
 'One Piece Special: Heart of Gold',
 'Mobile Suit Gundam SEED',
 'Moonlight Mile 2nd Season - Touch down',
 'Darker than Black: Gemini of the Meteor',
 'WorldEnd: What do you do at the end of the world? Are you busy? Will you save us?',
 'K: Seven Stories Movie 5 - Memory of Red ~BURN~',
 'Rage of Bahamut: Genesis',
 'High School DxD BorN',
 'Rilakkuma and Kaoru',
 'Mobile Suit Gundam: Thunderbolt',
 'Minami-ke',
 'To Love Ru: Darkness 2nd OVA',

In [ ]:
anime.to_csv('output.csv', index=False)

In [ ]:
sales = pd.read_csv('sales (1).csv')

In [ ]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117604 entries, 0 to 117603
Data columns (total 11 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       117604 non-null  object
 1   customer_id                    117604 non-null  object
 2   product_id                     117604 non-null  object
 3   category_english               115881 non-null  object
 4   price                          117604 non-null  float64
 5   freight_value                  117604 non-null  float64
 6   payment_type                   117601 non-null  object
 7   payment_value                  117601 non-null  float64
 8   order_purchase_timestamp       117604 non-null  object
 9   order_delivered_customer_date  115037 non-null  object
 10  total_price                    117604 non-null  float64
dtypes: float64(4), object(7)
memory usage: 9.9+ MB

In [ ]:
sales.describe()

               price  freight_value  payment_value    total_price
count  117604.000000  117604.000000  117601.000000  117604.000000
mean      120.822849      20.045551     172.686752     140.868400
std       184.477367      15.861351     267.592290     191.616461
min         0.850000       0.000000       0.000000       6.080000
25%        39.900000      13.080000      60.870000      55.270000
50%        74.900000      16.290000     108.210000      92.115000
75%       134.900000      21.190000     189.260000     157.780000
max      6735.000000     409.680000   13664.080000    6929.310000

In [ ]:
sales.describe(include='object')

,order_id,customer_id,product_id,category_english,payment_type,order_purchase_timestamp,order_delivered_customer_date
count,117604,117604,117604,115881,117601,117604,115037
unique,98666,98666,32951,71,4,88157,75649
top,895ab968e7bb0d5659d16cd74cd1650c,270c23a11d024a44c896d1894b261a83,aca2eb7d00ea1a7b8ebd4e68314663af,bed_bath_table,credit_card,08-08-2017 20:26,14-08-2017 12:46
freq,63,63,536,11823,86769,63,63

In [ ]:
sales['payment_type'].value_counts()

payment_type
credit_card    86769
boleto         22867
voucher         6274
debit_card      1691
Name: count, dtype: int64

In [ ]:
#sales, total_price > 500
sales.columns

Index(['order_id', 'customer_id', 'product_id', 'category_english', 'price',
       'freight_value', 'payment_type', 'payment_value',
       'order_purchase_timestamp', 'order_delivered_customer_date',
       'total_price'],
      dtype='object')

In [ ]:
sales[sales['total_price']>500]

,order_id,customer_id,product_id,category_english,price,freight_value,payment_type,payment_value,order_purchase_timestamp,order_delivered_customer_date,total_price
7,000576fe39319847cbb9d288c5617fa6,9ed5e522dd9dd85b4af4a077526d8117,557d850972a7d6f792fd18ae1400d9b6,garden_tools,810.00,70.75,credit_card,880.75,04-07-2018 12:08,09-07-2018 14:04,880.75
16,0009c9a17f916a706d71784483a5d643,8a250edc40ebc5c3940ebc940f16a7eb,3f27ac8e699df3d300ec4a5d8c5cf0b2,consoles_games,639.00,11.34,credit_card,650.34,25-04-2018 09:10,30-04-2018 17:54,650.34
40,0017afd5076e074a48f1f1a4c7bac9c5,8085a9af46f619bc25966f151a362b0d,fe59a1e006df3ac42bf0ceb876d70969,computers_accessories,809.10,44.29,credit_card,853.39,06-04-2017 22:16,23-05-2017 08:32,853.39
71,0029c5db35ef291ce99d1262012e7daa,2f08bf21468eccdf69598582d4b89fb5,7614c62b86a81021243e438cfde78ccc,health_beauty,492.75,21.62,boleto,514.37,25-08-2018 00:09,30-08-2018 18:34,514.37
160,006127b8b9a1681a982313ed7129c3c0,1aac2b5adf8aec2c00fe67d06aa8ebc2,f819f0c84a64f02d3a5606ca95edd272,watches_gifts,540.00,16.22,boleto,556.22,08-03-2018 16:01,20-03-2018 22:27,556.22
...,...,...,...,...,...,...,...,...,...,...,...
117397,ff85c3e4329457e83cb474799a257ccc,bebdd0fa741d459ddb69cf8862bb641c,144266e1585320d057797a369596bb8b,cool_stuff,899.00,17.50,credit_card,916.50,17-01-2018 14:02,21-01-2018 17:44,916.50
117506,ffc2638415f3ce34e88641eef792c1fc,cfd66b47b20e40dc4aef3c309508604e,bc2d6310e5cbd60facb2f9c8d9471597,cool_stuff,629.00,67.08,credit_card,696.08,06-06-2017 12:34,16-06-2017 17:23,696.08
117510,ffc49b9c9d666410e9ecdb0a3efadb9c,e175dcb4b025365a33467693abf7b4ca,f96ff9b997681965689f78bef092fdd9,health_beauty,765.00,27.06,credit_card,792.06,28-05-2018 19:29,12-06-2018 18:57,792.06
117525,ffd5e80bfdaf69504efd7562a3d522dd,467bcdf6e97d661f3947ad9308dcb0cc,bd67e67dcfcc53e712a29c215ec26de5,sports_leisure,584.90,16.65,credit_card,601.55,22-08-2017 09:29,23-08-2017 14:51,601.55
117586,fff7c4452f050315db1b3f24d9df5fcd,dec8952e97ef6124259c56914fb3569c,dd469c03ad67e201bc2179ef077dcd48,watches_gifts,736.00,20.91,credit_card,756.91,01-06-2017 16:53,08-06-2017 13:04,756.91

In [ ]:
# filter where Price > 100 and Sales < 1000.
sales[(sales['price']>100) & (sales['total_price']<1000)]

,order_id,customer_id,product_id,category_english,price,freight_value,payment_type,payment_value,order_purchase_timestamp,order_delivered_customer_date,total_price
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,e5f2d52b802189ee658865ca93d83a8f,pet_shop,239.90,19.93,credit_card,259.83,26-04-2017 10:53,12-05-2017 16:04,259.83
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,c777355d18b72b67abbeef9df44fd0fd,furniture_decor,199.00,17.87,credit_card,216.87,14-01-2018 14:33,22-01-2018 13:19,216.87
4,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,ac6c3623068f30de03045865e4e10089,garden_tools,199.90,18.14,credit_card,218.04,04-02-2017 13:57,01-03-2017 16:42,218.04
7,000576fe39319847cbb9d288c5617fa6,9ed5e522dd9dd85b4af4a077526d8117,557d850972a7d6f792fd18ae1400d9b6,garden_tools,810.00,70.75,credit_card,880.75,04-07-2018 12:08,09-07-2018 14:04,880.75
8,0005a1a1728c9d785b8e2b08b904576c,16150771dfd4776261284213b89c304e,310ae3c140ff94b03219ad0adc3c778f,health_beauty,145.95,11.65,credit_card,157.60,19-03-2018 18:40,29-03-2018 18:17,157.60
...,...,...,...,...,...,...,...,...,...,...,...
117589,fff8287bbae429a99bb7e8c21d151c41,6c1e92a209dbf868706caa831090941e,bee2e070c39f3dd2f6883a17a5f0da45,computers_accessories,180.00,48.14,credit_card,456.28,17-03-2018 12:11,07-04-2018 10:07,228.14
117591,fffa82886406ccf10c7b4e35c4ff2788,a5201e1a6d71a8d21e869151bd5b4085,bbe7651fef80287a816ead73f065fc4b,sports_leisure,229.90,44.02,credit_card,273.92,18-12-2017 16:33,08-01-2018 18:23,273.92
117598,fffbee3b5462987e66fb49b1c5411df2,11a0e041ea6e7e21856d2689b64e7f3a,6f0169f259bb0ff432bfff7d829b9946,home_construction,119.85,20.03,credit_card,139.88,19-06-2018 09:27,05-07-2018 17:51,139.88
117599,fffc94f6ce00a00581880bf54a75a037,b51593916b4b8e0d6f66f2ae24f2673d,4aa6014eceb682077f9dc4bffebc05b0,housewares,299.99,43.41,boleto,343.40,23-04-2018 13:57,10-05-2018 22:56,343.40
117600,fffcd46ef2263f404302a634eb57f7eb,84c5d4fbaf120aae381fad077416eaa0,32e07fd915822b0765e448c4dd74c828,computers_accessories,350.00,36.53,boleto,386.53,14-07-2018 10:26,23-07-2018 20:31,386.53

In [ ]:
sales.isnull().sum()

order_id                            0
customer_id                         0
product_id                          0
category_english                 1723
price                               0
freight_value                       0
payment_type                        3
payment_value                       3
order_purchase_timestamp            0
order_delivered_customer_date    2567
total_price                         0
dtype: int64

In [ ]:
sales['category_english'].value_counts()

category_english
bed_bath_table               11823
health_beauty                 9975
sports_leisure                8945
furniture_decor               8744
computers_accessories         8082
                             ...
arts_and_craftmanship           24
la_cuisine                      16
cds_dvds_musicals               14
fashion_childrens_clothes        8
security_and_services            2
Name: count, Length: 71, dtype: int64

In [ ]:
# sales['category_english'].fillna('bed_bath_table', inplace=True)
sales['category_english'] = sales['category_english'].fillna('bed_bath_table')

In [ ]:
sales.isnull().sum()

order_id                            0
customer_id                         0
product_id                          0
category_english                    0
price                               0
freight_value                       0
payment_type                        3
payment_value                       3
order_purchase_timestamp            0
order_delivered_customer_date    2567
total_price                         0
dtype: int64

In [ ]:
sales['payment_value'].mean()

172.68675189836821

In [ ]:
sales['payment_value'].median()

108.21

In [ ]:
sales['payment_value'].fillna(sales['payment_value'].median(), inplace=True)
sales.isnull().sum()

/tmp/ipykernel_61/2506572235.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sales['payment_value'].fillna(sales['payment_value'].median(), inplace=True)

order_id                            0
customer_id                         0
product_id                          0
category_english                    0
price                               0
freight_value                       0
payment_type                        3
payment_value                       0
order_purchase_timestamp            0
order_delivered_customer_date    2567
total_price                         0
dtype: int64

In [ ]:
sales.drop('order_delivered_customer_date',axis=1, inplace=True)

In [ ]:
sales.isnull().sum()

order_id                    0
customer_id                 0
product_id                  0
category_english            0
price                       0
freight_value               0
payment_type                3
payment_value               0
order_purchase_timestamp    0
total_price                 0
dtype: int64

In [ ]:
sales['Profit'] = sales['total_price'] - sales['freight_value']

In [ ]:
sales['Profit'].describe()

count    117604.000000
mean        120.822849
std         184.477367
min           0.850000
25%          39.900000
50%          74.900000
75%         134.900000
max        6735.000000
Name: Profit, dtype: float64

In [ ]:
sales['log_price'] = np.log(sales['Profit'])

In [ ]:
sales.head(5)

,order_id,customer_id,product_id,category_english,price,freight_value,payment_type,payment_value,order_purchase_timestamp,total_price,Profit,log_price
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,4244733e06e7ecb4970a6e2683c13e61,cool_stuff,58.90,13.29,credit_card,72.19,13-09-2017 08:59,72.19,58.90,4.075841
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,e5f2d52b802189ee658865ca93d83a8f,pet_shop,239.90,19.93,credit_card,259.83,26-04-2017 10:53,259.83,239.90,5.480222
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,c777355d18b72b67abbeef9df44fd0fd,furniture_decor,199.00,17.87,credit_card,216.87,14-01-2018 14:33,216.87,199.00,5.293305
3,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,7634da152a4610f1595efa32f14722fc,perfumery,12.99,12.79,credit_card,25.78,08-08-2018 10:00,25.78,12.99,2.564180
4,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,ac6c3623068f30de03045865e4e10089,garden_tools,199.90,18.14,credit_card,218.04,04-02-2017 13:57,218.04,199.90,5.297817

In [ ]:
sales['payment_type'].value_counts(normalize=True)

payment_type
credit_card    0.737825
boleto         0.194446
voucher        0.053350
debit_card     0.014379
Name: proportion, dtype: float64

In [ ]:
sales.shape[0]*0.737825

86771.17129999999